### ISSUE TITLE
Install-to-internal-storage script broken on arch

### ISSUE THREAD

**Issue by DumbGameMaker** [cb-linux/breath#100]
It looks like the arch installer uses the same script as ubuntu for install-to-internal-storage, so it exits with apt not found

**Comment by DumbGameMaker** [comment]
the script works fine otherwise, just needs some extra stuff to build some aur stuff from source :/

**Comment by DumbGameMaker** [comment]
something like this
```sh

git clone https://aur.archlinux.org/flashrom-git.git
git clone https://aur.archlinux.org/trousers.git
git clone https://aur.archlinux.org/vboot-utils.git

cd ./flashrom-git  && makepkg -cis 
cd ../trousers     && makepkg -cis
cd ../vboot-utils  && makepkg -cis 

pacman -Syu rsync curl

cd ../
rm -rf ./flashrom-git ./trousers ./vboot-utils
```

**Comment by MilkyDeveloper** [comment]
I've updated the script to include this in the latest commit. It'll be included in new builds, but you can download the script from `bin`  and make it executable to replicate this.
