### ISSUE TITLE
Sound settings in Ubuntu

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#102]
The sound is working -- that's the important thing!  But there is no "Output Device" listed in "Settings > Sound"  so none of the other sliders work, either.  I assume this is because Ubuntu relies (by default) upon pulseaudio and we'd have to do some tweaking (if even possible) to get it to recognize the SOF audio?

**Comment by MilkyDeveloper** [comment]
I believe this is fixed when PulseAudio is working, so I think we can merge this issue into #113
