### ISSUE TITLE
No microphone

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#103]
There is still no microphone -- I think you are aware of this.  Is this like the APL audio issue?  I assume it is related?

**Comment by MilkyDeveloper** [comment]
Yes - this is an APL audio issue I think.

**Comment by RodBarnes** [comment]
To be clear:  A solution for he audio out aspect of APL SOF resulted from the effort in [thesofproject/sof](https://github.com/thesofproject/sof/issues/5361), correct?  And we'd need to fall upon a similar effort to get audio out working?

**Comment by MilkyDeveloper** [comment]
I have no idea. Probably has something to do with UCM files from ChromeOS.
