### ISSUE TITLE
No sound on Asus CX5 Flip(volteer board)

### ISSUE THREAD

**Issue by Fornball** [cb-linux/breath#107]
On ubuntu + kde

**Comment by MilkyDeveloper** [comment]
What's the output of `sudo dmesg` and `sudo alsa-info` (and the file created in `/tmp` by it)?

**Comment by Fornball** [comment]
[alsa-info.txt](https://github.com/cb-linux/breath/files/8311996/alsa-info.txt)
[dmesg.txt](https://github.com/cb-linux/breath/files/8311997/dmesg.txt)
No file in /tmp instead http://alsa-project.org/db/?f=471d204dc01eb95eb67cb5e5b566524089a3610e

**Comment by Fornball** [comment]
Neither aux port nor bluetooth headphones work either. Plugging into the aux port does absolutely nothing. Pairing with headphones says no protocol available.

**Comment by MilkyDeveloper** [comment]
Output of ls /lib/firmware/intel/sof/community/sof-tgl.ri

**Comment by Fornball** [comment]
There is no such file...
![Screenshot_20220320_193608](https://user-images.githubusercontent.com/46828271/159179704-531e0102-1718-44bc-b27e-b32297967bba.png)

**Comment by MilkyDeveloper** [comment]
Run `git clone https://github.com/thesofproject/sof-bin` and then `sudo ./install.sh v2.0.x`. Reboot, and if audio doesn’t work, show me the output of `alsa-info`.

**Comment by Fornball** [comment]
First I had to rm -rf the old sof and sof-tplg folders(otherwise installer threw some error). Then I did a reboot. Then I ran the install command which gave me this:
[install-output.txt](https://github.com/cb-linux/breath/files/8312169/install-output.txt)
One more reboot. Still no audio tho.
[new_alsa_output.txt](https://github.com/cb-linux/breath/files/8312171/new_alsa_output.txt)
http://alsa-project.org/db/?f=27992827835ea10c622143c8a4f607f3325f67b4

**Comment by MilkyDeveloper** [comment]
You removed a neccesary directory, `v2.0.x`. Please refollow the directions exactly as said.

**Comment by MilkyDeveloper** [comment]
Try running exactly (including the slashes):
```
cd v2.0.x/
sudo rm -rf /lib/firmware/intel/sof
sudo rm -rf /lib/firmware/intel/sof-tplg
sudo rsync -a sof-v2.0/ /lib/firmware/intel/sof/
sudo rsync -a sof-tplg-v2.0/ /lib/firmware/intel/sof-tplg/
```
Audio should work then.

**Comment by MilkyDeveloper** [comment]
Did it work :D?

**Comment by Fornball** [comment]
Hey, sorry for the late reply. I tried all the commands(except I used v2.1 instead of v.2.0) and the audio does work now, although the quality of the "custom tuned harman/kardon high quality speakers" seems to be much worse(especially the bass frequencies). 
Probably needs some tweaking to pulseaudio.

**Comment by Fornball** [comment]
Hey, had to wipe the usb stick. Reinstalled, Ubuntu 22.04 with gnome. Tried the commands from the docs: ```sof-setup-audio``` and ```SOUNDCARD=rtk sof-setup-audio```
Tried this, with v2.0, 2.1, 2.2:
```
cd v2.0.x/
sudo rm -rf /lib/firmware/intel/sof
sudo rm -rf /lib/firmware/intel/sof-tplg
sudo rsync -a sof-v2.0/ /lib/firmware/intel/sof/
sudo rsync -a sof-tplg-v2.0/ /lib/firmware/intel/sof-tplg/
```
Doesnt work either.
[alsa-info.txt](https://github.com/cb-linux/breath/files/8966356/alsa-info.txt)

**Comment by Fornball** [comment]
So... Confusing update. Apparently gnome doesnt see the audio device(shows as dummy in settings). Neither do the browsers(no sound when playing back audio, even with volume at 100%). 
But when I tried installing android in a virtual machine(qemu through virt manager), that virtual android system makes sounds through the speakers...
Any idea why gnome/ubuntu cant use the speakers, but a virtual machine can? @MilkyDeveloper

**Comment by MilkyDeveloper** [comment]
It has nothing to do with virtual machines, rather that QEMU talks directly to ALSA. I believe that this is a problem with Pipewire. Try running:
```
systemctl --user mask pipewire
systemctl --user mask pipewire.socket
sudo apt install pulseaudio -y
```

and reboot.

**Comment by Fornball** [comment]
Ran the commands(pulseaudio was already installed btw) and rebooted, but nothing changed.

**Comment by Fornball** [comment]
speaker-test produces no sounds.
[pactl.txt](https://github.com/cb-linux/breath/files/8969520/pactl.txt)

**Comment by Fornball** [comment]
Any other solutions?

**Comment by Fornball** [comment]
> Reopen the issue if not completed

I am not sure I can reopen issues... But the fix doesnt work on a clean install either.

**Comment by runcros** [comment]
Can you add me on discord, we will try somes procedure. Discord : runcros#0615
