### ISSUE TITLE
ARM chromebook

### ISSUE THREAD

**Issue by techyporcupine** [cb-linux/breath#108]
I would like to build for my ARM chromebook. Is this even possible? If so, how do I? Thanks in advance!

**Comment by techyporcupine** [comment]
I want to build for a Lenovo N23 Yoga (hana) chromebook.

**Comment by MilkyDeveloper** [comment]
This project is currently focusing on x86 Chromebooks. You'll find Cadmium OS as a great alternative for ARM Chromebooks.
