### ISSUE TITLE
Pixel Slate GPU + Sound glitch

### ISSUE THREAD

**Issue by Laurin-PhilipHahn** [cb-linux/breath#109]
Hey I am experiencing graphical glitches (lines on screen) + the usual audio missing. 

Is there a way to update the video-driver or sth else? 

Cheers

**Comment by MilkyDeveloper** [comment]
What is the output of `dmesg`?

**Comment by org-tekeli-borisp** [comment]
@Laurin-PhilipHahn I had the same issue with horizontal lines glitchtes on the screen on Pop_OS. 
Disabling Panel Self Refresh was the answer for me. 

Use  **i915.enable_psr=0** as kernel parameter 
or
`sudo echo "options i915 enable_psr=0" >> /etc/modprobe.d/i915.conf`

Any success with the audio? 
I mean chromeos is linux based. There should be a solution for no sound issue...

**Comment by MilkyDeveloper** [comment]
@org-tekeli-borisp please provide a `dmesg` and the output of `sudo alsa-info` (when it asks for a link, say yes and post it here).

**Comment by org-tekeli-borisp** [comment]
@MilkyDeveloper My Slate is not on cb-linux but on Pop_Os with  (UEFI) Full ROM, so probably my dmesg / alsa info will not be very helpful. 
http://alsa-project.org/db/?f=ac7b4fb2a2a2166a53ec922fadbb5630b2151a7e

**Comment by org-tekeli-borisp** [comment]
@MilkyDeveloper  I found https://github.com/cb-linux/breath/blob/main/bin/setup-audio. 
Did I get it right, that cb-linux is using files from chromeos distro for enabling audio?

**Comment by MilkyDeveloper** [comment]
Yeah, cb-linux is using files from the ChromeOS root filesystem. It also uses a custom kernel, so these logs are pretty irrelevant.

**Comment by runcros** [comment]
Closing this issue because no answer from original author from 21 march
