### ISSUE TITLE
Please clearify something about sleep/bootlock

### ISSUE THREAD

**Issue by logan2k** [cb-linux/breath#114]
Hello.

After reading "https://cb-linux.github.io/breath/docs.html#/bootlock", I have a few questions:
1. "This makes you never need to press CTRL+D to boot" - Even after completely shut down?
2. "if ChromeOS has been wiped, you can’t re-enable USB and Unsigned kernel booting." - So in this case the device is bricked?

Thanks.

**Comment by avram-meir** [comment]
> 
>     1. "This makes you never need to press CTRL+D to boot" - Even after completely shut down?
> 

After a complete shutdown, you still would need to press ctrl-D to boot from the internal storage. Or you could wait about 30 seconds and the machine will beep twice and then boot from internal storage. I'm not sure why the docs say you won't have to press ctrl D again.

>     2. "if ChromeOS has been wiped, you can’t re-enable USB and Unsigned kernel booting." - So in this case the device is bricked?
> 

No, it's very unlikely that breath can brick a chromebook. If the USB and unsigned kernel boot flags get reset, then you wouldn't be able to boot an OS from a USB disk, and possibly not a non-ChromeOS OS from internal storage. In this case, the device is not bricked. You would have to restore ChromeOS from a ChromeOS recovery USB (e.g., turn off, then press esc+refresh+refresh (F3)) to boot into recovery mode, then reinstall ChromeOS from USB. This would wipe out whatever you had on the internal storage, but you'd be left with a "factory reset" chromebook.
> 
> Thanks.

**Comment by avram-meir** [comment]
Note: I'm not a Breath dev, so don't take what I wrote as the final word. I just answered from my own experience tinkering with my chromebooks.

**Comment by MilkyDeveloper** [comment]
Everything @avram-meir said is completely true! I couldn’t explain it better.

**Comment by logan2k** [comment]
Thank you friends!
