### ISSUE TITLE
No audio on the AKALI360 (Acer Spin 13) board

### ISSUE THREAD

**Issue by sgulino** [cb-linux/breath#117]
_Hello,_

I'm running Ubuntu 21.04 on an Acer Spin 13 (NAMI). After running setup-audio, I am able to see the soundcard in alsamixer; however, the soundcard is not appearing in my Ubuntu system settings and I still cannot hear anything. 

Here's an alsa-info dump: http://alsa-project.org/db/?f=8088832603e27ce02756d681db06508c4c717797
Here's the result of aplay -l:

**** List of PLAYBACK Hardware Devices ****
card 0: kblda7219max [kblda7219max], device 0: Audio (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: kblda7219max [kblda7219max], device 4: Hdmi1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: kblda7219max [kblda7219max], device 5: Hdmi2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: kblda7219max [kblda7219max], device 6: Hdmi3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I appreciate whatever support you can give.

**Comment by ArtemPozharov** [comment]
I support @sgulino . @MilkyDeveloper said that I should start it from scratch to achieve the result, but I still can't get the sound. The output from aplay and speaker-test is the same. 
Maybe the inventor should show the video with actions step-by-step to dispel doubts? We would be right happy to!

**Comment by MilkyDeveloper** [comment]
According to the output of `alsa-info`, you didn't update the kernel. On the docs, it says first to run:
> `VERSION=ALT bash updatekernel.sh` on the PC you built Breath with

Since you did not run this first, you have to run `rm -rf /usr/share/alsa/ucm2/kblda7219max*` on your chromebook. Then, run `VERSION=ALT bash updatekernel.sh; sync` (on your PC, not your chromebook). You can boot the chromebook and _then_ run `setup-audio`.

**Comment by ArtemPozharov** [comment]
> According to the output of `alsa-info`, you didn't update the kernel as instructed in the docs. On the docs, it says first to run:
> > `VERSION=ALT bash updatekernel.sh` on the PC you built Breath with
> 
> Since you did not run this first, you have to run `rm -rf /usr/share/alsa/ucm2/kblda7219max*` on your chromebook. Then, run `VERSION=ALT bash updatekernel.sh; sync` (on your PC, not your chromebook). You can boot the chromebook and _then_ run `setup-audio`.

Can I use updatekernel-on-emmc instead of using the second PC?

**Comment by MilkyDeveloper** [comment]
You can try, but it might not work due to a kernel bug in syncing.

**Comment by sgulino** [comment]
speaker-test gives the following:

> seby@ubuntu:~$ speaker-test
> 
> speaker-test 1.2.4
> 
> Playback device is default
> Stream parameters are 48000Hz, S16_LE, 1 channels
> Using 16 octaves of pink noise
> Rate set to 48000Hz (requested 48000Hz)
> Buffer size range from 2048 to 16384
> Period size range from 1024 to 1024
> Using max buffer size 16384
> Periods = 4
> was set period_size = 1024
> was set buffer_size = 16384
>  0 - Front Left

I can't hear anything, though. Unfortunately the alsaucm call you provided didn't change anything.

**Comment by sgulino** [comment]
Will PulseAudio break things further? Or should I try to install it?

**Comment by sgulino** [comment]
When I enter `alsamixer`, `Master` is stuck at 100; it's maxed out and I can't even lower it.

**Comment by ArtemPozharov** [comment]
I ran update-kernel-on-emmc. It finished successful. I ran setup-audio as usually. Sound is not exist. ![IMG_20220323_204733.jpg](https://user-images.githubusercontent.com/50730813/159783454-46722d04-e38d-4719-a85e-63b6fa5a21f9.jpg)

**Comment by MilkyDeveloper** [comment]
@ArtemPozharov what is the output of `uname -r`? Seems like the kernel still did not update.

**Comment by ArtemPozharov** [comment]
5.10.106. Which value should be?

**Comment by MilkyDeveloper** [comment]
`5.10.70`

**Comment by ArtemPozharov** [comment]
If I run updatekernel.sh, is it mandatory to have a preinstalled Chrome OS on Chromebook to install Ubuntu?

**Comment by MilkyDeveloper** [comment]
Yes.

**Comment by ArtemPozharov** [comment]
I ran updatekernel.sh with Linux laptop which did NOT build the image for my Chromebook. I selected a required USB drive, wrote the kernel, rebooted to Chromebook with Ctrl+U, but still see the Linux kernel 5.10.106.

**Comment by ArtemPozharov** [comment]
In addition, WiFi become broken on USB stick.

**Comment by MilkyDeveloper** [comment]
@sgulino I don't think booting from a USB/SDCard would make a difference, your lack of audio is probably due to UCM files.

**Comment by MilkyDeveloper** [comment]
```
git clone https://github.com/cb-linux/cb-ucm
cd cb-ucm/nami/akali360
rm /usr/share/alsa/ucm2/kblda7219max/*
sudo cp * /usr/share/alsa/ucm2/kblda7219max
```

**Comment by sgulino** [comment]
Just did a new install on a USB following instructions, to have a clean slate.

Here's the result of a search for pulseaudio and pipewire packages:
```
seby@ubuntu:~$ sudo apt list --installed | grep -E 'pulseaudio|pipewire'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gstreamer1.0-pulseaudio/impish,now 1.18.5-1ubuntu2 amd64 [installed]
libpipewire-0.3-0/impish,now 0.3.32-1 amd64 [installed,automatic]
libpipewire-0.3-common/impish,now 0.3.32-1 all [installed,automatic]
libpipewire-0.3-modules/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire-bin/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire-media-session/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire/impish,now 0.3.32-1 amd64 [installed,automatic]

```

I'll remove the packages and report back.

Unrelated question: do I need to remove write protection to run the install to internal storage script?

**Comment by MilkyDeveloper** [comment]
No, you don't need to remove WP to run the install script. It seems like everyone's audio is breaking on newer installs because either PulseAudio or Pipewire is installed. However, Pipewire is a dependency of `gnome-session`, so maybe:
```
systemctl --user disable pipewire.socket
systemctl --user disable pipewire.service
```
would work better.

**Comment by MilkyDeveloper** [comment]
In installs created with the commit I just published, this should be done by default.

**Comment by sgulino** [comment]
When I run `alsaucm -c kblda7219max set _verb HiFi set _enadev Speaker` I get the following output: 

```
ALSA lib parser.c:1846:(parse_master_file) Syntax field not found in kblda7219max.conf
ALSA lib main.c:1014:(snd_use_case_mgr_open) error: failed to import kblda7219max use case configuration -22
alsaucm: error failed to open sound card kblda7219max: Invalid argument
```

**Comment by MilkyDeveloper** [comment]
Add `Syntax 3` to the top of `/usr/share/alsa/ucm2/kblda7219max/kblda7219max.conf`

**Comment by sgulino** [comment]
Command worked, but I'm right back to where I was earlier: speaker-test returning no sound, despite nothing being muted in alsamixer.

Do you also have all of the pulsewire packages I listed above? should I remove any of those?

**Comment by MilkyDeveloper** [comment]
Remove all of the packages you mentioned above.

**Comment by sgulino** [comment]
When I remove the packages above, I am no longer able to start a desktop session. 

In order to log back into my Budgie desktop, I had to run `apt install --reinstall ubuntu-budgie-desktop`. That re-installed a lot of the packages automatically:

```
gstreamer1.0-pulseaudio/impish,now 1.18.5-1ubuntu2 amd64 [installed,automatic]
libpipewire-0.3-0/impish,now 0.3.32-1 amd64 [installed,automatic]
libpipewire-0.3-common/impish,now 0.3.32-1 all [installed,automatic]
libpipewire-0.3-modules/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire-bin/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire-media-session/impish,now 0.3.32-1 amd64 [installed,automatic]
pipewire/impish,now 0.3.32-1 amd64 [installed,automatic]
pulseaudio-module-bluetooth/impish-updates,now 1:15.0+dfsg1-1ubuntu2.2 amd64 [installed,automatic]
pulseaudio-utils/impish-updates,now 1:15.0+dfsg1-1ubuntu2.2 amd64 [installed,automatic]
pulseaudio/impish-updates,now 1:15.0+dfsg1-1ubuntu2.2 amd64 [installed,automatic]
```
I'm going to run `apt remove` for pulseaudio and pipewire alone, and leave the libs/gstreamer. Will report back.

**Comment by MilkyDeveloper** [comment]
You could just run 
```
systemctl --user mask pipewire.socket
    systemctl --user mask pipewire.service
    systemctl --user mask pulseaudio.socket
    systemctl --user mask pulseaudio.service
```

**Comment by sgulino** [comment]
I successfully removed the packages and also masked the services to be safe. 

I've got two observations; they might be helpful.

1) I'm getting a crackling noise if I unmute `codec1_out mo media0_in mi` in `alsamixer`.
2) I've noticed the following when running dmesg:
```
[   63.312080] snd_soc_skl 0000:00:1f.3: Invalid pipe config: 2 48000 24 for pipe: 2
[   63.312084] snd_soc_skl 0000:00:1f.3: ASoC: PRE_PMU: codec0_out mo event failed: -22
[   71.287682] snd_soc_skl 0000:00:1f.3: ASoC: POST_PMD: codec0_out mo event failed: -22
```

**Comment by MilkyDeveloper** [comment]
Must be the toplogy/kernel version. Try playing around some more with `alsamixer`. Just to make sure, what's the output of `uname -r` within ChromeOS?

**Comment by sgulino** [comment]
I'll continue playing around with each item in the mixer.

uname -r returns `5.4.172-17736-gfddbc46e9604`

**Comment by sgulino** [comment]
OKAY big progress: internal speakers don't work, but the headphone jack is working -- I am now getting audio (right channel only) from the jack. A massive improvement. I'm going to continue tooling around with ALSA configuration. 

I appreciate all of your help.

**Comment by MilkyDeveloper** [comment]
How did internal speakers work? After rebooting or did you need to change anything else in alsamixer? :D

Headphone jacks are a WIP, even for newer SOF devices, so I’m going to be closing this for now.

**Comment by sgulino** [comment]
Spoke too soon. 

Internal speakers never worked; headphone jack worked perfectly. 

Unfortunately, it's now back to not working at all -- it was just playing static from my headphones, and now I can't get it to play anything. 

Back to the drawing board! I'm trying to reset Alsa settings and hoping I can get lucky in the config one more time. I'll be more careful to note down exactly what I do if I get it to work this time.

**Comment by sgulino** [comment]
Looks like it's related to mux settings; changing the `Out DACL Mux`, `Out DACR Mux`, `Out DAIR Mux`, and `Out DAIL Mux` settings all either provide static or tone generator output.

**Comment by MilkyDeveloper** [comment]
You could get this perfect configuration by running `alsactl store` within ChromeOS. There should be a file created in `/var/lib/alsa` that has the name `asound.state`. Copy this to `/var/lib/alsa/asound.state` and to `/etc/asound.state` in the Breath USB.

**Comment by sgulino** [comment]
I don't think ChromeOS has alsa; I'm getting `command not found`. Any way to install it onto ChromeOS? 

I got static from `speaker-test -c 2 -t wav`; there should not have been static there, as it should have instead read out each channel. It also would change from static to tone generation when I set either DACL or DACR mux to `Tone Generator`, proving that alsa is working to some extent

**Comment by sgulino** [comment]
okay; `alsamixer` works in chronos, but `alsactl` does not work. I'll manually copy the settings and report back

**Comment by sgulino** [comment]
Using identical settings & playing around with ST mixer output filters, I'm now able to hear sound in both ears in all applications!

new problem: it's all in slow motion and sounds ridiculous.

**Comment by sgulino** [comment]
Looks like either an issue with alsa configuration (maybe format sampling or rate?). Might be related to my upgrade to Ubuntu 21.10 impish. Not sure how to adjust audio timers or clocks, but I'll see what I can do
