### ISSUE TITLE
Build on arch linux possible?

### ISSUE THREAD

**Issue by timmypidashev** [cb-linux/breath#119]
Just wondering if it is reasonable to allow this awesome installer to run on other arch-based distributions. If yes, then I can happily open a pull request and get to work setting that up. I'm just curious because it seems to rely heavily on a kernel build, and since crostini is debian based I'm wondering if that's the only way to properly build breath. Anyways thankyou for an awesome project.

**Comment by MilkyDeveloper** [comment]
Yes, it should be. Do note a few things:
* Breath is suppossed to be built on Ubuntu/Debian fully booted on a UEFI/EFI/BIOS PC, not Crostini under any circumstances.
* Users don't need to build the kernel; I build the kernel and then redistribute it on the releases page.

**Comment by timmypidashev** [comment]
Alright, this makes more sense. I will begin working on a pr :)
