### ISSUE TITLE
Missing wifi... Something

### ISSUE THREAD

**Issue by mrhappyma** [cb-linux/breath#125]
Hello! Just finished building the USB, booted it, and wifi settings shows this:

![image](https://user-images.githubusercontent.com/55963440/160155270-93433545-9b31-47bf-a7c0-46254c59de8b.jpeg)

**Comment by MilkyDeveloper** [comment]
Does `nmtui` work? What is your device model? What's the output of `lspci -vvvv`?

**Comment by mrhappyma** [comment]
i redid the script to build the usb and new one works fine for wifi
