### ISSUE TITLE
touch pad slow to respond xubuntu samsung chromebook 4

### ISSUE THREAD

**Issue by kylepwarren** [cb-linux/breath#137]
If I apply moderate pressure(considerably more than what is intuitive [how most touch pads work {or this one in chrome os}]) or accelerate quickly the input 'activates' and the cursor begins moving.

**Comment by MilkyDeveloper** [comment]
You can Google how to adjust touchpad sensitivity. It would be near impossible to maintain, test, and implement touchpad profiles for more than 25 boards. Sorry about this, I am unable to fix this.

**Comment by kylepwarren** [comment]
Just want to be clear, I don't think this is a sensitivity issue, I think it's a hardware comparability issue. I tried to describe what was going on in a way to make it clear, I guess I failed.

**Comment by RodBarnes** [comment]
@kylepwarren FYI: I encountered this same issue when running Lubuntu on Breath.  I have not encountered it running Ubuntu.  My assumption has been that it is a DE-related issue so I haven't pursued it in the light of other issues (e.g., audio).

**Comment by MilkyDeveloper** [comment]
@kylepwarren If all functions of the touchpad are working, however degraded, it is not a kernel bug (hw compat issue) and it is userspace.

**Comment by kylepwarren** [comment]
> @kylepwarren FYI: I encountered this same issue when running Lubuntu on Breath. I have not encountered it running Ubuntu. My assumption has been that it is a DE-related issue so I haven't pursued it in the light of other issues (e.g., audio).

I see. I tried regular ubuntu, which I guess comes with gnome. touchpad worked fine there. Installed xfce-desktop there, touch pad works fine (in xfce as a secondary desktop in regular ubuntu).


This project is awesome. Thanks. 
*I've installed it on the internal drive,
Should I just be able to run the upgradekernal command and probably go through some of the audio setup stuff again when there is a new release? Pretty sure all the info about upgrades I've seen were about on a usb stick.

**Comment by kylepwarren** [comment]
> You don't need to run `updatekernel.sh`. I'm pretty sure you have a GLK device, and you only need to run `sof-setup-audio`.

I didn't meant specifically related to sound, more generally: is there a straight forward / easy way to update everything 'install-to-internal-storage' installs?

**Comment by MilkyDeveloper** [comment]
The only thing that really updates an image would be upgrading Ubuntu itself, which you can do the same as any other PC (dist-upgrade). The updatekernel-on-emmc  script is currently broken because of a very irresponsible kernel bug by the ChromeOS kernel team.

**Comment by kylepwarren** [comment]
For example, 'sof-setup-audio' was recently updated. Is there an update process to update that in internal storage?

**Comment by MilkyDeveloper** [comment]
No, not at the moment. You could just download the script again from the `bin` directory.

**Comment by RodBarnes** [comment]
The setup scripts can just be copied to an existing image in internal storage; they all go into /usr/local/bin.
