### ISSUE TITLE
Add note saying upper case letters will break Debian install

### ISSUE THREAD

**Issue by Corgi** [cb-linux/breath#141]
I'm unfamiliar with Linux systems and did not realize you can't have capital letters in the user name, and accidentally spent most of my day trying to troubleshoot why my created IMG files were failing. The "choose your username" dialog specifies no special characters, etc, but says nothing about capital letters (unless I am new and improved levels of blind).

Just hoping to save someone else the trouble I went through. Really excited to try this out now that I've learned my lesson!

**Comment by MilkyDeveloper** [comment]
Should be fixed now, thanks for opening this issue.
