### ISSUE TITLE
Ubuntu Samsung Chromebook 4, volume control looks functional, but only mute works

### ISSUE THREAD

**Issue by kylepwarren** [cb-linux/breath#144]
moving the volume slider does nothing.
Mute works. 
I've also tried in the full mixer - same thing.

There is only one output device, it's labeled headphones.
I tried plugging in actual headphones to see if the volume would work there.
    The headphones did not work at all. no sound.

**Comment by MilkyDeveloper** [comment]
So do internal speakers work without volume control?

**Comment by kylepwarren** [comment]
Yes. I guess the volume is at 100%. I tried alsamixer too just to see what would happen, same thing. Only mute works

**Comment by MilkyDeveloper** [comment]
What is the output of `sudo alsa-info`, and `pacmd list-sinks`?

**Comment by kylepwarren** [comment]
`❯ sudo alsa-info
ALSA Information Script v 0.4.65
--------------------------------

This script visits the following commands/files to collect diagnostic
information about your ALSA installation and sound related hardware.

  dmesg
  lspci
  aplay
  amixer
  alsactl
  rpm, dpkg
  /proc/asound/
  /sys/class/sound/
  ~/.asoundrc (etc.)

See '/usr/sbin/alsa-info --help' for command line options.

cat: /proc/asound/modules: No such file or directory
Automatically upload ALSA information to www.alsa-project.org? [y/N] : 
Your ALSA information is in /tmp/alsa-info.txt.K8hV5qldGC


============

❯ pacmd list-sinks
1 sink(s) available.
  * index: 1
	name: <alsa_output.pci-0000_00_0e.0-platform-glk_da7219_mx98357a.stereo-fallback>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: (none)
	priority: 9030
	volume: front-left: 2621 /   4%,   front-right: 2621 /   4%
	        balance 0.00
	base volume: 65536 / 100%
	volume steps: 256
	muted: no
	current latency: 25.53 ms
	max request: 4 KiB
	max rewind: 4 KiB
	monitor source: 1
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Stereo
	used by: 1
	linked by: 3
	configured latency: 26.00 ms; range is 26.00 .. 341.33 ms
	card: 0 <alsa_card.pci-0000_00_0e.0-platform-glk_da7219_mx98357a>
	module: 22
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = ""
		alsa.id = "Speakers (*)"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "sof-glkda7219max"
		alsa.long_card_name = "Google-Casta-rev6"
		alsa.driver_name = "snd_soc_sst_bxt_da7219_max98357a"
		device.bus_path = "pci-0000:00:0e.0-platform-glk_da7219_mx98357a"
		sysfs.path = "/devices/pci0000:00/0000:00:0e.0/glk_da7219_mx98357a/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "3198"
		device.product.name = "Celeron/Pentium Silver Processor High Definition Audio"
		device.string = "hw:0"
		device.buffering.buffer_size = "65536"
		device.buffering.fragment_size = "16384"
		device.access_mode = "mmap+timer"
		device.profile.name = "stereo-fallback"
		device.profile.description = "Stereo"
		device.description = "Celeron/Pentium Silver Processor High Definition Audio Stereo"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-output-headphones: Headphones (priority 9900, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "audio-headphones"
	active port: <analog-output-headphones>


`

**Comment by MilkyDeveloper** [comment]
Could you provide the output of the file created by alsa info?

**Comment by kylepwarren** [comment]
[alsa-info.txt.K8hV5qldGC.txt](https://github.com/cb-linux/breath/files/8401071/alsa-info.txt.K8hV5qldGC.txt)

**Comment by kylepwarren** [comment]
The volume control for a bluetooth headset I just tried works no problem.

**Comment by brunocmorais** [comment]
I have a Samsung Chromebook 4 too and volume control works using pavucontrol and setting volume per application. Global volume control only works in alsamixer. Bluetooth headsets works with no problem.

**Comment by MilkyDeveloper** [comment]
I see. So can you control master volume? Does GUI volume control work?

**Comment by kylepwarren** [comment]
Bluetooth audio is working perfectly.

Internal speakers work (sound comes out), but the volume slider does nothing(this includes the task area widget, pavucontroller, and alsamixer). The mute function works in any of those places. (application volume control works, so it will kind of be tolerable for a while)

If I  plug in wired headphones it has no effect. Sound still comes out of the speakers, nothing comes out of the headphones.

**Comment by MilkyDeveloper** [comment]
Moving issue to here #146, check out my latest comment.
