### ISSUE TITLE
Include platform POPPY

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#147]
Running breath on poppy platform causes some devices not to work properly.
- Backlight screen
- Backlit keyboard
- audio (only headphones)

Do you have a solution?

Chromebooks concerning:
- HP Chromebook x2 (2018)
- Samsung Chromebook Plus (V2) (2018)
- Samsung Chromebook Plus LTE (2018)
- Google Pixel Slate (2018)
- Google Pixelbook Go (2019)
- Google Pixelbook (2017)

Platforms:
- Kabylake
- Kabylake-Y 
- Kabylake-U/R
- Amberlake-Y
- (Skylake)

Running ChromeOS kernel:
- 4.4

**Comment by RodBarnes** [comment]
I'm not familiar with POPPY -- do you mean Puppy?  In any case, I've had some experience with these issues on other distros:
What is the output of `brightnessctl`?  (Install it if it is not already there.

**Comment by MilkyDeveloper** [comment]
Puppy is one of the older boards. I’m pretty sure that POPPY is one of the first Kabylake Baseboards, and even my NAMI device is based on it.

Headphone jack audio doesn’t work for any device, so I won’t be focusing on it.

I’m pretty sure that keyboard backlights are handled by one of the ChromeOS kernel EC modules, so maybe lspci -vvvv and lsusb would be useful there.

By the screen backlight, do you mean the screen’s brightness? Is it at minimum brightness at default? This is again another thing that I believe ChromeOS kernel modules should be handling.

Thanks for posting this issue!

**Comment by MilkyDeveloper** [comment]
I've added some more kernel options to the script, try it out!

I don't understand your approach with `kexec`. If the ChromeOS kernel kexecs into a non-ChromeOS kernel, then you would just be using the mainline kernel, and, at that point, you could just use MrChromebox's firmware.

I've seen the CRAS audio stuff and it seems very hard to integrate. I always failed building it, and the process is overly complicated. You could try integrating it, but I cannot since Bluetooth audio works as of lately and so does internal audio.

**Comment by EMLommers** [comment]
Hi 
Have you seen the approach of Hexdump0815?
Using the ChromeOS kernel to boot into the mainline linux kernel, in order to keep the depthcharge ok.

That is something I do not want to do, to change firmware. not even RW Legacy. My goal is,  to find a  way (with help of others) to run mainline linux, on a chromebook, without changing firmware and not in developer mode. So in the end changing back from dev to normal with mainline linux ..
If we could use just a mainline kernel instead of ChromeOS kernel with vbooot and deptcharge it would be ok.
Is it possible to add in build.sh option to use mainline kernel instead of ChromeOS kernel and sign?

There is also a solution to run a bootloader (rEFind/Ventoy/etc..) as signed kernel and run.. I like to keep it secure and do not really trust UEFI or MBR.

**Comment by MilkyDeveloper** [comment]
You can boot a mainline kernel on Depthcharge without using a kexec from the ChromeOS kernel. You just put a `bzImage` into `vbutil_kernel` to sign it and then `dd` it, just like you can do with the normal ChromeOS kernel.

Throughout this whole process, you 100% *cannot* disable dev mode. It's simply impossible. DM Verity and Verified Boot Crypto would thwart this, unless you can sign your kernel from Google. If you wish to skip the timeout, you can do so by disabling the Write Protect and setting the GBB Flags to reduce the timeout from 30s to ~1s.

Also, why do you want mainline linux? There's little disadvantage to the ChromeOS kernel. 

I've tried `kexec`ing GRUB for DOS without avail. Using rEFind and Ventoy are interesting solutions that I'm currently looking at. Just wondering, why do you distrust UEFI?

**Comment by EMLommers** [comment]
My motto: nothing is impossible..
The depthcarge kernel should be signed , as the docs read, signed by anyone, not only google. 

The mainline linux kernel has updated routines, patches and additional security for several platforms, including additions from Intel, AMD and others. I am not saying always update kernel, cause sometimes it also breaks things.
When running kernel 5.13 or 5.15 on my apollolake everything is working (except audio headphones), but I will look into CRAS and see whether it solves the issue, also kabylake (and skylake derivatives) 

Why I do not trust UEFI? https://www.google.com/search?client=firefox-b-e&q=intel+uefi+vulnerabilities

u-boot/depthcarge/vboot is ideal and very secure. Why not use, or example, coreboot, slim bootloader, redboot, ventoy, rEFInd etc as signed boot partition, and keep firmware easy and simple, just secure boot and let the  boot kernel do the original bios checks and boot OS.

Currently for my apollolake I use GBB 0xd

I really love the google chromebook hardware,  but like to get away from chromeos as far as possible. ;)

`

**Comment by MilkyDeveloper** [comment]
This is a good idea. A few months ago, I made a repo [here](https://github.com/cb-linux/bootloader/discussions/1). I would reccomend you to not look at this (barebones) repository and build a kernel there using the minimal kernel config.

**Comment by EMLommers** [comment]
I will look at the kernel config and scripts and build the kernel using minimal config. Get back to you!

**Comment by RodBarnes** [comment]
> I really love the google chromebook hardware, but like to get away from chromeos as far as possible. ;)
Exactly my thoughts.  I could go get another laptop and take a simpler route but I really, really like this laptop device and so it's worth it (for me) to go down this path with Breath or something similar.

**Comment by RodBarnes** [comment]
@EMLommers I, too, have an ApolloLake device so am interested in what you find.

**Comment by EMLommers** [comment]
Build CRAS....
Still working on it.. results so far:

$ cras_test_client
System Volume (0-100): 100 
Capture Gain (0.00 - 0.00): 0.00dB 
User muted: Not muted
Output Devices:
	ID	Name
	12	sof-bxtda7219max: :0,7
	11	sof-bxtda7219max: :0,6
	10	sof-bxtda7219max: :0,5
	7	sof-bxtda7219max: :0,1
	6	sof-bxtda7219max: :0,0
Output Nodes:
	Stable Id	 ID	 Vol   Plugged	L/R swapped	      Time Hotword	Type		 Name
	(1b4c3f23)	12:0	  100       no	            no	         0        	HDMI             HDMI/DP,pcm=7 Jack
	(ea064cf9)	11:0	  100       no	            no	         0        	HDMI             HDMI/DP,pcm=6 Jack
	(92adced0)	10:0	  100       no	            no	         0        	HDMI             HDMI/DP,pcm=5 Jack
	(febb3885)	7:0	  100      yes	            no	1649703988        	UNKNOWN          (default)
	(9e934263)	6:0	  100       no	            no	         0        	HEADPHONE        Headphone
	(72a57953)	6:1	  100      yes	            no	1649703986        	INTERNAL_SPEAKER*Speaker
Input Devices:
	ID	Name
	13	sof-bxtda7219max: :0,8
	9	sof-bxtda7219max: :0,2
	8	sof-bxtda7219max: :0,1
	5	Post DSP Loopback
	4	Post Mix Pre DSP Loopback
Input Nodes:
	Stable Id	 ID	Gain   Plugged	L/R swapped	      Time Hotword	Type		 Name
	(e363fa47)	13:0	    0      yes	            no	1649704000        	UNKNOWN          (default)
	(a6476c33)	9:0	    0      yes	            no	1649703992        	UNKNOWN          (default)
	(61aab6ba)	8:0	    0       no	            no	         0        	MIC              Mic
	(4ce2eaa5)	8:1	    0      yes	            no	1649703990        	INTERNAL_MIC    *Internal Mic
	(8c74f766)	5:0	    0      yes	            no	         0        	POST_DSP_LOOPBACK Post DSP Loopback
	(8a04af91)	4:0	    0      yes	            no	         0        	POST_MIX_LOOPBACK Post Mix Pre DSP Loopback
Attached clients:
	ID	pid	uid
	16	1422	1000
	26	1422	1000
	27	3786	1000
Num active streams: 2
Last audio active time: 1297, 650531134

**Comment by MilkyDeveloper** [comment]
You're using this on Kernel 5.13, which is an external kernel not supported by Breath, but I think the same steps would apply. But I don't see the value in CRAS unless you connect it (somehow) to PulseAudio or PA :D.

**Comment by EMLommers** [comment]
I trying to build breath and run CRAS.. but not sucessfully could build breath. so I tested on non chromeos kernel.
After installing CRAS it automatically switches between headphone and  speaker. The only option for sound is cras. 
I am now going to build it on chromeOS kernel v4.4 v.4.14 and  v 5.4

**Comment by runcros** [comment]
Hello @EMLommers , poppy sound is working right now. 
Please join our discord to make it working on your platform ! https://discord.gg/WatsaYhXCa

**Comment by EMLommers** [comment]
In the meantime I installed Coreboot and running fedora with everything working... Thanks anyway!

**Comment by MilkyDeveloper** [comment]
Does it have kernel 5.19 or ahead?

**Comment by EMLommers** [comment]
5.18

**Comment by EMLommers** [comment]
Check repository pixelbook-fedora
