### ISSUE TITLE
Setup Debian #x fails

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#152]
FEATURE=ISO,KEYMAP bash ./setup.sh gnome debian stretch-9

Results in Debian 11

Also FEATURE=ISO,KEYMAP bash ./setup.sh gnome debian stretch-9.13

Same result.

**Comment by timmypidashev** [comment]
I'm looking into it right now, will try to reproduce error

**Comment by timmypidashev** [comment]
Sorry for the wait, it's still building the iso. You weren't exactly clear on the error, do you have anything you can add to clarify your issue meanwhile? Thankyou!

**Comment by EMLommers** [comment]
Ok, maybe wrong subject..
I am not able to  build other version than 11.
Trying to build  Jesse or Stretch results in Bullseye

**Comment by timmypidashev** [comment]
Ok, I did test and debian 11 builds just fine. The other variants might be the issues as mentioned. Can you mention the error that resulted, or any helpful output? Thankyou!

**Comment by EMLommers** [comment]
There is no output, only when running the iso, it will show up debian 11... even with gnome debian stretch-9

for ubuntu below 20, if gives no Release file available. 
building takes really a long  time, is it possible to use a squashfs file from livecd and use this one for ROOTFS. reduces time tremendously

**Comment by MilkyDeveloper** [comment]
Using a squashfs is unreliable to extract and automate, especially for multiple distros. This doesn’t build anything, it just downloads the packages from apt. Using the ISO feature, installing GNOME takes very little time for me (1 hour max). It offers little flexibility, and in the long run, takes more time than the current method.

So are you saying that the command works, but it doesn’t install your Debian version? I forgot to add that into debootstrap, thanks for reminding me :D

**Comment by EMLommers** [comment]
Oh  as well ass gnome ubuntu gave not recognized....

**Comment by EMLommers** [comment]
I am now building  ubuntu focal-20.04

Get Errors were encountered while processing:
libfprint-2-2:amd64
fprintd
limpam-fprintd:amd64

And than it removes all gnome wayland

and after copying modules:
cp : -r not specified 'bin/breach'

**Comment by MilkyDeveloper** [comment]
On focal, audio for SOF won’t work. You have to use a newer version for APL/GLK+ devices.

I think your experiencing all of these errors because of your host device. I cannot support all configurations.

As said in the script, ignore the errors about fprintd.

Your module errors are due to your untested changes to the code and file structure changes in ~/linux-build.

Please, stop making these unsupported changes. Rerun the commands, from the docs. Me and @timmypidashev can confirm this is working.

Sorry for the hostility on my side, but I just can’t understand your errors. Just give the exact command output.

**Comment by EMLommers** [comment]
No worries, I do not know if it has to do with CRAS, but no SOF needed...
on APL and KBL it detects audio SPEAKER, HEADPHONE and HDMI..

**Comment by MilkyDeveloper** [comment]
So does audio play on CRAS?

**Comment by EMLommers** [comment]
WIP...after some alsamixer  changes , bit audio through headphones

**Comment by MilkyDeveloper** [comment]
Is the failing to load symbols error in `dmesg`? Where does it appear? Is it while building (it should be fine if it's while building the kernel).

**Comment by EMLommers** [comment]
recompiled kernel with new .config and all ok!
