### ISSUE TITLE
Install Process

### ISSUE THREAD

**Issue by Metal-Toilet** [cb-linux/breath#157]
Hey! Sorry to make an issue twice in a day but I have another question. 

On the website it says "Currently, this project can only work on a full install of Debian or Ubuntu (not Crouton or Crostini). Running this on Arch or Fedora is unsupported."

Does this mean that to use we have to install Debian or Ubuntu through mrchromebox and then run breath?

Thanks!

**Comment by MilkyDeveloper** [comment]
Yes, you could use it through MrChromebox or through a standard Linux PC.

**Comment by Metal-Toilet** [comment]
Okay but on a chromebook you have to use chromebox but then breath removes chromebox and adds breath correct?

**Comment by timmypidashev** [comment]
@Metal-Toilet Once you have breath preloaded onto a usb, the installation process is as simple as running `install-to-internal-storage` once booted via said usb. This will wipe the internal emmc storage on your device(Make sure to read documentation on how to boot from external media!), but you will have to press CTRL-D at boot to load in to your breath install(If you have any questions on how to get rid of this step, I suggest you take a look at [fuselage](https://github.com/MilkyDeveloper/fuselage) for an idea of what needs to be done.) Also it is worth noting that arch and fedora is supported from commit 56b6a5e onwards. Hope this helps!

**Comment by Metal-Toilet** [comment]
Okay great thanks!
Sorry to bother you both.

**Comment by avram-meir** [comment]
@Metal-Toilet For what it's worth, I was able to create the breath usb using a [crouton](https://github.com/dnschneid/crouton) chroot. YMMV, but I'd definitely give that a shot before flashing MrChromebox firmware and then having to go back to stock ChromeOS firmware before then booting breath.
