### ISSUE TITLE
Branch alt-chromeos-5.10 not available

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#159]
HI,
Where can I find this branch? Or the commit to have audio without sof? Kernel  5.10.???
I guarantee  you have a copy/clone of it. Can you upload somewhere? Yousendit, Mega, etc..
Thanks. 
Or if you have a patch??

**Comment by MilkyDeveloper** [comment]
`alt-chromeos-5.10` is not a branch, it's a revision that I've tested to work on my KBL/SKL device. While refactoring, it seems like I forgot that it isn't a branch. In [line 42](https://github.com/cb-linux/kernel/blob/94350abb8e61779ff41e9e720df903a1d24efa0d/build.sh#L42), replace `$KERNEL_VERSION` with `chromeos-5.10`. I'll be pushing a fix in a few days, since I'm already working on a _huge_ refactor.

**Comment by EMLommers** [comment]
I already tried .... it is downloading about 3 GB and line 43 gives error..

**Comment by MilkyDeveloper** [comment]
The new refactor is using Powershell on Linux :D. On KBL/SKL, SOF is incompatible. `dfw_sst.bin` works by just copying it from the ChromeOS rootfs. `setup-audio` does this automatically, as mentioned in the docs.

**Comment by EMLommers** [comment]
the  line...
git checkout $(git rev-list..... chromeos-5.10)
fatal: not a git repository (or any parent up to mount point  /media/username)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM  not set).
fatal: not a git repository (or any parent up to mount point  /media/username)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM  not set).

**Comment by MilkyDeveloper** [comment]
Add `; cd alt-chromeos-5.10` after Line 43.

**Comment by EMLommers** [comment]
you mean chrome-5.10,  al-chrome does not  exist ... as using chromeos-5.10 also for line 42.

**Comment by EMLommers** [comment]
I like to work on the kernel without sof for  audio. KBL/APL/SKL
I have the firmware files, cannot retrieve or rebuild the  kernel.
which one can I use?

**Comment by EMLommers** [comment]
Which kernel to use  the nonsof kernel... can't get it working... sound
Constantly the error : set reset state failed.: core mask 1
DSP Core power up failed. I can get it working throug SOF, but i that is not my problem.
currently detects nops..

**Comment by MilkyDeveloper** [comment]
First: are you talking about KBL or APL audio? The detached head state is not an error. You can use the 4.14 or 4.19 branches, but you may need to use an older revision (e.g. from October). I have not tested any of these configurations. Without SOF, pulseaudio can fry your speakers, like they did to you. The only option to not use SOF is on SKL/KBL, where it is not available. On APL, where it does exist, I am not supporting or helping you without SOF. This is uncharted territory. I have tried to support this in #6, but then SOF got supported and I used it. You, and you alone, will need to put in the hours of experimenting needed to replicate the ChromeOS config without SOF. I will be closing this issue if you are asking me about SOF. SOF is great, and being skeptical about it’s firmware blobs is vapid.

**Comment by EMLommers** [comment]
KBL is the issue... without sof
How can I get the alt-chromeos-5.10 that's all

**Comment by MilkyDeveloper** [comment]
You already got it???? The detached head state indicates that it worked.

**Comment by EMLommers** [comment]
I just noticed the  build releases... have downloaded them for in case...
with SOF dmic16k would not be enabled and  hotwords also not possbile with SOF. Not all functions of the original will be included.
Bootlogo is working by the way 
The kernel is 5.10.54 (changed KERNEL_VERSION=chromeos-5.10 and the ../kernel-alt.conf is 5.10.70 correct???

**Comment by MilkyDeveloper** [comment]
Yes, the kernel config is 5.10.70???

**Comment by EMLommers** [comment]
can you confirm the kernel-alt.conf in the root  of breath (5.10.70) is used for kernel 5.10.54 , which is get by git.

**Comment by MilkyDeveloper** [comment]
Idk

**Comment by EMLommers** [comment]
You can close this! thanks!!
