### ISSUE TITLE
Audio for Samsung Chromebook Plus (v2)

### ISSUE THREAD

**Issue by namportuhkee** [cb-linux/breath#16]
Samsung Chromebook Plus (v2)
NAUTILUS
XE521QAB-K01US
Kaby Lake

thank you!

**Comment by runcros** [comment]
@namportuhkee can you do upload an alsa-info please.
`sudo alsa-info`

**Comment by runcros** [comment]
Closing because no answer, join our discord to make audio working (kabylake support is done).
https://discord.gg/WatsaYhXCa
