### ISSUE TITLE
Idea, optional: build kernel packages for x distribution

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#161]
Maybe it could be an idea, 
not only build bzImage.signed (kernell) for dd to partition,
also build kernel packages, (debian/ubuntu/debian derivatives at first), linux-headers, linux-image, ..modules, ..modules-extra .deb
And package for modifying audio, backlight,kbd backlight, suspend. etc.
For people who use RW Legacy or Full RW/RO firmware MrChromebox.  
It all starts with one simple step at a time....

**Comment by MilkyDeveloper** [comment]
I am tracking this at #139
