### ISSUE TITLE
Acer Chromebook Spin 713 (CP713-3W) - Overheating / no fan control

### ISSUE THREAD

**Issue by jkaplavka** [cb-linux/breath#168]
There seems to be issue with fan detection. CPU fan seems to be stuck at the lowest speed, `sensors-detect` from `lm-sensors` did not detect any fan. Here is the output from sensors during CPU stress test `stress --cpu  8 --timeout 20`, fan stayed at the lowest speed and temps got really high. I have installed Ubuntu 21.10 with Easter Release, everything else is working fine. Thanks for any help.

```
OS: Ubuntu 21.10 x86_64 
Host: Voxel rev3 
Kernel: 5.10.111 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
```

```
BAT0-acpi-0
Adapter: ACPI interface
in0:          12.69 V  
curr1:         0.00 A  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +41.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +89.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +86.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +87.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +85.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +89.0°C  (high = +100.0°C, crit = +100.0°C)
``

dmesg: https://pastebin.com/Z8q0axV0
lsmod: https://pastebin.com/aLh0NGUf

**Comment by MilkyDeveloper** [comment]
These temps are pretty high, but expected when running a stress-test. I don't think they can *damage* the CPU (gaming laptops are meant to turbo to around ~95c).

Fans are controlled by `ectool`, something I forgot to include in this. I believe you can compile it by running this on your Chromebook:
```
git clone http://review.coreboot.org/coreboot.git
cd coreboot/util/ectool
make
sudo make install
```

If running the `ectool` binary works, I'll be happy to put the compilation of the software in the Breath script.
`sudo ./ectool fanduty 100` would put your fans to 100%.

**Comment by 1Guardian** [comment]
I have the spin 713-2w and I also have this issue. I compiled the ectool binary, and installed it, but fanduty is not a recognized command for it. Is there anything else that has to be done to get control of the fan speed with ectool other than just compiling it and installing it?

**Comment by MilkyDeveloper** [comment]
I've just implemented this in the latest commit :D. Running `install-ectool` should do all of this for you.
