### ISSUE TITLE
Acer Chromebook 317, numlock is defualted as off, but there is no numlock button

### ISSUE THREAD

**Issue by xSPARExSTEWx** [cb-linux/breath#169]
My Chromebook is one of the few with a numpad, but it does not have a numlock button as it is just for the numbers nothing else. When I started using breath I quickly noticed that numlock was "off". I had to install numlockx and set up the command `numblockx on` at boot.

This only works after the login screen. I use budgie which luckily has a setting to have numlock on at the login screen. 

Just want to bring this to your attention if you want to mess with this, if not feel free to just close it.

Not sure if there is a better way to do this on your end so it is just defaulted to be "on" as I would guess if any other chromebooks have a numpad it would be similar with no numlock button.

**Comment by MilkyDeveloper** [comment]
I think I can make a `udev` rule that’ll enable numlock in Chromebook keyboards with numpads.

**Comment by xSPARExSTEWx** [comment]
Awesome, just let me know if you want me to try anything.

I looked to see if any other Chromebooks have a numpad and it looks like there are 3 others and they are all like mine, without a numlock button.

**Comment by MilkyDeveloper** [comment]
I'm afraid there's no hardware-level solution to enable/disable numlock. All of this is dependent on the desktop environment, Xorg, Wayland, or having no display server.
