### ISSUE TITLE
Black Screen on GRUNT (HP Chromebook 14, several other devices)

### ISSUE THREAD

**Issue by hortigado** [cb-linux/breath#17]
It stays on the black screen when restarting, could it be that it is not compatible?

**Comment by hortigado** [comment]
internal eMMC storage is  located at /dev/mmcblk1

**Comment by MilkyDeveloper** [comment]
If it stays black, it means the GPU is not working, which I suspect. I'll try to fix this.

**Comment by MilkyDeveloper** [comment]
Should be fixed now since I modularized AMDGPU. Try running `bash updatekernel.sh` on your Linux PC (not your chromebook).

**Comment by hortigado** [comment]
Thanks, but is same in black screen for more of 20 minutes; No work in it laptop model 🥲

**Comment by KSPAtlas** [comment]
I have this issue now

**Comment by KSPAtlas** [comment]
All I have is a small gradient is the bottom right

**Comment by MilkyDeveloper** [comment]
Could you show me a picture?

**Comment by KSPAtlas** [comment]
It's a black screen with a tiny gradient of pixels from blue to yellow in the bottom right corner, separated by 1 blank pixel each

**Comment by delliot47** [comment]
Up until about a month or two ago this black screen was a problem running linux on Careena using coreboot with kernel versions above 5.2. An older kernel may work or if you can use the updated source for the amdgpu module you may be able to get it to work on these devices.

**Comment by MilkyDeveloper** [comment]
I believe GRUNT display out is working now. See #173. Just rerun all the instructions to rebuild your USB.

**Comment by KSPAtlas** [comment]
@MilkyDeveloper please reopen, it is still non functional

**Comment by KSPAtlas** [comment]
Only Debian with KDE seemed to work, anything else and I get the black screen of death

**Comment by MilkyDeveloper** [comment]
Does install `gdm3` like `sudo apt install gdm3` and setting your display manager (when prompted) to GDM3 break your system again?

**Comment by KSPAtlas** [comment]
I was able to switch it to lightdm

**Comment by MilkyDeveloper** [comment]
hello.

**Comment by KSPAtlas** [comment]
Nothing, just wondering if I can help

**Comment by KSPAtlas** [comment]
It worked with sddm
