### ISSUE TITLE
exFAT not accessible

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#171]
I have found that an exFAT USB will mount and is usable on the device when ChromeOS is running but NOT when running Breath/Ubuntu.  Ubuntu requires `exfat-utils` and `exfat-fuse` (Ubuntu 21.10) or `exfatprogs` (Ubuntu 22.04) for reading exFAT devices and those are installed.  The same bundles installed on my Ubuntu build system enable it to mount and use this same exFAT USB.  It is only under Breath/Ubuntu that it is not accessible.

When I insert the USB, it is listed in the Files app (in nautilus, left-hand pane) but attempts to access it report: "Unable to access, Error mounting: unknown filesystem type 'exFat'.  When I open "Disks", it does not see the device at all; it is not listed.

Given it works under ChromeOS and we're using the ChromeOS kernel, it seems strange that it wouldn't work under Breath/Ubuntu.  Ideas?

**Comment by hede5562** [comment]
The kernel config is different between those systems. CONFIG_EXFAT_FS is not part of the kernel config.

**Comment by MilkyDeveloper** [comment]
Yeah, I'm pretty sure I built the latest kernel with exFAT support.
