### ISSUE TITLE
Cometlake rt5682 Audio not working (Dragonair/Hatch)

### ISSUE THREAD

**Issue by tobiastnf** [cb-linux/breath#183]
I tried to use debian and ubuntu 22.04 and everything is working except the audio. I use a HP Chromebook x360 14c-ca0241ng.

**Comment by MilkyDeveloper** [comment]
Do you know what board this is? Can I have a `dmesg` and `lsmod` from ChromeOS and and Breath?

**Comment by tobiastnf** [comment]
lsmod (Ubuntu):
https://pastebin.com/0nieVpvz

dmesg (ChromeOS):
https://pastebin.com/9NJgacif

(hope I did it right haha)

**Comment by MilkyDeveloper** [comment]
I was looking for both commands from both Ubuntu and ChromeOS

**Comment by tobiastnf** [comment]
okay, just did dmesg in ubuntu and lsmod in chromeos (i did lsmod in shell due to crosh not knowing what lsmod is, sry if i sound a bit nooby with that)

lsmod (ChromeOS)
https://pastebin.com/GWU9H5it

dmesg (Ubuntu)
https://pastebin.com/2EnYs6PH

**Comment by MilkyDeveloper** [comment]
You need to add `sudo` in front of `dmesg` in Ubuntu.

**Comment by tobiastnf** [comment]
thanks for the tip. i have edited the pastebin of the dmesg in ubuntu

**Comment by MilkyDeveloper** [comment]
Hmmm... I wonder if this is due to a new kernel update.

On the PC you built Breath with, replace all occurences of `latest` in `updatekernel.sh` with `v4.2.0`.

**Comment by MilkyDeveloper** [comment]
Also, did you run `sof-setup-audio`?

**Comment by MilkyDeveloper** [comment]
I've reverted the kernel to 5.10.110. Let me know how `bash updatekernel.sh` (on the PC you built Breath with) goes.

**Comment by MilkyDeveloper** [comment]
Actually, I think running `setup-audio` first would work better.

**Comment by tobiastnf** [comment]
so i did use "setup-audio" and "sof-setup-audio" before without success. changing the script to version 4.2.0 just gave me a bunch of errors. i have redownloaded the git now and i am building a brand new image, flash it with etcher, use "bash updatekernel.sh" and then boot and use "setup-audio" and "sof-setup-audio" again. i'll tell you how it went.

**Comment by tobiastnf** [comment]
so I just tried everything again and still no luck. I did however notice an error while running "setup-audio", that i noticed before, but I thought were irrelevant to me since I think that I should be using "sof-setup-audio" or "SOUNDCARD=rtk sof-setup-audio"

Here is my terminal output from running "setup-audio":
https://pastebin.com/795YQ9Ku

also, since your update, new errors show up when I run both "sof-setup-audio" and "SOUNDCARD=rtk sof-setup-audio", that weren't there before

here is the terminal output of me running "sof-setup-audio":
https://pastebin.com/5rtkT5xW

and here is the terminal output of me running "SOUNDCARD=rtk sof-setup-audio":
https://pastebin.com/EjGjRA9n

**Comment by MilkyDeveloper** [comment]
Should be fixed now. Download the latest file in `bin/sof-setup-audio` to your Chromebook, make it executable (`chmod +x`), and then run it alone.

**Comment by tobiastnf** [comment]
It didn't give me an error this time. Still no sound. Here is the "dmesg":
https://pastebin.com/m38Sg0QM

**Comment by MilkyDeveloper** [comment]
Looks fine to me. What about `sudo alsa-info` (give the output of the file/URL created).

**Comment by tobiastnf** [comment]
sure. there is the link:
http://alsa-project.org/db/?f=6e65dadd44946a6ed3ec1b860602d74f1bc5d94d

**Comment by MilkyDeveloper** [comment]
We're getting this again:
```
[   12.191674] Bluetooth: hci0: Found device firmware: intel/ibt-19-0-4.sfi
[   13.636060] pci 0000:00:1f.3: attach allowed to drvr sof-audio-pci-intel-cnl [internal device]
[   13.636082] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   13.636197] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[   13.636271] sof-audio-pci-intel-cnl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[   13.642670] sof-audio-pci-intel-cnl 0000:00:1f.3: use msi interrupt mode
[   13.651957] sof-audio-pci-intel-cnl 0000:00:1f.3: codec #2 probe error, ret: -2
[   13.652072] sof-audio-pci-intel-cnl 0000:00:1f.3: no hda codecs found!
[   13.806461] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware info: version 2:0:0-b678a
[   13.806481] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[   13.806482] sof-audio-pci-intel-cnl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[   13.806487] sof-audio-pci-intel-cnl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[   13.821033] Bluetooth: hci0: Waiting for firmware download to complete
```

Whereas what should happen is:
```
[    5.684713] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.684916] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[    5.693578] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffff98aa41f0)
[    5.702327] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
```

**Comment by MilkyDeveloper** [comment]
I think there's a change your running the (borked) kernel I published. You could run `bash updatekernel.sh` on the PC you built Breath with and post a new `alsa-info`.

**Comment by tobiastnf** [comment]
I just did that. I am pretty sure I did that before too with the `bash updatekernel.sh` but I redid everything from scratch including running `bash updatekernel.sh`.
I looked into the ALSA Information Script myself and the lines you mentioned didn't change after doing it again. Here is the Link:
http://alsa-project.org/db/?f=7f47d6569c0cc2312b3282ee4cbceb5d8f7f85b4

**Comment by MilkyDeveloper** [comment]
Create a new file named `alsa-hatch.conf` in `/etc/modprobe.d/` containing:
```
blacklist snd_hda_intel
blacklist snd_soc_skl
```

Reboot and give me another alsa info log.

**Comment by tobiastnf** [comment]
http://alsa-project.org/db/?f=a7f13aa39fc1e3cc5e65b6349e8dcc02031c5219

**Comment by MilkyDeveloper** [comment]
Run this:
```
cd # to home directory
git clone --depth 1 "https://github.com/thesofproject/sof-bin"
cd sof-bin/v2.1.x
sudo rsync -a sof*v2.1.1   /lib/firmware/intel/
sudo ln -s sof-v2.1.1      /lib/firmware/intel/sof
sudo ln -s sof-tplg-v2.1.1 /lib/firmware/intel/sof-tplg
sudo rsync tools-v2.1.1/*  /usr/local/bin
```

Reboot and do the alsa info stuff.

**Comment by tobiastnf** [comment]
http://alsa-project.org/db/?f=c4f4a552c8b492e24d40dc939cd8713f8d125b88

I got some errors while running `sudo ln -s sof-v2.1.1      /lib/firmware/intel/sof` and `sudo ln -s sof-tplg-v2.1.1 /lib/firmware/intel/sof-tplg`. The errors are in the txt file.
[errors.txt](https://github.com/cb-linux/breath/files/8647429/errors.txt)
.

**Comment by MilkyDeveloper** [comment]
Can you confirm that `/lib/firmware/intel/sof/community/sof-cml.ri` exists?

**Comment by tobiastnf** [comment]
no, but `/lib/firmware/intel/sof/sof-cml.ri` exists. a directory named `community` doesn't exist

**Comment by MilkyDeveloper** [comment]
Try making the community folder and copying `sof-cml.ri` there.

**Comment by tobiastnf** [comment]
did just that, still getting the same errors.

**Comment by tobiastnf** [comment]
sorry for getting back that late. i have no more errors, but still no sound. shall i do a new image and run `bash updatekernel.sh` and `sof-setup-audio` again? and one more question, is the image influenced by which distro i build it with? because i used kde neon for that, since it never had errors.

**Comment by MilkyDeveloper** [comment]
No, what distro you build it with has no influence. Could you give me an `alsa-info`?

**Comment by tobiastnf** [comment]
this is the alsa-info right now:
http://alsa-project.org/db/?f=affb21a9984cbaad167348fea81515ee5b1a5ef2

i'll now do a full reflash of my sd card to see if sound works now.

**Comment by tobiastnf** [comment]
i did just do the reflash, still no sound after running `sof-setup-audio` here is the `alsa-info`
http://alsa-project.org/db/?f=6b067e6ab6b111b53c689a78fb87cfaec63a69f3

**Comment by MilkyDeveloper** [comment]
The reflash you did removed `/etc/modprobe.d/alsa-hatch.conf`. Go back to that comment and redo it (this is already done on the latest commit, but you probably didn’t pull the latest update).

Once you do that, audio should be working. The alsa log you gave me before you reflashed indicates that audio was working. Use `speaker-test` to test audio and make sure your volume is up, either through a GUI, or, just to be sure, `alsamixer`.

**Comment by MilkyDeveloper** [comment]
Also, you're invited to the Microphone and Headphone Jack testing thread on #190, if you don't mind :D.

**Comment by tobiastnf** [comment]
yes, i just read the log again and yes the audio was working haha. i did pull the latest update before the reflash, but maybe running `bash updatekernel.sh` broke it but even if so, it's easily fixable. thank you very much for helping me. and yes, i'll gladly help you test the microphone and headphone jack, but i'll do that tomorrow (it's almost 11pm where i live haha)

**Comment by tobiastnf** [comment]
erm...so i did just redo the `alsa-hatch.conf` file and the device is showing up...but still no sound. tried playing a video, no sound. also no sound in ubuntus internal sound test. did i do something wrong?

**Comment by MilkyDeveloper** [comment]
What does `sof-setup-aux` do? Give me an `alsa-info` log too.

**Comment by MilkyDeveloper** [comment]
Idk how to fix this lol

maybe remove pulseaudio? 🤷‍♂️
