### ISSUE TITLE
Crostini Support

### ISSUE THREAD

**Issue by splch** [cb-linux/breath#186]
I'm trying to build breath.iso using a Samsung Galaxy Chromebook 2 with crostini. I'm running `FEATURES=ISO,KEYMAP bash setup.sh kde ubuntu jammy-22.04`. I'm not sure if this is possible, but I'm getting a couple errors.

1. The first was no `parted` being installed. It was fine after installing
2. The second is with losetop:
```bash
losetup: cannot find an unused loop device
```
3. The third seems to be a stat error:
```bash
Error: Could not stat device mklabel - No such file or directory.
```

The second error doesn't cause the program to stop, so I assume that's fine. But the third does.

**Comment by MilkyDeveloper** [comment]
I think this is an error on your side. If `modprobe loop` doesn't work, I'll reopen this.

**Comment by splch** [comment]
It seems that `modprobe` isn't a command in ChromeOS. Is there another way to do this?

```shell
$ modprobe loop

-bash: modprobe: command not found
```

**Comment by MilkyDeveloper** [comment]
Oh right, you’re using Crostini. This project is meant to be run on a full Linux computer, as stated in the docs.

However, you could run this on Crostini. Follow the instructions [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1303315#c3) first and add `,CROSTINI` to the FEATURES variable.

**Comment by splch** [comment]
That worked! Thanks so much :) I'll add a couple notes as well in case others need to build from a chromebook.

1) Running the container with privileges might take a couple tries (enabling and disabling as well as rebooting). There seems to be some memory allocation bug so it worked eventually but not consistently.

2) Renaming `breath.img` to `breath.bin` will let you use the Chrome Recovery Tool to write it.

3) If you write the OS to a microsd card, you may need to use an adapter to use the USB port instead of the microsd card port. My Chromebook wouldn't boot from that port.

**Comment by MilkyDeveloper** [comment]
I'm going to close this since I've recently added this to the docs. Thanks for your input :D.

**Comment by MaluNoPeleke** [comment]
> That worked! Thanks so much :) I'll add a couple notes as well in case others need to build from a chromebook.
> 
> 1. Running the container with privileges might take a couple tries (enabling and disabling as well as rebooting). There seems to be some memory allocation bug so it worked eventually but not consistently.
> 2. Renaming `breath.img` to `breath.bin` will let you use the Chrome Recovery Tool to write it.
> 3. If you write the OS to a microsd card, you may need to use an adapter to use the USB port instead of the microsd card port. My Chromebook wouldn't boot from that port.

I cannot make it work as of this error:
![image](https://user-images.githubusercontent.com/1446541/186128540-f9b37034-171f-4488-9cc1-15339b290815.png)
Can you please further explain what you did exactly?
