### ISSUE TITLE
Acer chromebook 311 (cb311-9h) booting into black screen

### ISSUE THREAD

**Issue by br4zyy** [cb-linux/breath#192]
i booted my chromebook from the usb but it went to a black screen that says:
Debian GNU/Linux bookworm/sid debian tty1

debian login:
when i login it shows some linux info an some copyright info and then it brings me to a command line

**Comment by MilkyDeveloper** [comment]
That's because you didn't install a desktop, as stated in the instructions. Just google how to install GNOME or any other DE on Ubuntu.
