### ISSUE TITLE
Sound on Lenovo IdeaPad Flex 3

### ISSUE THREAD

**Issue by hede5562** [cb-linux/breath#196]
- Lenovo Ideapad Flex i3
- ChromeOS dedede platform
- botenflex board

alsa-info see: http://alsa-project.org/db/?f=2e3ce45b27975d18123eaa5d34fc905a9a0579c9

The sound is generally working after fiddling with some alsamixer controls. The internal speaker works. If manually fiddling with the alsa mixer and manually changing the output device even headphone output is possible. 

But there is no headphone plug detection and the internal microphone works as 4-channel-input with the 2 front mics connected to the first two channels and white noise on channel 3+4. 

I would like to have the jack detection working and to have the microphone as a stereo microphone and not a 4-channel-microphone with 2 noisy channels.

Has anyone here experience in modifying ChromeOS alsa-ucm-files? It seems some of the parameters which ChromeOS CRAS sound server can use are useless for standard alsa+pulseaudio. 

Like for example: 
- CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
... for only using 2 of the 4 microphone channels

or 
- JackDev "sof-rt5682 Headset Jack"
- JackSwitch "6"
... for automatic switching to the headset if plugged in. 

The ChromeOS alsa-ucf file is there:
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/master/overlay-dedede/chromeos-base/chromeos-bsp-dedede/files/common/audio/ucm-config/sof-rt5682.rt1015.1mic/HiFi.conf

Does anyone know if alsa-ucm is sufficient to solve these problems? Or is some driver modification or even firmware modification needed? (for example sof topology - at least for the 4-channel-microphone it seems a topology-change will do the trick but this means to compile and sign new firmware!?)

**Comment by MilkyDeveloper** [comment]
Eventually will be closed with the introduction of #223
