### ISSUE TITLE
Problems with trying to setup Crostini to build Breath

### ISSUE THREAD

**Issue by CorruptedPlazma** [cb-linux/breath#198]
Following the instructions for setting up Crostini to do this via the instructions [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1303315#c3) returns a few errors.

The first 3 steps gives me this:
```
crosh> vmc stop termina
crosh> vmc start termina
(termina) chronos@localhost ~ $ vmc container termina penguin --privileged true
-bash: vmc: command not found
(termina) chronos@localhost ~ $ 
```

Exiting that takes be back to crosh, where I tried:
```
crosh> vmc stop termina
crosh> vmc start termina && vmc container termina penguin --privileged true
Error: UnrecognizedOption("privileged")
[ERROR:src/main.rs:183] ERROR: command failed
crosh> 
```

I've been trying several other variations of performing the instructions to no avail. I feel the solution is likely super simple, and I simply lack enough knowledge of Crostini. I would greatly appreciate any guidance, thanks!

**Comment by Denisuu** [comment]
I think you have to run: `vmc container termina penguin --privileged true` from Crosh? Neither work for me either though on ChromeOS 101. 

When I try to run `bash setup.sh cli arch` I receive:
```
utils/bootstrap.sh: line 9: There are files in /mnt! Please clear this directory of any valuable information!: 
No such file or directory
```

When I try to run [these ](https://bugs.chromium.org/p/chromium/issues/detail?id=1303315#c3)commands as described in the guide I receive the following errors: 


From Crosh:
```
crosh> vmc container termina penguin --privileged true

Error: operation `container_start` failed: failed to start container: `FAILED`: failed to update privilege level: Invalid config: LXD was configured to only allow unprivileged containers
[ERROR:src/main.rs:183] ERROR: command failed
```
From Termina:
```
(termina) chronos@localhost ~ $ vmc container termina penguin --privileged true
-bash: vmc: command not found
```

**Comment by CorruptedPlazma** [comment]
I remember running those as well early on in troubleshooting the problem, and got the same results. This may be some change in ChromeOS itself, removing the ability to make containers privileged? That would be my guess from `LXD was configured to only allow unprivileged containers`

**Comment by MilkyDeveloper** [comment]
A comment from the thread (linked above) that I started:
```
It is actually possible if your host device has a newer kernel, although we haven't documented it yet.  what does `uname -a` show in crosh (*not* inside the VM) ?
```

Could you give me the output of `uname -a` from `crosh`? I'm guessing that priveledged containers are only allowed on certain, newer (maybe 5.4+) kernel versions.

**Comment by CorruptedPlazma** [comment]
`uname -a` returns `Linux localhost 4.14.272-18805-g12d6850827f5 #1 SMP PREEMPT Wed May 4 19:55:34 PDT 2022 x86_64 Intel(R) Celeron(R) N4020 CPU @ 1.10GHz GenuineIntel GNU/Linux`.

That explains why it's not working, I'm on a fairly outdated kernel. I suppose I'll need to find another way to setup Breath then?

**Comment by MilkyDeveloper** [comment]
I guess you could use Crouton or another computer with a bootable USB of Ubuntu. ChromeOS is really frustrating for those of us who like to tinker with the OS - they still haven't gave raw USB access.

**Comment by CorruptedPlazma** [comment]
Alright, thanks for the help, I think I can setup a crouton environment, not like ChromeOS will see much use after I get this going.
