### ISSUE TITLE
No Audio - HP Chromebook 14 x360 (Nami)

### ISSUE THREAD

**Issue by aBabyPenguin** [cb-linux/breath#205]
Hi,

I've followed the instructions for Kabylake below and still have no audio on my HP Chromebook 14 ( Model # 14-da0011dx ). I've attached dmesg output and also-info. Let me know if I messed up somehow or if there's anything I can do to help. Thanks!

```
Connect to Wifi on your Chromebook! You can use a GUI for this or nmcli/nmtui

    Skylake, Kabylake, or Coffeelake (7th/8th Gen Intel CPU):
        VERSION=ALT bash updatekernel.sh on the PC you built Breath with (cannot be run from Crostini)
        setup-audio on your Chromebook that has booted Breath
```

[dmesgOutput.txt](https://github.com/cb-linux/breath/files/8751205/dmesgOutput.txt)
[alsa-info.txt](https://github.com/cb-linux/breath/files/8751206/alsa-info.txt)

**Comment by MilkyDeveloper** [comment]
Try adding:
```
blacklist snd_hda_intel
```

to /etc/modprobe.d/alsa-nami.conf.

**Comment by ArtemPozharov** [comment]
The same problem. It needs to be fixed!

**Comment by ArtemPozharov** [comment]
Did you notice that snap apps don't work?

**Comment by aBabyPenguin** [comment]
> Try adding:
> 
> ```
> blacklist snd_hda_intel
> ```
> 
> to /etc/modprobe.d/alsa-nami.conf

Not sure if I'm doing something wrong here. I can't seem to find alsa-nami.conf. I went ahead and reflashed and followed the instructions again. Here's my process.

1. Flash image to SD card
2. Put in SD card and booted once to test everything is working
3. Put SD card back into machine that flashed it. Run updatekernel.sh
4. Boot SD card again, connect to wifi
5. sudo apt update
6. setup-audio
7. Reboot and still no audio devices

Attached is the output from setup-audio. Also attached is output from "ls /etc/modprobe.d/" Since I checked to see if an alsa-nami.conf file ever appeared at many points in the process and I couldn't find it. Let me know if I can do more! 

[setup-audio_output.txt](https://github.com/cb-linux/breath/files/8768159/setup-audio_output.txt)
[no-alsa-nami.txt](https://github.com/cb-linux/breath/files/8768160/no-alsa-nami.txt)

**Comment by aBabyPenguin** [comment]
Hm, I've created the file and rebooted but still have no audio!

![Screenshot from 2022-05-26 00-01-33](https://user-images.githubusercontent.com/19317534/170388501-98c5ba8a-52d5-4f3e-bc74-4e0c89c86b07.png)

**Comment by MilkyDeveloper** [comment]
What’s the output of `dmesg`?

**Comment by aBabyPenguin** [comment]
Here ya go!

[dmesg_output.txt](https://github.com/cb-linux/breath/files/8776366/dmesg_output.txt)

**Comment by MilkyDeveloper** [comment]
I think this is a problem:
> Those UCM files already exist in /usr/share/alsa/ucm2/kblda7219max/kblda7219max.nami/

This could be because ChromeOS has changed their UCM directory layout. 

Give me the output of `find /usr/share/alsa/ucm*` from ChromeOS. Sorry for the late reply :D.

**Comment by aBabyPenguin** [comment]
No worries on the late reply, hopefully we're close to cracking this! Here's the list.

[findUCM.txt](https://github.com/cb-linux/breath/files/8793681/findUCM.txt)

**Comment by MilkyDeveloper** [comment]
Sorry, could I have the output of the `find` command from ChromeOS?

**Comment by aBabyPenguin** [comment]
Ah! Here's the output from ChromeOS.

[ChromeOSfindUCM.txt](https://github.com/cb-linux/breath/files/8793774/ChromeOSfindUCM.txt)

**Comment by MilkyDeveloper** [comment]
You're on Debian Unstable, which has a newer UCM directory layout.

Try doing:
```
sudo rm -rf /usr/share/alsa/ucm2/kblda7219max/kblda7219max.nami /usr/share/alsa/ucm2/kblda7219max/kblda7219max.nami/kblda7219max.nami.conf /usr/share/alsa/ucm2/kblda7219max/kblda7219max.nami/HiFi.conf
```

and then:
sudo mv /usr/share/alsa/ucm2/kblda7219max /usr/share/alsa/ucm2/conf.d/kblda7219max
```

```

**Comment by aBabyPenguin** [comment]
Ran both commands then rebooted and still no output devices found :( Here's another dmesg if that gives you any info! 

![Screenshot from 2022-05-30 00-10-11](https://user-images.githubusercontent.com/19317534/170897114-300d9378-3adc-40ce-ab69-e1ff18eb889f.png)
[dmesg5-30.txt](https://github.com/cb-linux/breath/files/8794569/dmesg5-30.txt)

**Comment by MilkyDeveloper** [comment]
Ubuntu will show no output devices found, but playing audio should work from any app. Try `speaker-test` from the command-line or launching Firefox.

**Comment by aBabyPenguin** [comment]
> Ubuntu will show no output devices found, but playing audio should work from any app. Try `speaker-test` from the command-line or launching Firefox.

Still not hearing sound from speaker-test or Firefox 😭️ Is the output below normal?

`$ speaker-test

speaker-test 1.2.6

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
ALSA lib pcm_direct.c:1284:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1044:(snd_pcm_dmix_open) unable to initialize slave
Playback open error: -22,Invalid argument
`

**Comment by MilkyDeveloper** [comment]
I think this means the UCM isn’t loaded. 

```

alsaucm -c kblda7219max set _verb HiFi set _enadev Speaker'
```

**Comment by MilkyDeveloper** [comment]
I think you forgot to run:
```
VERSION=ALT bash updatekernel.sh
```

on the PC you built Breath. This was instructed in the docs for `Nami` devices :D.

**Comment by ArtemPozharov** [comment]
Sound on Nami doesn't work if you perform all actions.

пн, 30 мая 2022 г., 18:18 MilkyDeveloper ***@***.***>:

**Comment by MilkyDeveloper** [comment]
@ArtemPozharov `dmesg`

**Comment by MilkyDeveloper** [comment]
By the way, if any of you find this useful, feel free to [donate](https://opencollective.com/breath) ❤️

**Comment by aBabyPenguin** [comment]
> I think you forgot to run:
> 
> ```
> VERSION=ALT bash updatekernel.sh
> ```
> 
> on the PC you built Breath. This was instructed in the docs for `Nami` devices :D.

I did! My earlier comment mentions my steps, that would have been step 3. Although I could have done something wrong. I just tried running updatekernel.sh again just now but there's still no audio. I'm going to reflash the image onto a usb drive instead of the SD card I've been using and try to run through all the steps again.

> 
> Not sure if I'm doing something wrong here. I can't seem to find alsa-nami.conf. I went ahead and reflashed and followed the instructions again. Here's my process.
> 
>     1. Flash image to SD card
> 
>     2. Put in SD card and booted once to test everything is working
> 
>     3. Put SD card back into machine that flashed it. Run updatekernel.sh
> 
>     4. Boot SD card again, connect to wifi
> 
>     5. sudo apt update
> 
>     6. setup-audio
> 
>     7. Reboot and still no audio devices
> 
> 
> Attached is the output from setup-audio. Also attached is output from "ls /etc/modprobe.d/" Since I checked to see if an alsa-nami.conf file ever appeared at many points in the process and I couldn't find it. Let me know if I can do more!
> 
> [setup-audio_output.txt](https://github.com/cb-linux/breath/files/8768159/setup-audio_output.txt) [no-alsa-nami.txt](https://github.com/cb-linux/breath/files/8768160/no-alsa-nami.txt)

**Comment by aBabyPenguin** [comment]
> By the way, if any of you find this useful, feel free to [donate](https://opencollective.com/breath) heart

Will absolutely buy you lunch if we can get my speakers working :)

**Comment by MilkyDeveloper** [comment]
Huh, the `dmesg` shows you're on 5.10.11* whereas you should be on 5.10.70 after `bash updatekernel.sh`. I think a reflash would be the correct way to go. Audio will work then ;)

**Comment by aBabyPenguin** [comment]
Good to know! Something must be going wrong on my end then. I'll investigate and get back to you!

**Comment by aBabyPenguin** [comment]
I've tried the updatekernel script on the newly flashed USB drive and I'm still not updated to 5.10.70 😖 Here's the output from `VERSION=ALT bash updatekernel.sh ` Any ideas? I did notice `cp: cannot create symbolic link '/mnt/lib/modules/5.10.70/build': Operation not permitted` and `cp: cannot create symbolic link '/mnt/lib/modules/5.10.70/source': Operation not permitted`

[updateKernel_output.txt](https://github.com/cb-linux/breath/files/8800698/updateKernel_output.txt)

**Comment by MilkyDeveloper** [comment]
`rm -rf /mnt/*` and use `/dev/sdb` instead of `sdb` (as shown in the example)

**Comment by MilkyDeveloper** [comment]
Well, this should fix it, but I haven't implemented the copy to `conf.d` yet, so I'm going to leave this open until then.

**Comment by MilkyDeveloper** [comment]
This will be ran by default on all future builds. Let me know if audio works now @aBabyPenguin :D, you don't need to rebuild, just [do this](https://github.com/cb-linux/breath/issues/205#issuecomment-1141483080).

**Comment by MilkyDeveloper** [comment]
```
sudo umount /mnt
```
and rerun the script.

**Comment by ArtemPozharov** [comment]
> ```
> sudo umount /mnt
> ```
> and rerun the script.

I've already tried. Didn't help.

**Comment by MilkyDeveloper** [comment]
Reboot or something, idk. This is out of my script's control, `umount` not working is a seperate problem which I don't know how to fix.

**Comment by ArtemPozharov** [comment]
![IMG_20220611_200648.jpg](https://user-images.githubusercontent.com/50730813/173199778-1204be24-3605-4d8e-ba8f-d2b7630ab950.jpg)

**Comment by ArtemPozharov** [comment]
Should speaker-test give me some sound?

**Comment by MilkyDeveloper** [comment]
`ls /usr/share/alsa/`

**Comment by ArtemPozharov** [comment]
сб, 11 июн. 2022 г., 23:40 MilkyDeveloper ***@***.***>:

**Comment by MilkyDeveloper** [comment]
`sudo apt install alsa-*`

Is there anything in the alsa folder now?

**Comment by ArtemPozharov** [comment]
![IMG_20220612_184121.jpg](https://user-images.githubusercontent.com/50730813/173243706-3bab940a-6d01-4729-810a-5bfad838abb3.jpg)

**Comment by ArtemPozharov** [comment]
![IMG_20220612_184322.jpg](https://user-images.githubusercontent.com/50730813/173243761-e36fb1e4-a4fa-405a-8cbe-0dfa7dc41acc.jpg)
I reran the script, rebooted and then executed speaker-test. You can see an error here.

**Comment by ArtemPozharov** [comment]
![IMG_20220612_201742.jpg](https://user-images.githubusercontent.com/50730813/173247503-3b6eb9c0-a144-4e54-ad22-ff6a234e9035.jpg)
The end part of dmesg

**Comment by MilkyDeveloper** [comment]
`uname -r` is 5.10.70, right? I’ll look into this, maybe KDS is producing builds different from my manual 5.10.70 builds.

**Comment by ArtemPozharov** [comment]
> `uname -r` is 5.10.70, right? I’ll look into this, maybe KDS is producing builds different from my manual 5.10.70 builds.

Unfortunately, 5.106 kernel.

**Comment by MilkyDeveloper** [comment]
That’s a problem. Run the update kernel step as described in the instructions again and tell me the command’s output.

**Comment by MilkyDeveloper** [comment]
No, tell me the text that the command outputs.

**Comment by MilkyDeveloper** [comment]
Sorry, what text does the updatekernel command show? This isn’t anything from your Chromebook, update kernel is ran on your USB.

**Comment by ArtemPozharov** [comment]
[output.txt](https://github.com/cb-linux/breath/files/8893900/output.txt)

**Comment by ArtemPozharov** [comment]
Today I've remade all operations from scry, but sound is still absent.
