### ISSUE TITLE
Can't build Arch ISO

### ISSUE THREAD

**Issue by Denisuu** [cb-linux/breath#206]
Hi all,

When I try to make an Arch ISO with `$ FEATURES=ISO,KEYMAP bash setup.sh cli arch` 
It almost immediately stops when trying to write to an ISO or a USB.

```Writing storage, may take more than 5 minutes.
Although it seems slow, consider this process like flashing an ISO to a USB Drive.
Below is an innacurate indicator of mB left to write. It may decrease hundreds of megabytes in seconds.
490.65MB

cp: cannot stat '/mnt/usr/share/X11/xkb/symbols/pc': No such file or directory
[denisuu@N580GD breath]$ 
```

I tried building it from Ubuntu & Manjaro, tried on my laptop from Breath and from a VM on my main Windows machine. 
Always the same result.

**Comment by CorruptedPlazma** [comment]
#200

**Comment by Denisuu** [comment]
Oops my bad, I'll close this one.
