### ISSUE TITLE
The device disconnects after sleeping

### ISSUE THREAD

**Issue by QL100100** [cb-linux/breath#21]
Sorry for bothering you again.
When I first tried Breath, I was surprised that suspending actually works!
However, when I reopened the lid, I found the network disconnected and couldn't get it to reconnect until I rebooted.
Thanks

**Comment by MilkyDeveloper** [comment]
What is your Wifi card?

**Comment by QL100100** [comment]
Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                 94208  0
stp                    16384  1 bridge
llc                    16384  2 stp,bridge
tun                    28672  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   16384  0
ah6                    16384  0
ip6t_REJECT            16384  2
nf_reject_ipv6         16384  1 ip6t_REJECT
ip6t_ipv6header        16384  0
ccm                    20480  1
vhost_vsock            20480  5
vmw_vsock_virtio_transport_common    20480  1 vhost_vsock
vsock                  32768  7 vmw_vsock_virtio_transport_common,vhost_vsock
vhost                  24576  1 vhost_vsock
veth                   16384  0
rfcomm                 40960  2
cmac                   16384  2
algif_hash             16384  1
algif_skcipher         20480  1
af_alg                 16384  6 algif_hash,algif_skcipher
xt_cgroup              16384  2
uinput                 20480  0
ipt_MASQUERADE         16384  1
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xt_mark                16384  96
iio_trig_hrtimer       16384  2
industrialio_sw_trigger    16384  1 iio_trig_hrtimer
industrialio_configfs    16384  2 industrialio_sw_trigger
snd_soc_sst_bxt_da7219_max98357a    24576  4
snd_soc_hdac_hdmi      24576  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  1
snd_soc_skl_ssp_clk    16384  0
acpi_als               16384  1
snd_soc_max98357a      16384  1
snd_soc_da7219         53248  2 snd_soc_sst_bxt_da7219_max98357a
snd_soc_skl            65536  3 snd_soc_skl_ssp_clk
snd_soc_skl_ipc        36864  1 snd_soc_skl
snd_soc_sst_dsp        32768  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_sst_match      16384  1 snd_soc_skl
snd_hda_ext_core       20480  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_hda_core           53248  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                   90112  20
ip6table_filter        16384  2
iio_trig_sysfs         16384  0
cros_ec_sensors        16384  2
cros_ec_sensors_core    16384  1 cros_ec_sensors
industrialio_triggered_buffer    16384  2 cros_ec_sensors_core,acpi_als
kfifo_buf              16384  2 industrialio_triggered_buffer,cros_ec_sensors_core
industrialio           49152  9 iio_trig_hrtimer,industrialio_triggered_buffer,iio_trig_sysfs,cros_ec_sensors_core,acpi_als,kfifo_buf,cros_ec_sensors
cros_ec_sensorhub      20480  1 cros_ec_sensors_core
iwlmvm                409600  0
iwlwifi               344064  1 iwlmvm
iwl7000_mac80211      655360  2 iwlwifi,iwlmvm
zram                   24576  1
cfg80211              479232  3 iwlwifi,iwlmvm,iwl7000_mac80211
btusb                  40960  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             413696  32 btbcm,btrtl,btusb,rfcomm,btintel
uvcvideo               81920  0
videobuf2_vmalloc      16384  1 uvcvideo
videobuf2_v4l2         24576  1 uvcvideo
videobuf2_core         28672  2 uvcvideo,videobuf2_v4l2
videobuf2_memops       16384  1 videobuf2_vmalloc
joydev                 20480  0

**Comment by MilkyDeveloper** [comment]
Could you get Wifi disconnected by suspending and then attach the output of the command `dmesg` right after?

**Comment by QL100100** [comment]
[dmesg2.txt](https://github.com/MilkyDeveloper/cb-linux/files/7797720/dmesg2.txt)

**Comment by MilkyDeveloper** [comment]
Try running `git fetch; git pull` on your Linux PC (not chromebook). Then run: `VERSION=5.4 bash updatekernel.sh`.

**Comment by QL100100** [comment]
I re-cloned the repository, and run the update kernel command.
But now, not only does my chromebook disconnect after sleeping, but my touchpad stops working!

**Comment by vilasrk** [comment]
@QL100100 
What is the scenario of this issue?
