### ISSUE TITLE
SOF Audio not working from Ubuntu

### ISSUE THREAD

**Issue by stormchaser56** [cb-linux/breath#211]
Running Debian Sid 11.3.0, sof-setup-audio and SOUNDCARD=rtk sof-setup-audio both tried on separate reboots to no apparent effect.
Only the 'dummy output' audio device is visible.

Worth noting that it appears to work on Ubuntu, just not Debian for whatever reason.

dmesg | grep sof output
> [    0.645514] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.645516] software IO TLB: mapped [mem 0x00000000759f3000-0x00000000799f3000] (64MB)
[    6.613912] pci 0000:00:0e.0: attach allowed to drvr sof-audio-pci-intel-apl [internal device]
[    6.614091] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    6.614942] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    6.616639] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[    6.623269] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    6.638650] sof-audio-pci-intel-apl 0000:00:0e.0: codec #2 probe error, ret: -2
[    6.638805] sof-audio-pci-intel-apl 0000:00:0e.0: no hda codecs found!
[    6.682399] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:1:1-3964a
[    6.682403] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:21:0 Kernel ABI 3:18:0
[    6.682405] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    6.682425] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    6.810000] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:1:1-3964a
[    6.810005] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:21:0 Kernel ABI 3:18:0
[    6.810006] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel

Device: Lenovo 300e 2nd Gen (Intel)
Hardware ID: PHASER360

**Comment by MilkyDeveloper** [comment]
I already know what it is. Maybe an `lsmod` would confirm this?

**Comment by MilkyDeveloper** [comment]
Ubuntu has a working `/etc/modprobe.d`, and Debian doesn't.

Tell me the output of:
* ```
  sudo apt install kmod
  ```
* ```
  cat /etc/modprobe.d/*
  ```

**Comment by stormchaser56** [comment]
`kmod is already the newest version (29-1+b1)`

`blacklist snd_soc_skl snd_hda_intel`

**Comment by MilkyDeveloper** [comment]
```
cp /etc/modprobe.d/* /lib/modprobe.d
```

Reboot.

**Comment by stormchaser56** [comment]
Doesn't seem to make a difference.

**Comment by MilkyDeveloper** [comment]
I don’t know then. Where does Debian Unstable keep its modprobe.d files then?
