### ISSUE TITLE
Fallocate fails on ecryptfs home directory

### ISSUE THREAD

**Issue by dakk** [cb-linux/breath#213]
If I try to run breath setup.sh on my archlinux, I get this error:
```
Building ISO at /home/dakk/linux-build/breath.img
fallocate: fallocate failed: Operation not supported
```

The problem is that my home directory is an ecryptfs mountpoint, and fallocate can't run on that, while it runs fine on other dir (ie /tmp). A solution can be to use /tmp as a destination for the linux-build directory instead of ~ (or let the user specify another directory).

**Comment by MilkyDeveloper** [comment]
I feel like we could solve this by looking at it as an XY Problem (I know, I know, it's not the solution you want hear). Try chrooting (preferably using `systemd-nspawn`) into another root file system located outside of your home directory.

**Comment by dakk** [comment]
Not  a XY problem, I was only proposing a possible solution; btw as you prefer, thanks anyway

**Comment by MilkyDeveloper** [comment]
This rootfs can be a directory (using debootstrap), it doesn't have to be a seperate volume or system.
