### ISSUE TITLE
OFFLINE install: install-to-internal-storage fails with "FATAL: do_vbutil_kernel: Error reading config file"

### ISSUE THREAD

**Issue by aubrel-g** [cb-linux/breath#214]
Hi folks, really great project.

I created the breath USB on an internet connected Debian 11 machine using the command FEATURES=ISO,KEYMAP bash setup.sh kde debian

I booted to the breath USB on my OFFLINE gemini chromebook. Everything except sound and wifi seems fine.

I ran the command install-to-internal-storage in a terminal window.

It seemed to install fine until the very end where it stopped with a fatal error:

FATAL: do_vbutil_kernel: Error reading config file

I've seached the error message in the issues for this project. The solution was to get the latest versions, which I have done.

I've searched outside github but there are no relevant solutions.

It's not possible to bring this chromebook to a wifi network or ethernet network, so I must install breath to internal storage in an offline situation. Would really appreciate any help, thanks folks.

This has taken so many hours, with my daughter's help, and I probably still left identifying information in the attached images haha

![1best](https://user-images.githubusercontent.com/106740634/171627314-b130a89a-6abb-4026-a27b-815214f80347.jpg)
![2best](https://user-images.githubusercontent.com/106740634/171627330-2c3eebe5-cc0d-4c80-9fb1-c47e2176092a.jpg)
![3best](https://user-images.githubusercontent.com/106740634/171627371-0053c7a4-aa0c-4754-8bb2-33006f29088e.jpg)

**Comment by aubrel-g** [comment]
Hi, thanks for the reply, much appreciated.

How tricky would an offline install be? If you have a moment, could you outline briefly how it could be done?

Really great project, it could get me computing with a linux machine that I could afford, finally!

**Comment by aubrel-g** [comment]
Hi again,

We replaced line 56 with the two lines you suggested.

Not a fatal error this time, but the install stopped with the message:

**"Writing storage, will take a few minutes
kernel.emmc.flags.sh: line 1: i915.modeset=1: command not found"**

I can post photos of the install process again if necessary, but there were no new or different messages apart from the error above.

**Comment by MilkyDeveloper** [comment]
Populate `kernel.emmc.flags.sh` with the text:

```
echo "console=tty1 root=${USB}p2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1"
```

Make sure to do this with a text editor, like Nano or Vim.

**Comment by aubrel-g** [comment]
Hello again. I really appreciate your attention on this.

We populated kernel.emmc.flags.sh with your text, using nano.

We weren't sure exactly what populate meant in this context: Replace the existing line in kernel.emmc.flags.sh? Or append the new text to the existing contents of kernel.emmc.flags.sh?

So we tried both, several times. The outcome was the same each time. The install process seems to overwrite kernel.emmc.flags.sh back to it's original contents. The edit you suggested in your last post doesn't persist.

Anyway, the outcome at the end of the install process is the same:

"Writing storage, will take a few minutes
kernel.emmc.flags.sh: line 1: i915.modeset=1: command not found"

So, just to clarify: 
We follow your last post and populate kernel.emmc.flags.sh with the text,
then check again that the edit is correct, 
then run install-to-internal-storage, 
the error message results, 
then we check the edit to kernel.emmc.flags.sh again but it is gone

**Comment by MilkyDeveloper** [comment]
Try removing this line:
```
echo "console=tty1 root=${USB}p2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1" > kernel.emmc.flags.sh
```

Sorry for all of this trouble, I've been hastily replying. By populate, I mean completely replace.

**Comment by aubrel-g** [comment]
Oh no. The Ents were right, beware hastiness :)
I am travelling to use the internet so can we slow down a little :) I truly hope we can get this resolved, an offline installation procedure would be useful to many people surely.


To clarify:

The contents of `kernel.emmc.flags.sh` on a **freshly created** breath USB are one line:

`console=tty1 root=/dev/mmcblk0p2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1`

We can edit `kernel.emmc.flags.sh` perfectly with nano.

Edits to `kernel.emmc.flags.sh` persist through a reboot.

Edits to `kernel.emmc.flags.sh` **DO NOT** persist through the `install-to-internal-storage` procedure.

After the install procedure fails, when we check `kernel.emmc.flags.sh` in nano, our edits have been overwritten so that the file is back to it's original state containing just the line above.

**Comment by MilkyDeveloper** [comment]
The way the script is set up, it fundamentally depends on the internet to fetch the latest kernel and command line, the latter of which is important for security and clarity when filing big reports.
