### ISSUE TITLE
Is it possible to enable Iommu on breath/ where could I set kernel flags in breath to enable iommu?

### ISSUE THREAD

**Issue by 1Guardian** [cb-linux/breath#218]
### Discussed in https://github.com/cb-linux/breath/discussions/216

<div type='discussions-op-text'>

<sup>Originally posted by **1Guardian** June  3, 2022</sup>
Hello, I wanted to mess around with some virtual machines, and wanted to know if it is possible to enable iommu groups for virtual machine passthroughs on a breath linux install. I have done it via boot parameters in grub in the past, but given the lack of grub use, I'm not sure where these parameters would need to be set. Thanks for any help anyone can offer!</div>

**Comment by MilkyDeveloper** [comment]
Enabling GVT-G is trivial. The main thing to implement is a way o change the kernel command line. I've made this Python script:
```
#!/usr/bin/env python3

import argparse
import os.path
import subprocess as sp

def parseArgs():
    # Create the parser and add arguments
    parser = argparse.ArgumentParser()

    # Positional argument for the cmdline
    parser.add_argument(
        dest='cmdline',
        type=str, nargs=1,
        help="The new kernel command line (also known as its parameters)"
    )

    # Boolean flag that doesn't accept data
    parser.add_argument(
        '-a', '--append',
        action="store_true", default=False,
        help="Append a flag rather than replacing the whole command line"
    )

    # Parse the arguments
    args = parser.parse_args()

def installPackages():
    if not os.path.exists('/usr/bin/futility'):
        if os.path.exists('/usr/bin/apt'):
            os.system('sudo apt install -y vboot-kernel-utils')
        else:
            print("Please install vboot-kernel-utils or vboot-utils for the futility binary.")
            sys.exit(1)

def generateNewKernel():

    # Get the root device
    rootProcess = sp.Popen("mount | grep ' / ' | cut -d' ' -f 1", shell=True, stdout=sp.PIPE)
    rootDevice = rootProcess.communicate()[0]
    kernelPartition = rootDevice[:-1] + '1'

    # Get the current kernel's command line
    cmdlineProcess = sp.Popen("cat /proc/cmdline", shell=True, stdout=sp.PIPE)
    cmdline = cmdlineProcess.communicate()[0]

    # Write the new kernel commandline to a file
    with open('cmdline', 'w') as f:
        if args.a:
            f.write(f"{cmdline} {args.cmdline}")
        else:
            f.write(args.cmdline)

    sp.run(f'dd if={kernelPartition} of=kernelpart', shell=True, check=True)
    sp.run(f'futility vbutil_kernel --repack newKernelPart --version 1 --keyblock /usr/share/vboot/devkeys/kernel.keyblock --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --oldblob kernelpart --config cmdline', shell=True, check=True)

def flashKernel():
    sp.run(f'sudo dd if=newKernelPart of={kernelPartition}', check=True, shell=True)

parseArgs()
installPackages()
generateNewKernel()
flashKernel()
```

Create a file with this text and then invoke it like so:
```
chmod +x myfile
./myfile --append loglevel=7
```

Give me a `dmesg`. Theoretically, you should get more logs than normal if you enable this. This is all just testing to see if this script works; it's unrelated to the GVT-G issue on hand.

**Comment by 1Guardian** [comment]
I'll let you know if it works when I get a chance to make another bootable. For now I just did what I stated above and recompiled with iommu enabled via the kernel config options. Then added some extra flags in the kernel.flags section to enable it. The issue I was running into with gvt-g originally was it requires intel_iommu=on, but the iommu groups would not populate no matter what, and gvt-g would always give an empty option subsection in the /sys dir. Recompiling with a custom kernel config to enable intel iommu was the only thing that seemed to work, but I will try it when I get a chance with a stock kernel.

**Comment by MilkyDeveloper** [comment]
Once [this CI Deployment](https://github.com/cb-linux/breath/runs/6804119795?check_suite_focus=true) finishes, new builds should have an IOMMU-enabled kernel. I'll make sure to document the existence and usage of `change-kernel-parameters`.

**Comment by 1Guardian** [comment]
Sounds good, thanks!
