### ISSUE TITLE
No sound | LARS / Skylake

### ISSUE THREAD

**Issue by runcros** [cb-linux/breath#227]
Hello, I've followed the wiki to install breath with ubuntu 22.04 and gnome then I've did the audio part but now I don't have sound.
Model name: CP5-471 (Acer Chromebook 14 for Work)
[alsa-info.txt](https://github.com/cb-linux/breath/files/8936060/alsa-info.txt)
[dmesgOutput.txt](https://github.com/cb-linux/breath/files/8936061/dmesgOutput.txt)

**Comment by lauretandretheo** [comment]
Here is my setup 
[setup-audio.txt](https://github.com/cb-linux/breath/files/8939592/setup-audio.txt)
I"ve modified the setup audio and here my alsa-info after 
[alsa-info.txt](https://github.com/cb-linux/breath/files/8939621/alsa-info.txt)

**Comment by MilkyDeveloper** [comment]
Looks like you need to run:
```
systemctl mask pipewire.socket
```

and reboot

**Comment by lauretandretheo** [comment]
`[sudo] Password of ....xxxxx
Invalid unit name "—user" escaped as "\xe2\x80\x94user" (maybe you should use systemd-escape?).
Unit \xe2\x80\x94user.service does not exist, proceeding anyway.
Unit pipewire.socket does not exist, proceeding anyway.
Created symlink /etc/systemd/system/\xe2\x80\x94user.service → /dev/null.
Created symlink /etc/systemd/system/pipewire.socket → /dev/null.
`

Is this a good output ?

**Comment by MilkyDeveloper** [comment]
Reboot and give me another `alsa-info` log…

**Comment by lauretandretheo** [comment]
[alsainfo.txt](https://github.com/cb-linux/breath/files/8943155/alsainfo.txt)
Okay done, here are for you, thanks

**Comment by MilkyDeveloper** [comment]
What does `speaker-test` output? Does it play any audio?

**Comment by lauretandretheo** [comment]
It doesn't play audio :/
Here the output : 
`speaker-test 1.2.6`
`Le périphérique de lecture est default`
`Les paramètres du flux sont 48000Hz, S16_LE, 1 canaux`
`Utilisation de 16 octaves de 'pink noise'`
`ALSA lib pcm_direct.c:1284:(snd1_pcm_direct_initialize_slave) unable to install hw params`
`ALSA lib pcm_dmix.c:1044:(snd_pcm_dmix_open) unable to initialize slave`
`Erreur d'ouverture à la lecture: -22,Argument invalide`

**Comment by lauretandretheo** [comment]
I've tried another device with -D argument and all hw, sysdefault, plughw card do nothing when I do the command, looking like there are sleeping... 

When I run with dmix or default I get same ouput as before

**Comment by MilkyDeveloper** [comment]
You’re on 5.10.106; the instructions stated that if you are on Skylake or Kabylake you have to run a specific command (you don’t need to run `setup-audio` since you already ran it). You might have already done it, but my CI was misconfigured then.

Check back there and see if it works.

**Comment by lauretandretheo** [comment]
Excuse me what I have to do ?

**Comment by MilkyDeveloper** [comment]
No worries!
```
VERSION=ALT bash updatekernel.sh
```

**Comment by lauretandretheo** [comment]
Thank you, can I run this directly on the breath-installed chromebook ? (I've installed breath into internal memory)

**Comment by MilkyDeveloper** [comment]
No, you have to run it on your PC with the Breath USB plugged in.

You could use this command directly on your Chromebook:
```
VERSION=ALT updatekernel-on-emmc
```

**Comment by MilkyDeveloper** [comment]
Yay! I've never had a user report a SKL/KBL Chromebook with a working microphone.

If you don't mind, I'll be keeping this issue open until I implement changes to `setup-audio`.

**Comment by lauretandretheo** [comment]
I can be your SKL tester okay, just my microphone is working using arecord but when I open chrome browser I can't test it (I think it's another problem)

**Comment by MilkyDeveloper** [comment]
I'm wondering why you had to mount a recovery image rather than ChromeOS already installed on the disk. Do you, by chance, have the output of `lsblk` before installing Breath on your EMMC.

**Comment by lauretandretheo** [comment]
I had already uninstalled chrome os to install breath instead, so instead of reinstalling chrome os I retrieved the "ROOT-A" (from original lars recovery image) which I burned to an img in order not to have to reinstall chrome os,(perhaps it would be necessary to be able to select an image without reinstalling chrome os and booted from usb)

**Comment by runcros** [comment]
I close this issue, since a fix has been proposed.
