### ISSUE TITLE
Search button inputs caps lock instead of super

### ISSUE THREAD

**Issue by Fornball** [cb-linux/breath#229]
The chromeos search button is recognized as caps lock instead of the windows/super button.
Both the german and english layouts recognize it as caps lock. The actual physical keyboard layout is german.

The command I used to create the usb stick: ```FEATURES=KEYMAP bash setup.sh gnome ubuntu```

**Comment by Fornball** [comment]
Thank you! After logging out and back in, it works.

**Comment by lauretandretheo** [comment]
#230 

Oh sorry I've already do it lol...
