### ISSUE TITLE
[SKL/KBL Testers needed] Pipewire working!

### ISSUE THREAD

**Issue by runcros** [cb-linux/breath#232]
Hello, today I found (problaby, so need testing) a working around to make pipepire working. 
To contribute, you need working audio configuration (look at the doc) 
After post here, we will do the configuration to make pipewire working. 
(If it works, I will do a PR to make the enhancement global available) 

(Tested on Acer CP5-471 (Chromebook 14 for work) board:lars)
At this time, all pipewire based app works except gnome settings (it shows sounds card but speaker test don't work also for microphone).
Internal speaker and jack are working. But sometimes a loss of sound appears and you have to restart.
Microphone (there is noise but nothing conclusive) and HDMI need more testing, don't always work. 

Skylake and Kabylake users can test it if pipewire don't work on their distro.

For faster answer and test, let's talk on discord : commando29#0615
Further improvement to get stable pipewire will be added during testing.

**Comment by andrzej-onja** [comment]
I have ASUS-Chromebook-C523NA how can I help with testing ?

**Comment by runcros** [comment]
> I have ASUS-Chromebook-C523NA how can I help with testing ?
> (could not find you on discord)

Join our discord https://discord.gg/WatsaYhXCa
