### ISSUE TITLE
Breath doesn't build (Ubuntu/Arch)

### ISSUE THREAD

**Issue by GlaZedBelmont** [cb-linux/breath#233]
Tried building latest commit and it keeps erroring out

**Comment by GlaZedBelmont** [comment]
![image](https://user-images.githubusercontent.com/48196637/175240342-2ec516df-037f-416f-95f9-6ff422173b67.png)

**Comment by GlaZedBelmont** [comment]
`FEATURES=KEYMAP bash setup.sh kde ubuntu jammy-22.04`
`FEATURES=ISO,KEYMAP bash setup.sh kde ubuntu jammy-22.04`
`FEATURES=ISO,KEYMAP bash setup.sh cli arch`

are the commands used so far

**Comment by lauretandretheo** [comment]
Just in case can you post the output of "df -h" also please.

**Comment by GlaZedBelmont** [comment]
![image](https://user-images.githubusercontent.com/48196637/175247712-bc572af3-51f2-4dce-bdb2-073e28a18c0a.png)
whole output coming soon

**Comment by lauretandretheo** [comment]
Alright, I'll build on my side also to see if it's an isolated issue or not.

**Comment by GlaZedBelmont** [comment]
[output.txt](https://github.com/cb-linux/breath/files/8965359/output.txt)

**Comment by lauretandretheo** [comment]
On my side, I can build it, can you do same task as before (upload then) but now use this command :
`FEATURES=ISO,KEYMAP bash -x setup.sh kde ubuntu 2>&1 | tee output.txt`

**Comment by lauretandretheo** [comment]
On this output I see that you had successfully build the iso. 
You can close this issue and use the another vm or we can try to find the problem on the original vm but you have to send the output.txt of the vm that is causing the issue.

**Comment by lauretandretheo** [comment]
Can you replace the content of utils/extract.sh with the content of the following file. 
[extract.txt](https://github.com/cb-linux/breath/files/8966332/extract.txt)
Then test 
`FEATURES=ISO,KEYMAP bash -x setup.sh kde ubuntu 2>&1 | tee output.txt` and upload the file.

**Comment by GlaZedBelmont** [comment]
on which install? the one that worked or the one that did not?

**Comment by lauretandretheo** [comment]
Then if you have successfully build, you can close the issue. I will do a pull request so that issue doesn't happen again.

**Comment by GlaZedBelmont** [comment]
https://discord.gg/bt5r9xCM3a I think this could interest you, it's a server to talk about putting windows/linux on chromebooks,, Milky is in there, you could find Skylake testers (like myself) fairly easily by going there
