### ISSUE TITLE
no sound on Asus Flip CM5 (CM5500FD) model WOOMAX-NAMM

### ISSUE THREAD

**Issue by pierremad** [cb-linux/breath#246]
Hi,
Thanks for good works, first. Everything is OK on deban 11 except sound on Asus Flip CM5 (CM5500FD) model WOOMAX-NAMM on boot screen. 
for your wiki try without success :  
Everything else: sof-setup-audio
Doesn’t work? Try SOUNDCARD=rtk sof-setup-audio
Since Debian is installed on usb key i can send you info about chromeos if needed.
Thanks

**Comment by pierremad** [comment]
as root do rm -rf
output sof-setup-audio
root@chromeos:~# sof-setup-audio
Installing Audio...
pcm.!default {
    type plug
    slave.pcm "softvol"
}

pcm.softvol {
    type softvol # Software volume control
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card 0
    }
}
[Unit]
Description="Reload ALSA and set the correct UCM"

[Service]
User=root
WorkingDirectory=/
ExecStart=/bin/bash -c 'modprobe snd_soc_max98357a snd_soc_da7219 && alsa reload'

[Install]
WantedBy=multi-user.target
Cloning into 'sof-bin'...
remote: Enumerating objects: 1156, done.
remote: Counting objects: 100% (1156/1156), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 1156 (delta 1048), reused 1105 (delta 1014), pack-reused 0
Receiving objects: 100% (1156/1156), 7.17 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (1048/1048), done.
blacklist snd_soc_skl snd_hda_intel
SOF enabled successfully! Reboot to enable audio

**Comment by pierremad** [comment]
Hi,
here's information :
output of alsa-info http://alsa-project.org/db/?f=cde1e0a6133969319ac8fb474f20fe5a92cd1c3c
as root do rm -rf ./sof-bin
output sof-setup-audio
root@chromeos:~# sof-setup-audio
Installing Audio...
pcm.!default {
    type plug
    slave.pcm "softvol"
}

pcm.softvol {
    type softvol # Software volume control
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card 0
    }
}
[Unit]
Description="Reload ALSA and set the correct UCM"

[Service]
User=root
WorkingDirectory=/
ExecStart=/bin/bash -c 'modprobe snd_soc_max98357a snd_soc_da7219 && alsa reload'

[Install]
WantedBy=multi-user.target
Cloning into 'sof-bin'...
remote: Enumerating objects: 1156, done.
remote: Counting objects: 100% (1156/1156), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 1156 (delta 1048), reused 1105 (delta 1014), pack-reused 0
Receiving objects: 100% (1156/1156), 7.17 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (1048/1048), done.
blacklist snd_soc_skl snd_hda_intel
SOF enabled successfully! Reboot to enable audio
thanks

**Comment by pierremad** [comment]
here's the lsmod with debian 11

[lsmod-linux.txt](https://github.com/cb-linux/breath/files/8987361/lsmod-linux.txt)
will update with chromeos

**Comment by runcros** [comment]
Can we talk on discord please, runcros#0615

**Comment by runcros** [comment]
Can you add me on discord we will get a try runcros#0615

**Comment by MilkyDeveloper** [comment]
@runcros This is a UCM issue, FYI.
