### ISSUE TITLE
iso creation errors out on crostini

### ISSUE THREAD

**Issue by JakoDel** [cb-linux/breath#248]
used: FEATURES=ISO,KEYMAP,CROSTINI bash setup.sh cli arch

(10/12) Reloading system bus configuration...
  Skipped: Running in chroot.
(11/12) Warn about old perl modules
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
(12/12) Updating the info directory file...
umount: /tmp/arch/mnt: block devices are not permitted on filesystem.
umount: /tmp/arch: block devices are not permitted on filesystem.
rm: cannot remove '/tmp/arch/mnt': Device or resource busy
chroot: failed to run command ‘/bin/sh’: No such file or directory
chroot: failed to run command ‘/bin/sh’: No such file or directory
P.S: ran this on root after running the commands on chromium bug tracker

**Comment by runcros** [comment]
Have you tried a clean install?

**Comment by JakoDel** [comment]
> Have you tried a clean install?

thanks for the reply! but.. what do you mean by that? what should I try clean installing?

**Comment by runcros** [comment]
I mean on a Chromebook the most updated as possible, and crostini that have never been used (uninstalled then reinstalled)

**Comment by runcros** [comment]
No answer, I close the issue.
