### ISSUE TITLE
Fedora Support

### ISSUE THREAD

**Issue by noidontwanttolearntocode69** [cb-linux/breath#258]
Can I just replace `FEATURES=ISO,KEYMAP bash setup.sh cli ubuntu` with `FEATURES=ISO,KEYMAP bash setup.sh gnome fedora` and build breath with fedora instead of arch, debian, or ubuntu? The docs don't say that I can but I saw a previous issue where someone had that script.

**Comment by MilkyDeveloper** [comment]
The script doesn't know how to install specific desktops on Fedora. You might have luck with using `cli` instead of a desktop and then installing one later.
