### ISSUE TITLE
No WiFi module in nmcli.

### ISSUE THREAD

**Issue by KannaHayabusa** [cb-linux/breath#261]
Running the command only shows loopback, no wlan. Using the Arch installation on my Lenovo Ideapad Flex 5.

**Comment by CorruptedPlazma** [comment]
I noticed this too on an HP Chromebook 14a, Blooglet board.

**Comment by MilkyDeveloper** [comment]
You can still write it to a file, transfer it through a USB, and upload it; or save it to a file and then put your Breath USB on a Linux Computer and find the file.

**Comment by KannaHayabusa** [comment]
[dmesg.txt](https://github.com/cb-linux/breath/files/9067074/dmesg.txt)

**Comment by MilkyDeveloper** [comment]
Reclone the git repo and remake the USB
