### ISSUE TITLE
Sound does not work on Elemi

### ISSUE THREAD

**Issue by mcirsta** [cb-linux/breath#265]
I've just installed Arch on Elemi (HP Chromebook 14a-nb0010ng) using Breath and I like the experience.
 The only thing that I've found not working is the sound.
 I'm attaching the dmesg from Chrome OS and from Arch and the alsa-info from Arch ( I didn't think to get it from Chrome OS).

 It looks like a driver issue to me but I'm not that good in the Linux sound system and even less when it comes to the Chromebook one.

 Let me know if you need any more info or testing.
[alsa-info.txt](https://github.com/cb-linux/breath/files/9077384/alsa-info.txt)
[dmesg-arch.txt](https://github.com/cb-linux/breath/files/9077385/dmesg-arch.txt)
[dmesg-chromebook.txt](https://github.com/cb-linux/breath/files/9077386/dmesg-chromebook.txt)

**Comment by MilkyDeveloper** [comment]
This is Tigerlake Chromebook so it theoretically should work fine. If you don't mind, does audio work on an Ubuntu USB created with Breath?

**Comment by mcirsta** [comment]
Unfortunately the result is exactly the same. I'm attaching the dmesg from Ubuntu.

The key part to me in both these Linux failures seems this:

_[    8.336033] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #2 probe error, ret: -2
[    8.336140] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!_

[dmesg-ubuntu.txt](https://github.com/cb-linux/breath/files/9077975/dmesg-ubuntu.txt)

**Comment by mcirsta** [comment]
Unfortunately the issue is still not fully resolved as far as I can tell. 
 Now this code probe error is gone but I only see input devices being created in dmesg for some reason.
 I'm attaching the new dmesg. I didn't recreate the entire image as that seemed a bit too drastic. I just changed the file as per your fix for this and here's the result now
[dmesg_new.txt](https://github.com/cb-linux/breath/files/9176703/dmesg_new.txt)
.

**Comment by MilkyDeveloper** [comment]
Recreating the USB is the only way it’ll work. It won’t get fixed out of thin air

**Comment by mcirsta** [comment]
I manually changed the file:

_cat /etc/modprobe.d/alsa-breath.conf 
blacklist snd_hda_intel
blacklist snd_soc_skl
softdep snd_sof_pci_intel_icl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_cnl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_apl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tng pre: snd_hda_codec_hdmi_

It looks like this now and also removed the old one. This is why I expected it to work as from what I saw that is the only change made.
 At least that's what I understood, not expecting it would just work.
 Anyway I appreciate your efforts and the fix does work, it's just that it's not fully working as I said above. I still don't see anything but the dummy output in KMix.
