### ISSUE TITLE
No Audio - HP Chromebook 14 G5 EE Snappy

### ISSUE THREAD

**Issue by superfemily** [cb-linux/breath#27]
Hello, thanks for this awesome project!

I have everything working but audio on my HP Chromebook currently. I tried all 3 audio commands in the docs.

It is an HP Chromebook 14 G5 EE, the full recovery mode screen says: SNAPPY E25-C2B-P2Y-Q77-X3Q-A2Q

Running lspci and lsmod in crosh gives me this:
**lspci**
00:00.0 Host bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Host Bridge (rev 0b)
00:00.1 Signal processing controller: Intel Corporation Device 5a8c (rev 0b)
00:00.2 Non-Essential Instrumentation [1300]: Intel Corporation Device 5a8e (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Device 5a85 (rev 0b)
00:03.0 Multimedia controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Imaging Unit (rev 0b)
00:0e.0 Multimedia audio controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster (rev 0b)
00:0f.0 Communication controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Trusted Execution Engine (rev 0b)
00:14.0 PCI bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port B #1 (rev fb)
00:15.0 USB controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series USB xHCI (rev 0b)
00:16.0 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #1 (rev 0b)
00:16.1 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #2 (rev 0b)
00:16.2 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #3 (rev 0b)
00:16.3 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #4 (rev 0b)
00:17.0 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #5 (rev 0b)
00:17.1 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #6 (rev 0b)
00:18.0 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series HSUART Controller #1 (rev 0b)
00:18.1 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series HSUART Controller #2 (rev 0b)
00:18.2 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series HSUART Controller #3 (rev 0b)
00:19.0 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series SPI Controller #1 (rev 0b)
00:1b.0 SD Host controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series SDXC/MMC Host Controller (rev 0b)
00:1c.0 SD Host controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series eMMC Controller (rev 0b)
00:1f.0 ISA bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Low Pin Count Interface (rev 0b)
00:1f.1 SMBus: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series SMBus Controller (rev 0b)
01:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)

**lsmod**
Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                 94208  0
stp                    16384  1 bridge
llc                    16384  2 stp,bridge
tun                    28672  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   16384  0
ah6                    16384  0
ip6t_REJECT            16384  2
nf_reject_ipv6         16384  1 ip6t_REJECT
ip6t_ipv6header        16384  0
vhost_vsock            20480  5
vmw_vsock_virtio_transport_common    20480  1 vhost_vsock
vsock                  32768  7 vmw_vsock_virtio_transport_common,vhost_vsock
vhost                  24576  1 vhost_vsock
veth                   16384  0
rfcomm                 40960  4
cmac                   16384  3
xt_cgroup              16384  2
algif_hash             16384  1
algif_skcipher         20480  1
af_alg                 16384  6 algif_hash,algif_skcipher
ipt_MASQUERADE         16384  1
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xt_mark                16384  96
uinput                 20480  0
ccm                    20480  2
btusb                  40960  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             413696  32 btbcm,btrtl,btusb,rfcomm,btintel
uvcvideo               81920  0
videobuf2_vmalloc      16384  1 uvcvideo
videobuf2_v4l2         24576  1 uvcvideo
videobuf2_core         28672  2 uvcvideo,videobuf2_v4l2
videobuf2_memops       16384  1 videobuf2_vmalloc
iio_trig_hrtimer       16384  2
industrialio_sw_trigger    16384  1 iio_trig_hrtimer
industrialio_configfs    16384  2 industrialio_sw_trigger
iio_trig_sysfs         16384  0
snd_soc_sst_bxt_da7219_max98357a    24576  3
snd_soc_hdac_hdmi      24576  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  1
snd_soc_skl_ssp_clk    16384  0
snd_soc_skl            65536  3 snd_soc_skl_ssp_clk
snd_soc_skl_ipc        36864  1 snd_soc_skl
snd_soc_sst_dsp        32768  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_sst_match      16384  1 snd_soc_skl
snd_hda_ext_core       20480  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_hda_core           53248  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
snd_soc_max98357a      16384  1
acpi_als               16384  1
industrialio_triggered_buffer    16384  1 acpi_als
kfifo_buf              16384  1 industrialio_triggered_buffer
industrialio           49152  5 iio_trig_hrtimer,industrialio_triggered_buffer,iio_trig_sysfs,acpi_als,kfifo_buf
snd_soc_da7219         53248  2 snd_soc_sst_bxt_da7219_max98357a
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                   90112  20
ip6table_filter        16384  2
cros_ec_sensorhub      20480  0
zram                   24576  1
iwlmvm                409600  0
iwlwifi               344064  1 iwlmvm
iwl7000_mac80211      655360  2 iwlwifi,iwlmvm
cfg80211              479232  3 iwlwifi,iwlmvm,iwl7000_mac80211
joydev                 20480  0

**Comment by superfemily** [comment]
Should also mention this is on the default 21.04 Hirsute with XFCE

**Comment by MilkyDeveloper** [comment]
Looks like this is a `reef` device. I've recently added audio support for these devices in #6. The docs have also been updated to show this.
