### ISSUE TITLE
Building image fails because there are files in /mnt

### ISSUE THREAD

**Issue by NorthboundPaddler** [cb-linux/breath#270]
I am trying to build the image to flash onto a USB drive, however I am running into an error message when running setup.sh and just after I enter the hostname. I get the following regardless of what options I provide:
```
utils/bootstrap.sh: line 9: There are files in /mnt! Please clear this directory of any valuable information!: No such file or directory
```

I am attempting to build the image file on a desktop running Pop!_OS, and I indeed to have files in the /mnt directory of this PC (another pair of drives in a RAID-1 configuration for media storage). Do I really need to unmount those for this installation to proceed? This doesn't make much sense to me...

**Comment by MilkyDeveloper** [comment]
`/mnt` is used to mount and write to the USB. Most people's setups have this directory unused.

However, you might have some luck editing [this line](https://github.com/cb-linux/breath/blob/main/setup.sh#L18) to another path.
