### ISSUE TITLE
No sound nor Network on Samsung Chromebook Pro (CAROLINE)

### ISSUE THREAD

**Issue by MadMcCrow** [cb-linux/breath#273]
Hi!
I've tested both with Arch and Ubuntu with and without gnome for the latter. as per title, no audio devices, nor network devices where picked up. I even tried plugin a usb-C dock with ethernet to no avail. here's the raw output of dmesg : 
[dmesg.txt](https://github.com/cb-linux/breath/files/9134026/dmesg.txt)

**Comment by runcros** [comment]
Hello please join our discord, we will give you support 

https://discord.gg/WatsaYhXCa

**Comment by ericsbelcher** [comment]
This is the output I have for
sudo alsa-info

!!################################
!!ALSA Information Script v 0.5.1
!!################################

!!Script ran on: Thu Jul 21 11:32:46 UTC 2022


!!Linux Distribution
!!------------------

Ubuntu 22.04 LTS \n \l DISTRIB_ID=Ubuntu DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS" PRETTY_NAME="Ubuntu 22.04 LTS" NAME="Ubuntu" ID=ubuntu ID_LIKE=debian HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" UBUNTU_CODENAME=jammy Ubuntu 22.04 LTS (Jammy Jellyfish)


!!DMI Information
!!---------------

Manufacturer:      Google
Product Name:      Casta
Product Version:   rev5
Firmware Version:  Google_Casta.11297.242.0
System SKU:        sku1
Board Vendor:      Google
Board Name:        Casta


!!ACPI Device Status Information
!!---------------

/sys/bus/acpi/devices/ACPI0003:00/status 	 15
/sys/bus/acpi/devices/BOOT0000:00/status 	 11
/sys/bus/acpi/devices/DLGS7219:00/status 	 15
/sys/bus/acpi/devices/ELAN0000:00/status 	 15
/sys/bus/acpi/devices/GGL0001:00/status 	 11
/sys/bus/acpi/devices/GOOG0003:00/status 	 11
/sys/bus/acpi/devices/GOOG0004:00/status 	 11
/sys/bus/acpi/devices/GOOG0006:00/status 	 11
/sys/bus/acpi/devices/GOOG000A:00/status 	 15
/sys/bus/acpi/devices/GOOG9999:00/status 	 11
/sys/bus/acpi/devices/INT3400:00/status 	 15
/sys/bus/acpi/devices/INT3403:00/status 	 15
/sys/bus/acpi/devices/INT3403:01/status 	 15
/sys/bus/acpi/devices/INT3403:02/status 	 15
/sys/bus/acpi/devices/INT3403:03/status 	 15
/sys/bus/acpi/devices/INT3453:00/status 	 15
/sys/bus/acpi/devices/INT3453:01/status 	 15
/sys/bus/acpi/devices/INT3453:02/status 	 15
/sys/bus/acpi/devices/INT3453:03/status 	 15
/sys/bus/acpi/devices/LNXPOWER:00/status 	 15
/sys/bus/acpi/devices/LNXPOWER:01/status 	 15
/sys/bus/acpi/devices/MX98357A:00/status 	 15
/sys/bus/acpi/devices/PNP0C02:00/status 	 15
/sys/bus/acpi/devices/PNP0C02:01/status 	 15
/sys/bus/acpi/devices/PNP0C0A:00/status 	 31
/sys/bus/acpi/devices/PRP0001:00/status 	 15
/sys/bus/acpi/devices/ZNT0000:00/status 	 15
/sys/bus/acpi/devices/device:13/status 	 15
/sys/bus/acpi/devices/device:2b/status 	 15


!!Kernel Information
!!------------------

Kernel release:    5.10.106
Operating System:  GNU/Linux
Architecture:      x86_64
Processor:         x86_64
SMP Enabled:       Yes


!!ALSA Version
!!------------

Driver version:     k5.10.106
Library version:    1.2.6.1
Utilities version:  1.2.6


!!Loaded ALSA modules
!!-------------------



!!Sound Servers on this system
!!----------------------------

PipeWire:
      Installed - Yes (/usr/bin/pipewire)
      Running - Yes

Pulseaudio:
      Installed - Yes (/usr/bin/pulseaudio)
      Running - Yes


!!Soundcards recognised by ALSA
!!-----------------------------

--- no soundcards ---


!!PCI Soundcards installed in the system
!!--------------------------------------

00:0e.0 Multimedia audio controller [0401]: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio [8086:3198] (rev 03)
	Subsystem: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio [8086:7270]


!!Modprobe options (Sound related)
!!--------------------------------

snd_pcsp: index=-2
snd_usb_audio: index=-2
snd_atiixp_modem: index=-2
snd_intel8x0m: index=-2
snd_via82xx_modem: index=-2
snd_atiixp_modem: index=-2
snd_intel8x0m: index=-2
snd_via82xx_modem: index=-2
snd_usb_audio: index=-2
snd_usb_caiaq: index=-2
snd_usb_ua101: index=-2
snd_usb_us122l: index=-2
snd_usb_usx2y: index=-2
snd_cmipci: mpu_port=0x330 fm_port=0x388
snd_pcsp: index=-2
snd_usb_audio: index=-2
snd_hda_intel: dmic_detect=0
snd_intel_dspcfg: dsp_driver=3
snd_sof_pci: fw_path="intel/sof"


!!Loaded sound module options
!!---------------------------


!!Sysfs card info
!!---------------

!!Card: /sys/class/sound/card*
Driver: 
Tree:
	/sys/class/sound/card*  [error opening dir]


!!ALSA Device nodes
!!-----------------

crw-rw----  1 root audio 116,  1 Jul 21 07:31 /dev/snd/seq
crw-rw----  1 root audio 116, 33 Jul 21 07:31 /dev/snd/timer


!!ALSA configuration files
!!------------------------

!!System wide config file (/etc/asound.conf)

pcm.!default {
    type plug
    slave.pcm "softvol"
}

pcm.softvol {
    type softvol # Software volume control
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card 0
    }
}


!!Aplay/Arecord output
!!--------------------

APLAY

aplay: device_list:274: no soundcards found...

ARECORD

arecord: device_list:274: no soundcards found...

!!Amixer output
!!-------------


!!Alsactl output
!!--------------

--startcollapse--
--endcollapse--


!!All Loaded Modules
!!------------------

bluetooth
btbcm
btintel
btrtl
btusb
crc32c_intel
dm_multipath
ecc
ecdh_generic
fat
fuse
iwlmvm
iwlwifi
joydev
ledtrig_audio
nls_cp437
nls_iso8859_1
snd_hda_codec
snd_hda_codec_hdmi
snd_hda_core
snd_hda_ext_core
snd_hwdep
snd_intel_dspcfg
snd_soc_acpi
snd_soc_acpi_intel_match
snd_soc_da7219
snd_soc_dmic
snd_soc_hdac_hda
snd_soc_max98357a
snd_sof
snd_sof_intel_hda
snd_sof_intel_hda_common
snd_sof_pci
snd_sof_pci_intel_apl
snd_sof_xtensa_dsp
uvcvideo
vfat
videobuf2_vmalloc


!!ALSA/HDA dmesg
!!--------------

[    0.000000] Linux version 5.10.106 (runner@fv-az173-733) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1 SMP PREEMPT Sun Jun 26 22:27:27 UTC 2022
[    0.000000] Command line: cros_secure console=tty1 root=/dev/sda2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1  snd-intel-dspcfg.dsp_driver=3 snd_sof_pci.fw_path="intel/sof"
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
--
[    0.023385] Policy zone: Normal
[    0.023389] Kernel command line: cros_secure console=tty1 root=/dev/sda2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1  snd-intel-dspcfg.dsp_driver=3 snd_sof_pci.fw_path="intel/sof"
[    0.024116] Dentry cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
--
[    0.109182] ACPI: Added _OSI(Linux-Dell-Video)
[    0.109185] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[    0.109188] ACPI: Added _OSI(Linux-HPI-Hybrid-Graphics)
--
[    0.823533] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    0.824172] ALSA device list:
[    0.824724]   No soundcards found.
[    0.825321] Waiting for root device /dev/sda2...
--
[    8.658863] Bluetooth: SCO socket layer initialized
[    8.838437] pci 0000:00:0e.0: attach allowed to drvr sof-audio-pci-intel-apl [internal device]
[    8.838734] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    8.838870] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[    8.844217] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    8.856524] sof-audio-pci-intel-apl 0000:00:0e.0: codec #2 probe error, ret: -2
[    8.856660] sof-audio-pci-intel-apl 0000:00:0e.0: no hda codecs found!
[    8.860289] usb 1-9: GPIO lookup for consumer reset
--
[    8.869568] Bluetooth: hci0: Found device firmware: intel/ibt-17-16-1.sfi
[    8.884350] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:1:1-3964a
[    8.884355] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:21:0 Kernel ABI 3:18:0
[    8.884357] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    8.884368] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    9.409073] iwlwifi 0000:00:0c.0 wlp0s12f0: renamed from wlan0
--
[   10.269024] Bluetooth: hci0: Firmware revision 0.1 build 174 week 4 2022
[   11.915088] sof-audio-pci-intel-apl 0000:00:0e.0: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   11.916975] sof-audio-pci-intel-apl 0000:00:0e.0: error: extended rom status:  0x81000012 0x2c 0x0 0x0 0x0 0x0 0x1551100 0x0
[   11.918359] sof-audio-pci-intel-apl 0000:00:0e.0: error: load fw failed ret: -110
[   11.919738] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to reset DSP
[   11.921079] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to boot DSP firmware -110
[   11.972592] sof-audio-pci-intel-apl 0000:00:0e.0: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   11.973976] sof-audio-pci-intel-apl 0000:00:0e.0: error: dsp core reset failed: core_mask 1
[   11.985559] sof-audio-pci-intel-apl 0000:00:0e.0: error: sof_probe_work failed err: -110
[   12.171964] pci 0000:00:0e.0: attach allowed to drvr sof-audio-pci-intel-apl [internal device]
[   12.172987] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[   12.173164] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[   12.207211] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[   12.217035] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[   12.217224] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:1:1-3964a
[   12.217227] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:21:0 Kernel ABI 3:18:0
[   12.217228] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[   12.217235] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[   12.225285] da7219 i2c-DLGS7219:00: Using default DAI clk names: da7219-dai-wclk, da7219-dai-bclk
--
[   12.229899] gpio gpiochip1: Persistence not supported for GPIO 15
[   15.749593] sof-audio-pci-intel-apl 0000:00:0e.0: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   15.751123] sof-audio-pci-intel-apl 0000:00:0e.0: error: extended rom status:  0x81000012 0x2c 0x0 0x0 0x0 0x0 0x1551100 0x0
[   15.752548] sof-audio-pci-intel-apl 0000:00:0e.0: error: load fw failed ret: -110
[   15.753973] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to reset DSP
[   15.755374] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to boot DSP firmware -110
[   15.807087] sof-audio-pci-intel-apl 0000:00:0e.0: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   15.808524] sof-audio-pci-intel-apl 0000:00:0e.0: error: dsp core reset failed: core_mask 1
[   15.818690] sof-audio-pci-intel-apl 0000:00:0e.0: error: sof_probe_work failed err: -110
[   24.230404] wlp0s12f0: authenticate with c0:d7:aa:d7:e0:cc


!!Packages installed
!!--------------------

ii  alsa-oss                                   1.1.8-1                                 amd64        ALSA wrapper for OSS applications
ii  alsa-tools                                 1.2.5-2                                 amd64        Console based ALSA utilities for specific hardware
ii  alsa-tools-gui                             1.2.5-2                                 amd64        GUI based ALSA utilities for specific hardware
ii  alsa-topology-conf                         1.2.5.1-2                               all          ALSA topology configuration files
ii  alsa-ucm-conf                              1.2.6.3-1ubuntu1                        all          ALSA Use Case Manager configuration files
ii  alsa-utils                                 1.2.6-1ubuntu1                          amd64        Utilities for configuring and using ALSA

[http://alsa-project.org/db/?f=bc88856a8ec254bcfcb5e8ad689ff2bb431ed2f3](url)
