### ISSUE TITLE
Trying to install OpenRazer

### ISSUE THREAD

**Issue by Sudham6** [cb-linux/breath#284]
Hey, recently I bought a Razer mouse and found out that its software for Linux is a program or driver called OpenRazer and I have tried to install it but it always ends up with some kernel issues so I was hoping you could fix it or help me fix it. 

Screenshots: 
![Screenshot 2022-07-22 12:50:26](https://user-images.githubusercontent.com/87921028/180486915-1c612eec-3c00-44c2-a461-2254d912aba8.png)

I have tried their troublshooting but I have no kernel headers so i dont how to install for the breath kernel so please can u help me. Thank you

**Comment by MilkyDeveloper** [comment]
We're going to provide a release for UEFI that includes kernel headers.
