### ISSUE TITLE
Can't boot from Breath USB - Acer 713 i5 Tiger Lake

### ISSUE THREAD

**Issue by rainingcrypto** [cb-linux/breath#298]
Hello,
New Acer 713 Spin, i5, Tiger Lake series CPU here.
I enabled Developer mode, enabled USB booting and made used Breath to create two images, Ubuntu Gnome and Debian KDE. I created them on another linux machine I have, and wrote them to USB with Etcher.

When I select "external storage" on the Chromebook boot menu with the USB plugged in, the screen goes black and the USB stops being read (as indicated by the absence of flashing lights). Then I need to power cycle the Chromebook by holding the power button to turn it off. 

See video attached (and I've tested both standard USB and USB adapter for Micro SD, as shown in video):
https://user-images.githubusercontent.com/74947552/182518339-36fc7c5e-fb23-4c1f-ab99-1d4bbe66343c.mp4

Thanks so much for your help, the entire community is very gracious!

**Comment by North2212** [comment]
Hey there, 
I had some issues too.
When writing the image raw using dd, or using etcher on linux didn't boot.
If you have a windows machine try using rufus to write the disk image.
Set the partition scheme as GPT, target system as UEFI only and file system fat32

I can't get the sound to work properly with breath maybe you'll have more luck.

The other option you could try is running vanilla ubuntu, if you flash the mrchromebox script https://mrchromebox.tech/#fwscript and boot through legacy mode. everything except touchscreen works on my chromebook

**Comment by MilkyDeveloper** [comment]
Fixed, run `sudo rm -rf ~/linux-build; bash updatekernel.sh` on the PC you built Breath with.
