### ISSUE TITLE
Can't boot from Breath USB - Asus C433 i5

### ISSUE THREAD

**Issue by krisek** [cb-linux/breath#299]
Very similarly to #298, I cannot boot Breath written micro-sd on my Asus C433 i5. I tried to write out the image with balenaEtcher, Startup Disk Creator and finally on Windows with Rufus. No success: after pressing Ctrl+u, the screen goes blank the usb / sd-card adapter flashes twice (or so) and that's all. The Chromebook has a micro-sd slot, similar results there too (blank screen after pressing Ctrl+u).

Any hints?

If I look at the written disk layout with gparted, it seems to be ok, a small partition labelled as chromeos_kernel, and an ext4 partition containing the Linux installation.

**Comment by MilkyDeveloper** [comment]
Fixed, run `sudo rm -rf ~/linux-build; bash updatekernel.sh` on the PC you built Breath with.
