### ISSUE TITLE
black screen bootup

### ISSUE THREAD

**Issue by digby5** [cb-linux/breath#300]
its a gallop-fobb asus CX1700
first try: gnome debian using dd to write from a kali linux
second try: cli fedora via omitting the ISO command, kali again
both options lead to just a black screen after selecting external boot option in CTRL-U developer menu

**Comment by sikclown** [comment]
Same issue here on a Samsung Galaxy Chromebook model KOHAKU-JPZQ
First try: CLI Ubuntu using Ecther to write from Ubuntu 22.04 Dell XPS 13 on a SanDisk 32gb USB 3.0 device (Black screen at boot and never moves)
Second try: Gnome Ubuntu using Rufus on Windows to write (Unable to boot error message)
Third Try: Minimal Ubuntu using dd to write from Pop OS 22.04 5.18 to a Sandisk 256GB USB 3.1 device (Black Screen boot and never moves)

**Comment by nplawes** [comment]
Same here on an ASUS CX1400 Chromebook...

first: FEATURES=ISO,KEYMAP bash setup.sh xfce ubuntu focal-20.04
second: FEATURES=ISO,KEYMAP bash setup.sh cli ubuntu focal-20.04

Boots to white screen, Ctrl-U makes the screen go black, and it stays that way.

**Comment by skerce** [comment]
Same issue with an Lenovo IdeaPad Flex 3i Chromebook Gen 6 (11" Intel N4500), board name: Botenflex.

Tried multiple distros, options and storage devices but still a black screen on boot.

RW_LEGACY Firmware works well on the Chromebook, but with the known issues around onboard audio and touchscreen support.

**Comment by ThePizzaTimeBandit** [comment]
Same issue with Samsung Galaxy Chromebook 2.

Tried every supported distro.  Tried cli, gnome, and xfce.  Ran from my chromebook crostini install with FEATURES=ISO,crostini bash setup.sh as well as from a Debian vm.

**Comment by MilkyDeveloper** [comment]
I know about this issue. Please be patient, I'm solving it. It emerged from a destructive PR.

**Comment by nplawes** [comment]
Thanks for the prompt response... glad to hear that the issue has been identified... I thought I'd broken something :-) I tried using an older bzImage (to no avail) as it was suggested that might be the issue.

**Comment by lajca** [comment]
Thanks for the update. Just adding info. Same issue on an HP Chromebook 14:

## Chromebook Model
HP Chromebook Model 14a-na0010ca
Prod ID: 9VU02UA

## Board Model
BLOOGLET C2E-A4D-B2K-X3R-M3A-A6P

### Background/ frivolous personal colour

This is very exciting. My son's been living with ChromeOS for a couple of years, and as cool as it is, all too often I'm butting heads with the OS just not doing something. Not _can't_, but *won't* and it's maddening. Also, Minecraft wouldn't work past 1.16 on ChromeOS(LinuxVM) for no obvious reasons, so the whole family hasn't migrated. Then it just stopped working entirely. _sigh_

Anyways, he's looking forward to this. :)

**Comment by energy-x** [comment]
> I know about this issue. Please be patient, I'm solving it. It emerged from a destructive PR.

I thought I was losing my mind, or maybe my Acer CB317 (MAGPIE) wasn't supported for some reason. Thanks for the work on this!

**Comment by MilkyDeveloper** [comment]
Fixed, run `sudo rm -rf ~/linux-build; bash updatekernel.sh` on the PC you built Breath with.

**Comment by nplawes** [comment]
Many thanks, it just worked a treat! I did clean install as I'd been fiddling with the checked out version.

Now to install it to the SSD... Seems much simpler than the flashing that was required for GalliumOS. Loving it so far!

Perhaps when I understand how it's put together I may be able to find some way to contribute to the project (as a retired unix admin / developer)

**Comment by ThePizzaTimeBandit** [comment]
Thanks as well.  I am confirming now that I was able to install Ubuntu and Debian.
