### ISSUE TITLE
Black screen - not booting on HP 11 G6 EE

### ISSUE THREAD

**Issue by c25** [cb-linux/breath#301]
I see someone else has this device working, but with a different model number

I've tried Ubuntu and Debian, MicroSD via two different USB and directly into the slot.

Sequence is:
* Turn on
* `ctrl`+`u`
* screen goes black
* nothing happens (even if left for hours)

**Device**: HP Chromebook 11 G6 EE
**Model**: SNAPPY E23-B4B-L4Y-O3Z-N3Q-A2V

**Comment by energy-x** [comment]
Try just a USB drive (no MicroSD). I have an Acer CB317 that refuses to boot from MicroSD with just a flashing cursor, but will start right up with a USB drive (Flash or SATA SSD with USB 3.x adapter).

**Comment by MilkyDeveloper** [comment]
This issue has been fixed in the latest commits.
