### ISSUE TITLE
HP Chromebook 11 G6 EE Celeron - no sound

### ISSUE THREAD

**Issue by c25** [cb-linux/breath#306]
I see others have got sound working on the *lake version of this chromebook, but mine has a celeron processor.

Running `sof-setup-audio` and `SOUNDCARD=rtk sof-setup-audio` doesn't appear to make sound work.

[alsa-info.txt](https://github.com/cb-linux/breath/files/9332416/alsa-info.txt)

**Device**: HP Chromebook 11 G6 EE
**Model**: SNAPPY E23-B4B-L4Y-O3Z-N3Q-A2V

**Comment by MilkyDeveloper** [comment]
This is an ApolloLake device.
