### ISSUE TITLE
apl-sof-setup-audio doesn't run on debian 11

### ISSUE THREAD

**Issue by c25** [cb-linux/breath#308]
**EDIT**: I don't know where I should run this script. It seems like it should be on the chromebook, but it mentions USB drives etc.

Running the command (running breath on my chromebook) results in:

```bash
Error: 'restricted' invalid
```

Removing / commening line 8 allows it to run.

I don't know if this is required on other distros (ubuntu?)

**Comment by c25** [comment]
It also fails on line 80

```bash
cd: /home/username/linux-build: No such file or directory
```

this seems to work

```bash
if [ ! -d ~/linux-build ]
then
  mkdir ~/linux-build
fi
cd ~/linux-build
```

**Comment by c25** [comment]
Script completed and said to reboot.
Not it won't boot.

Is this something to do with depthcharge that I saw mentioned in the script?
There is no infor/warning on the installation page about this step!
https://cb-linux.github.io/breath/docs.html#/?id=audio

ps: I really appreciate your patience with me struggling through this as someone completely new to chromebooks and this ecosystem.
I'm hoping I can contribute back to the documentation - once I have something working correctly - to make it easier for anyone else like me!

**Comment by c25** [comment]
OK

I did a complete new build, using latest commits.
this time `apl-sof-setup-audio` did run, and everything rebooted ok!

I think it's ok to close this issue now...

**however** I will observe that I don't have audio working.
I think this is because I'm trying to use gnome, and #122 suggests that I should remove pulseaudio - but when attempting that apt tells me it will also remove gnome.

Attempting `apt remove pipewire*` ALSO says it will remove gnome.

I've just built with KDE - but that doesn't show a login screen so I can't confirm (yet) if it's specific to the combination of gnome+debian

**Comment by MilkyDeveloper** [comment]
PipeWire is already masked, so there’s no need to remove it. Give me the link/file created by `sudo alsa-info` if you don’t mind.

**Comment by c25** [comment]
[alsa-info.txt](https://github.com/cb-linux/breath/files/9348941/alsa-info.txt)

**Comment by MilkyDeveloper** [comment]
Looks like this is our culprit:
```
PipeWire:
      Installed - Yes (/usr/bin/pipewire)
      Running - Yes
```

I've seen this happen a few times, installing a desktop "unmasks" Pipewire. To fix this, just run
```
systemctl mask --user pipewire.{socket,service}
```

**Comment by c25** [comment]
Maybe this is a new issue now, but that has only half helped!

Pipewire is no longer running, but I still have no audio output options in Gnome.
Running `speaker-test` fails.
Running `sudo speaker-test` works

I've tried adding my user to the `audio` group, but that doesn't seem to make any difference.

**Comment by MilkyDeveloper** [comment]
Redownload https://github.com/cb-linux/breath/blob/main/bin/sof-setup-audio and run it again. This should fix it :D

If this project works well for you, feel free to [donate](https://opencollective.com/breath) or give it a star.

**Comment by c25** [comment]
I thought this device used the apl-sof-setup-audio?
I see your changes, but don't want to end up twisting my configuration into an even bigger mess running the wrong script :grin:

**Comment by MilkyDeveloper** [comment]
Once done with its work of changing the kernel commandline and downloading firmware, `apl-sof-setup-audio` invokes `sof-setup-audio`, so there should be no problems.

Also, your audio configuration isn't a mess, it's all documented. We almost have it working :D.

**Comment by c25** [comment]
Right, multiple rebuilds later and I've reached "good enough".

Audio works, but not always, well, eventually.

When first booting up, no audio shows up in gnome, and there is no sound.
Running `speaker-test` sometimes works at this point, but not always.
Some time later (I haven't identified the exact delay or cause) audio will start working.
Sometimes I need to change between the two identically named audio devices.

Thanks for taking the time to work this through with me!
