### ISSUE TITLE
Can't expand USB image to use available space

### ISSUE THREAD

**Issue by d0od88** [cb-linux/breath#312]
I re-created a Breath IMG (Ubuntu LTS, GNOME) and flashed it, but on all devices I flash it to I'm left unable to run the 'expand' script to make use of the remaining disk space on the USB (or SD card, I tried it on one of those too).

They all throw the same error:

<img width="686" alt="Screenshot 2022-08-16 at 16 23 25" src="https://user-images.githubusercontent.com/869982/184917801-1bed3413-7e48-480c-b298-0ae3ce30ae9d.png">

As well as being unable to run the expander script from the same machine I installed Breath from I'm also unable to create a partition (of any format) out of the remaining free space. Or resize the breath partition. The only way to make the remaining space usable is to re-format the entire USB. Otherwise, it's just sat there "free" but unable to be changed.

<img width="976" alt="Screenshot 2022-08-16 at 16 25 52" src="https://user-images.githubusercontent.com/869982/184919288-a800c2a6-0677-4a75-8b7e-964f114bad8a.png">

I've reformatted and refreshed the USB about 18 times, including onto different devices, and the same issue occurs. 

Breath itself runs fine, it's just the partition(s) that can't be resized 💁🏻‍♂️

**Comment by MilkyDeveloper** [comment]
Looks like you omitted the `/dev` in `/dev/sdb` when queried about your USB device in expand.sh :D. I'll add some code that validates this.

GNOME Disks is unable to expand the partition because the bootloader that Chromebooks have, Depthcharge, requires a modified GPT layout to work.

**Comment by d0od88** [comment]
> Looks like you omitted the `/dev` in `/dev/sdb` when queried about your USB device in expand.sh :D. I'll add some code that validates this.

Doh! I feel so stupid. That's exactly the issue… 🙈 I'm off to hide…

**Comment by d0od88** [comment]
> Looks like you omitted the `/dev` in `/dev/sdb` when queried about your USB device in expand.sh :D. I'll add some code that validates this.

Doh! I feel so stupid. That's exactly the issue… 🙈 I'm off to hide…
