### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Apacelus** [cb-linux/breath#319]
Is this project dead?

**Comment by MilkyDeveloper** [comment]
What do you mean? No. Of course not. This project is poggers! I had to go potty, sorry for the wait. Could I recommend you to an alternative project, though? While we stabilize this ecosystem, you could go to https://eupnea-linux.github.io. Great day, and I wish you a merry Christmas and a multitude of opportunities to have seggs.

**Comment by MilkyDeveloper** [comment]
Closed by #302
