### ISSUE TITLE
Is there a way to install to a microSD card? 

### ISSUE THREAD

**Issue by FaberfoX** [cb-linux/breath#32]
I've just got a Lenovo Flex 5i (Code name: lillipup, Base board: volteer) and easily created a (beautifully) working Ubuntu install on a 32GB USB drive. Then, I dd'ed that to a same sized micro SD card, but that doesn't boot from the Developer Mode screen, and my guess is that it won't ever boot from the internal card reader, as it's mapped to /dev/mmcblk0 and not to /dev/sdX
Then, I used the MrChromebox script to update the RW_LEGACY payload, but, as expected, Tianocore doesn't boot it as there's no UEFI partition. 
So, is there anyway to get Breath working from the internal card reader?

Also, I've just found about the install-to-internal-storage script but I figure that it wipes the chromeos install, that I'd like to keep. My SSD is 128GB, would it be possible to shrink the main chromeos partition (seen as /dev/nvme0n1p1, 111.1G out of 119.2G total) and tweak the script to install to new partitions? How would I go about booting it as the Dev Mode screen only offers to boot from internal or external disks?
![image](https://user-images.githubusercontent.com/6801510/148629723-b48e8fb3-b5a0-41f5-8ac3-5a31aa70bd40.png)

**Comment by sgulino** [comment]
Have you tried installing directly to the SD card, rather than dd'ing from a previous install? I'm successfully booting from MicroSD on my Nami CB. 

Also, are you sure your SD card is mounted to mmcblk0? That should be the eMMC storage.

**Comment by MilkyDeveloper** [comment]
Actually, the `install-to-internal-storage` script can use any block device (USB, cd-rom, SD Card, etc.) as the output. You could also just directly build Breath to an SD Card instead of putting it to an SD Card, there's no difference the install to internal storage script makes.
