### ISSUE TITLE
Hearphone jack sound not working in [LARS] Chromebook 14 For Work

### ISSUE THREAD

**Issue by elKawai628** [cb-linux/breath#323]
i already did the funni `setup-audio` and the internal sound works.
The problem here is when i try to connect a headphone jack 
my laptop or the system i selected just dont recognize it
someone can send some help? 

im in Ubuntu 22.04 with the kde desktop

**Comment by MilkyDeveloper** [comment]
You 👉😰 silly, ⭕😛 silly 👻 goose. 🦆 This project 🔛 is, dare 👨‍👩‍👧‍👦👪🎨 I 👁️ say, 🛐 DEAD! 🩸🖤🦵 I 😀 redirect you 👈 to the so-called 👐 "Eupnea" project. 🔛

**Comment by elKawai628** [comment]
lmao :skull: i :duck: already :+1: 
have :100: that :smiling_face_with_three_hearts:
