### ISSUE TITLE
Blank screen on Lenovo Gaming Chromebook 16 "Taniks" (Alder Lake)

### ISSUE THREAD

**Issue by a-tringali** [cb-linux/breath#324]
Built the USB according to the instructions, but I get a blank screen when I try booting from USB. Tried rebuilding the image, flashing with different programs (ChromeOS recovery, etcher), tried different USB sticks, without any luck.

Any ideas on why it could be hanging?

**Comment by YeesterPlus** [comment]
it is 0( issue: https://github.com/cb-linux/breath/issues/325 )

**Comment by a-tringali** [comment]
I don't own this computer anymore. Godspeed to whoever tries to make this work.
