### ISSUE TITLE
HP Chromebook 11 G5 webcam issue

### ISSUE THREAD

**Issue by Fsu9** [cb-linux/breath#49]
The built-in webcam doesn't seem to be recognized automatically.  (There is no /dev/video*)

**Comment by Fsu9** [comment]
It looks like maybe it's as simple as installing more kernel modules.  Maybe I will fix it myself one of these days.

**Comment by Fsu9** [comment]
Looks like I need kernel module ``uvcvideo`` loaded to make the webcam work.
``sudo modprobe uvcvideo`` works but gives an error message (a dependency isn't where it expects it)
I couldn't figure out where uvcvideo actually was.  Not in the ``/lib/modules/5.10.88`` directory or subdirectories.  Same thing with the dependency (``videobuf2-vmalloc``).  ``modprobe`` knows somehow.  But the modules can't find their dependencies.

It looks like the whole directory ``/lib/modules/5.10.88/kernel/drivers/media`` is missing on my laptop, but it is present in the ``modules.tar.xz`` from the latest Breath release.  When I copied them over and loaded ``uvcvideo``, the webcam worked.

**Comment by MilkyDeveloper** [comment]
Should be fixed in the latest release. It also autoloads with the latest commit.
