### ISSUE TITLE
Build to local disk first, flash USB afterwards

### ISSUE THREAD

**Issue by korbendallaskoop** [cb-linux/breath#50]
Awesome project, thanks a lot, hoping to get a gemini lake CB up and running with it soon. First attempts gave various errors and a lot of USB drive punishing. Next try will be from crostini.

Can you suggest a method to write to local disk first, before creating an .iso and flashing the USB disk? Or would that break thinks? 

Not sure how to interpret the waitForUSB function:
https://github.com/MilkyDeveloper/cb-linux/blob/d67b7388931cde1084c055cb4ea5ffdda0d8666f/setup.sh#L53-L54
https://github.com/MilkyDeveloper/cb-linux/blob/39255612d4e4221675b024e9a09f9b420fabb147/utils/functions.sh#L37-L42
-but reckon there might be ways to mount a fake block device of sorts if needed.

*10 minutes after edit, found the https://milkydeveloper.github.io/cb-linux/docs.html#/kernel note, seems to be a workaround if I understand it correctly.

**Comment by MilkyDeveloper** [comment]
This already does directly write to a USB. It doesn't work within Crostini since you can't write to certain ext4 USBs.

**Comment by korbendallaskoop** [comment]
Thanks for the quick reply - pardon my limited grasp of the code. What I am looking for is a way to write to local disk, ie. the same as the OS hosting the script and build process, and afterwards flash a USB disk with the req. filesystem and structure. 

If kept inside setup.sh an option that allows a local folder instead of a USB lsblk device or separates build from USB prep and write.

Alternatively, instructions on how to manually complete the build and merge the compiled https://milkydeveloper.github.io/cb-linux/docs.html#/kernel.

**Comment by daffy1234** [comment]
What I did was to create a file of the appropriate size on disk (using `fallocate -l [size]G breath.img`), mount it as a loopback device (`losetup -f --show breath.img`) and use `/dev/loop0` (or whatever the previous command outputs) in place of the flash drive's name. You'll have to modify a few hard coded things in setup.sh (everywhere it says `${USB}1` or `${USB}2` change to `${USB}p1` and `${USB}p2` respectively). Then after this you can simply dd the image to the flash drive.

It's hacky and not perfect but works. If I were to put more time into it, I would modify setup.sh to handle this for me, as well as writing it to the flash drive and then expanding the second partition once written.

**Comment by MilkyDeveloper** [comment]
I incorporated @daffy1234's changes into the script. Now, the script should build an IMG file by default. The docs have also been updated.
