### ISSUE TITLE
Debian 11 - WiFi adaptor not found

### ISSUE THREAD

**Issue by avram-meir** [cb-linux/breath#57]
Command used to build bootable usb: `bash setup.sh gnome debian`
Chromebook model: ASUS C425 (LEONA)

I booted into Debian and it was beautiful, but when I tried to open WiFi settings, it was grayed out with "No WiFi Adapter Found". I installed iwlwifi by copying the deb directly to the USB Debian's /home/[user]/Downloads folder in ChromeOS and installed with dpkg, but no dice.

**Comment by MilkyDeveloper** [comment]
Post the output of `dmesg` on your chromebook in Debian.

**Comment by avram-meir** [comment]
Here it is!
[dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/8027757/dmesg.txt)

**Comment by MilkyDeveloper** [comment]
Try running `modprobe iwlmvm`.

**Comment by avram-meir** [comment]
That worked! Thank you so much.

**Comment by avram-meir** [comment]
I found that this needs to be set every time after reboot.

**Comment by MilkyDeveloper** [comment]
Note to self: implement this autoloading

**Comment by KSPAtlas** [comment]
I also get this issue on Debian and iwlmvm doesnt help, even though according to the specs it has an Intel WiFi adapter

**Comment by KSPAtlas** [comment]
The WiFi module seems to be supported by iwlwifi

**Comment by MilkyDeveloper** [comment]
There’s other iwl7000 drivers iirc. What is your Wi-Fi card?

**Comment by KSPAtlas** [comment]
> There’s other iwl7000 drivers iirc. What is your Wi-Fi card?

Intel Dual Band Wireless-AC 7265 802.11a/b/g/n/ac (2x2) WiFi and Bluetooth 4.2 Combo, non-vPro

**Comment by KSPAtlas** [comment]
Also, bit unrelated, but the graphics is still.running via llvmpipe
