### ISSUE TITLE
Audio for reef still doesn't work

### ISSUE THREAD

**Issue by jz5020** [cb-linux/breath#6]
While I don't really know much about how audio works on Linux, after following the commands to get audio working on the reef Chromebook, I still haven't been able to get any sound output working on my installation of Ubuntu with KDE. At first, the first error that I had encountered was that the `setup-audio` script had been trying to pull the ChromeOS files off of `/dev/mmcblk0p3` while on my Chromebook, the internal storage had always been mounted at `/dev/mmcblk1`. After modifying the script to account for this, the script completes without any further error, but upon a reboot of the system, after installing `kmix`, I still only get an output labeled "default and only sink". I've also tried running firefox with `apulse firefox`, where I had gotten errors such as `can't open playback device "default". Error code -2 (No such file or directory)` and `ALSA lib confmisc.c:767:(parse_card) cannot find card '0'`. Another thing that I had tried was to execute the commands set out in `alsa-reload.service` manually, where I was met with
`ALSA lib parser.c:1934:(get_by_card_name) no soundcards found...
ALSA lib main.c:412:(execute_sequence) unable to open ctl device 'hw:bxtda7219max'
ALSA lib main.c:1971:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such device`
after running `alsaucm -c bxtda7219max set _verb HiFi set _enadev Speaker`
Any help on this matter would be appreciated.

**Comment by MilkyDeveloper** [comment]
Could you post the output of `dmesg`?

**Comment by jz5020** [comment]
Alright, [dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7748714/dmesg.txt)

**Comment by QL100100** [comment]
Mine doesn't work either
I don't know what to do
The three commands on the website all failed

**Comment by MilkyDeveloper** [comment]
Try running `sof-setup-audio` within Breath. I have a feeling it'll work :D

**Comment by jz5020** [comment]
While I am really grateful for your efforts towards getting many other Chromebooks that otherwise wouldn't have been able to run Linux, it appears that running `sof-setup-audio` still does not fix the audio issues that I have been experiencing on my Acer Spin 11.
While running Firefox, the errors that I face after pulling up a YouTube video are:

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dmix
[apulse] [error] do_connect_pcm: can't open playback device "default". Error code -2 (No such file or directory)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
[Child 1974, MediaDecoderStateMachine #1] WARNING: 7fed0dcd82f0 OpenCubeb() failed to init cubeb: file /build/firefox-ahszPM/firefox-95.0.1+build2/dom/media/AudioStream.cpp:324
[Child 1974, MediaDecoderStateMachine #1] WARNING: Decoder=7fed135d9100 [OnMediaSinkAudioError]: file /build/firefox-ahszPM/firefox-95.0.1+build2/dom/media/MediaDecoderStateMachine.cpp:4007
ATTENTION: default value of option mesa_glthread overridden by environment.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM dmix
[apulse] [error] do_connect_pcm: can't open playback device "default". Error code -2 (No such file or directory)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.

**Comment by MilkyDeveloper** [comment]
It appears there are no soundcards detected. Could I have the output of `dmesg`?

**Comment by jz5020** [comment]
Again, heres [dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7786915/dmesg.txt). Thank you so much for the effort that you've put into this project!

**Comment by MilkyDeveloper** [comment]
@RodBarnes try running `setup-audio`. Reboot and post the output of `sudo dmesg` and ‘sudo alsa-info’

**Comment by RodBarnes** [comment]
I ran `setup-audio` then ran `sudo dmesg | nc termbin.com 9999`.  The output can be seen [here](https://termbin.com/tgva).

**Comment by MilkyDeveloper** [comment]
This is the main error:
`
[    8.848546] snd_soc_skl 0000:00:0e.0: Direct firmware load for 5a98-reef-sand-8-tplg.bin failed with error -2
[    8.848567] snd_soc_skl 0000:00:0e.0: tplg fw 5a98-reef-sand-8-tplg.bin load failed with -2, trying alternative tplg name bxt_da7219_mx98357a-tplg.bin
[    8.848599] snd_soc_skl 0000:00:0e.0: Direct firmware load for bxt_da7219_mx98357a-tplg.bin failed with error -2
[    8.848602] snd_soc_skl 0000:00:0e.0: tplg bxt_da7219_mx98357a-tplg.bin failed with -2, falling back to dfw_sst.bin
[    8.848624] snd_soc_skl 0000:00:0e.0: Direct firmware load for dfw_sst.bin failed with error -2
[    8.848627] snd_soc_skl 0000:00:0e.0: Fallback tplg fw dfw_sst.bin load failed with -2
[    8.848633] snd_soc_skl 0000:00:0e.0: Failed to init topology!
`

What’s the output of `ls /lib/firmware`, `lsblk`, and `setup-audio; sync`? Looks like the fw still hasn’t been copied, which puzzles me.

**Comment by MilkyDeveloper** [comment]
The thing is, the specific kernel used in ChromeOS has specific patches and a special config file. I’m halfway through retrieving those.

**Comment by RodBarnes** [comment]
rod@ubuntu:~$ ls /lib/firmware | grep 5a98
5a98-reef-sand-8-tplg.bin

rod@ubuntu:~$ ls /lib/firmware | grep bxt_da7219
<nothing>

rod@ubuntu:~$ ls /lib/firmware | grep dfw_sst
<nothing>

Full output of `ls /lib/firmware` is [here](https://termbin.com/x7ye).

**Comment by RodBarnes** [comment]
Output of `ls /lib/firmware` is [here](https://termbin.com/x7ye).  Note that it lists `5a98-reef-sand-8-tplg.bin` but neither of the two backups (`bxt_da7219_mx98357a-tplg.bin` or `dfw_sst.bin`) are listed.

Output of 'lsblk' is [here](https://termbin.com/3ejv).

Output of `setup-audio; sync` is [here](https://termbin.com/woth).

**Comment by MilkyDeveloper** [comment]
Maybe copying `/lib/firmware/5a98-reef-sand-8-tplg.bin` to `/lib/firmware/intel/5a98-reef-sand-8-tplg.bin`.

**Comment by RodBarnes** [comment]
I did the copy, ran `setup-audio; sync` again, rebooted, and confirmed that `5a98-reef-sand-8-tplg.bin` as still in `/lib/firmware/intel`.  I then did `speaker-test` with the same result: `cannot find card '0'`.

**Comment by MilkyDeveloper** [comment]
I think I'm going the wrong direction here, it seems like SOF is the way to go. Could you run `sof-setup-audio` and `sudo alsa-info` (when it asks for a link, say "y" and share it).

**Comment by RodBarnes** [comment]
Ran `sof-setup-audio`, rebooted as it directed, then ran `sudo alsa-info`.  I did say 'Y' to upload but it didn't report a link but a path: `/tmp/alsa-info.txt.vS1ss5uoFf`.  That file does exist and I have made it available [here](https://termbin.com/52qs).

**Comment by MilkyDeveloper** [comment]
I'll be fixing this issue for all Apollo Lake Chromebooks soon. It looks like the key to solving this is [located in this thread](https://github.com/thesofproject/sof/issues/5361) over [here](https://github.com/thesofproject/sof/issues/5361#issuecomment-1048319805).

**Comment by MilkyDeveloper** [comment]
I added a new SOF script for Apollo Lake that might work. Run:
```
sudo wget https://raw.githubusercontent.com/cb-linux/breath/main/bin/apl-sof-setup-audio -O /usr/local/bin/apl-sof-setup-audio```
and then

```
sudo chmod +x /usr/local/bin/apl-sof-setup-audio
```
Then, just run `apl-sof-setup-audio` on your chromebook.

**Comment by RodBarnes** [comment]
I think the script has cr/lf in it?  I got ^M errors when I attempt to execute it.  I edited in nano and confirmed it as MS-DOS format.  I saved it as Mac format but it still won't execute, reporting:\
set: bad interpreter: No such file or directorybash`

**Comment by MilkyDeveloper** [comment]
I fixed the line ending issues and `dd`. Hopefully it should do fix it. Do the whole spiel again; run:
```
sudo wget https://raw.githubusercontent.com/cb-linux/breath/main/bin/apl-sof-setup-audio -O /usr/local/bin/apl-sof-setup-audio
```
and then

```
sudo chmod +x /usr/local/bin/apl-sof-setup-audio
```

Then, just run `apl-sof-setup-audio` on your chromebook.

**Comment by RodBarnes** [comment]
This time, it made it all the way through but I still got that initial error (details below).  other than that, no other errors appeared in the output and it otherwise went to completion.  However, after the reboot, I still have no output device showing under "Settings > Sound" and running `speaker-test` produced the same results; i.e., `cannot find card '0'`.

Error details: During the process, I still got that `dpkg-deb` error and immediately after it occurred, a dialog appeared prompting to generate a bug report.  I clicked "Yes" which took me to `bugs.launchpad.net`.  (I have not yet submitted it; I wasn't sure that was correct given we're doing dev testing here; let me know if you want me to proceed.)  The summary of the report is "package firmware-sof-signed 1.7-1 failed to install/upgrade: trying to overwrite '/lib/firmware/intel/sof/sof-bdw.ri', which is also in package linux-firmware 1.201.4"

**Comment by MilkyDeveloper** [comment]
The `dpkg-deb` error wasn't a failure. It's a bug in the Ubuntu SOF firmware packages. When that inevitably occurs, it runs another command which fixes it. Filing a bug report was a good idea.

Please post the output of `sudo alsa-info` and `dmesg` whenever I test like this.

**Comment by RodBarnes** [comment]
Repeated the test.
Output of `alp-sof-setup-audio` is [here](https://termbin.com/eon9).
Submitted the [but report](https://bugs.launchpad.net/ubuntu/+source/firmware-sof/+bug/1964278).
Output of `sudo alsa-info` is [here](https://termbin.com/5rig).
Output of `sudo dmesg` is [here](https://termbin.com/5flo3).

**Comment by MilkyDeveloper** [comment]
It seems the kernel command line isn't getting properly applied. What's the text of the file `kernel.flags` in `~/linux-build`? Could you run `bash -x apl-sof-setup-audio`?

**Comment by RodBarnes** [comment]
On the Chromebook,`~/linux-build/kernel.flags` contains: 
`console=tty1 root=/dev/sda2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1 loglevel=0 splash snd-intel-dspcfg.dsp_driver=3 snd_sof_pci.fw_path="intel/sof"`

Output of `bash -x apl-sof-setup-audio` is [here](https://termbin.com/7xiq).

**Comment by MilkyDeveloper** [comment]
Alright, last time, I promise. Run:
```
sudo wget https://raw.githubusercontent.com/cb-linux/breath/main/bin/apl-sof-setup-audio -O /usr/local/bin/apl-sof-setup-audio
```
and then

```
sudo chmod +x /usr/local/bin/apl-sof-setup-audio
```

Run `apl-sof-setup-audio` on your chromebook.

**Comment by RodBarnes** [comment]
Houston: WE HAVE LIFT-OFF!  System sounds are working; using `mpg123` was able to play an MP3.

I still don't see an output device under "Settings > Sound" so unable to [Test] or set "Balance", etc.  Maybe this is a Gnome thing?

BTW: You should have received a donation from me.  I greatly appreciate your efforts here; I do not mind doing this multiple times.

**Comment by MilkyDeveloper** [comment]
Huuuge thanks for the donation :D

I'll look into fixing the GNOME audio. GNOME uses PulseAudio, so it doesn't detect the minimal ALSA setup this project uses.

**Comment by RodBarnes** [comment]
Quick question:  Will these steps be necessary with future images?  Or is this going to be baked in?

**Comment by MilkyDeveloper** [comment]
For future images, users will need to run `apl-sof-setup-audio`. The reason I've isolated these into commands and not made these run by default is because there are multiple audio setups, some with SOF, some with SOF+Realtek, and others without SOF. For those without `reef`, `apl-sof-setup-audio` wouldn't work.

**Comment by RodBarnes** [comment]
Clarification: Maybe I am remembering incorrectly, but I am pretty sure that in my prior testing with the `apl-sof-setup-audio` script I executed the script without as my user.  Certainly, looking at the previous comments where it was successful, there is no indication of using `sudo`.

Plus, the [instructions](https://cb-linux.github.io/breath/docs.html#/) don't specify using `sudo`.

However, I noticed in the latest release that both `apl-sof-setup-audio` and `sof-setup-audio` are executable only for the `owner` and `group`.  Changing them to be executable for `other` I was successful with running and setting up the audio.  I assume this would also work if I ran it as `sudo`.

Maybe this was an oversight?  Or maybe by design?  I didn't want to just fork and make a change without checking on if this was intentional.

**Comment by Tykymba** [comment]
Omg, what about arch linux guys, is it possible to make sound work too?

**Comment by MilkyDeveloper** [comment]
You can adapt the `bash` so it has Arch support by using `pacman`. Feel free to open a PR.

**Comment by MilkyDeveloper** [comment]
@RodBarnes I've fixed this in the latest commit.

**Comment by RodBarnes** [comment]
Hmmm... I just pulled and they still show as this:

```
drwxr-xr-x  2 root root 4096 Mar 16 14:27 .
drwxr-xr-x 10 root root 4096 Mar  9 00:57 ..
-rwxr-xr--  1 root root 3563 Mar 16 14:27 apl-sof-setup-audio
-rwxr-xr--  1 root root 1568 Mar 16 14:27 install-to-internal-storage
-rwxr-xr--  1 root root 2573 Mar 16 14:27 setup-audio
-rwxr-xr--  1 root root 2004 Mar 16 14:27 sof-setup-audio
-rwxr-xr--  1 root root 2989 Mar 16 14:27 updatekernel-on-emmc
```

**Comment by RodBarnes** [comment]
A new issue?

I just did a clean and clone (deleted my repository, cloned again).  Then built and flashed the image.  When I run `apl-sof-setup-audio` it reports:

```
Setting up firmware-sof-signed (1.7-1) ...
Downloading the Apollo Lake SOF Topology...
lsblk: /dev/sda2s: not a block device
```

Here's the output of [lsblk](url):
```
sda            8:0    1 28.9G  0 disk 
├─sda1         8:1    1   64M  0 part 
└─sda2         8:2    1 11.9G  0 part /
sdb            8:16   1  1.9G  0 disk 
└─sdb1         8:17   1  1.9G  0 part /media/rod/TOOLS
```

**Comment by MilkyDeveloper** [comment]
I fixed the trailing s issue in the latest commit. Any extra info over the penguin screen? Maybe an image?

**Comment by RodBarnes** [comment]
I picked an earlier point (commit e26b1c) and built from there.  But it did the same thing.  I'll continue to work back to find a point where it is working again and attempt to identify what changed.  But here's a [screen shot](https://i.postimg.cc/bvzh7TBZ/20220317-150450.jpg).

**Comment by MilkyDeveloper** [comment]
Alright, so it's waiting for a root device, meaning the kernel parameter for the root device the script set is wrong. Are you running this off of the internal storage? I've yet to test that functionality.

**Comment by MilkyDeveloper** [comment]
What would also be useful for debugging this issue would be providing the output of `bash -x $(which apl-sof-setup-audio)`.

**Comment by RodBarnes** [comment]
So, it works fine on commit ccb22a4ed4accf73dd29fbde114b05370db8f069 "Dummy commit to fix line endings".  It may be notable that this is just prior to the docker-related changes.

**Comment by MilkyDeveloper** [comment]
As of the latest commit, the script should be operational again :D

**Comment by RodBarnes** [comment]
@MilkyDeveloper  Confirmed.  However, it still shows the penguin and a lot more stuff happening at boot now than it did before.  Could you explain what all the additional is?  When the sound was working before, it didn't show all of this.  Just would like to understand...

**Comment by MilkyDeveloper** [comment]
So, sound is working again now? The extra boot messages must be a kernel addition since I recently rebuilt the kernel with some extra modules. I find the logging to be useful for debugging.

**Comment by RodBarnes** [comment]
Yes, sound is working with your last change. The extra messages for debugging makes sense. Just unexpected and seems to take a little longer to boot. But that could be just me watching the messages scroll by. 😊

--
Rod Barnes

-------- Original Message --------
