### ISSUE TITLE
cli arch broken archive

### ISSUE THREAD

**Issue by DumbGameMaker** [cb-linux/breath#61]
When I try to install arch, the archive is broken.
log:
```
▄▄▄▄▄▄                                            ▄▄      
██▀▀▀▀██                                  ██      ██      
██    ██   ██▄████   ▄████▄    ▄█████▄  ███████   ██▄████▄
███████    ██▀      ██▄▄▄▄██   ▀ ▄▄▄██    ██      ██▀   ██
██    ██   ██       ██▀▀▀▀▀▀  ▄██▀▀▀██    ██      ██    ██
██▄▄▄▄██   ██       ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄   ██    ██
▀▀▀▀▀▀▀    ▀▀         ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀
┌──────────────────────┐
│Made by MilkyDeveloper│
└──────────────────────┘
What would you like your username to be? (no spaces, backslashes, or special characters)
base64
Installing Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
arch-install-scripts is already the newest version (23-1).
cgpt is already the newest version (0~R81-12871.B-1).
vboot-kernel-utils is already the newest version (0~R81-12871.B-1).
git is already the newest version (1:2.25.1-1ubuntu3.2).
wget is already the newest version (1.20.3-1ubuntu2).
wget set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 86 not upgraded.
kernel.flags        100%[===================>]     107  --.-KB/s    in 0s      

Which USB Drive or SD Card would you like to use (e.g. /dev/sda)? All data on the drive will be wiped!
sdb    Cruzer_Glide            usb
/dev/sdb
Ok, using /dev/sdb to install Linux
umount: /dev/sdb: not mounted.
umount: /dev/sdb1: not mounted.
umount: /mnt: not mounted.
umount: /media/*/*: no mount point specified.
Writing storage, may take more than 5 minutes.
Although it seems slow, consider this process like flashing an ISO to a USB Drive.
Below is an innacurate indicator of mB left to write. It may decrease hundreds of megabytes in seconds.
28.80MB
22240+0 records in
22240+0 records out
11386880 bytes (11 MB, 11 MiB) copied, 2.69064 s, 4.2 MB/s
mke2fs 1.45.5 (07-Jan-2020)
Creating filesystem with 31243776 4k blocks and 7815168 inodes
Filesystem UUID: 2dbd5bed-7abc-44be-8e45-3d72e1881406
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (131072 blocks): done
Writing superblocks and filesystem accounting information: done   

Writing storage, may take more than 5 minutes.
Although it seems slow, consider this process like flashing an ISO to a USB Drive.
Below is an innacurate indicator of mB left to write. It may decrease hundreds of megabytes in seconds.

umount: /mnt: not mounted.
umount: /mnt: not mounted.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

**Comment by DumbGameMaker** [comment]
in utils/bootstrap.sh, it tries to download `https://mirror.rackspace.com/archlinux/iso/2021.10.01/archlinux-bootstrap-2021.12.01-x86_64.tar.gz`, which doesn't exist. I'll change it to `https://mirror.rackspace.com/archlinux/iso/2021.12.01/archlinux-bootstrap-2021.12.01-x86_64.tar.gz` (which does exist), and submit a pr

**Comment by DumbGameMaker** [comment]
that did not seem to fix it (though probably would have been an issue in the future), maybe something else is causing it

**Comment by DumbGameMaker** [comment]
found it! the output of `futility vbutil_kernel --arch x86_64 --version 1 --keyblock /usr/share/vboot/devkeys/kernel.keyblock --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --bootloader kernel.flags --config kernel.flags --vmlinuz bzImage --pack bzImage.signed` is a tar archive... that is empty. file size of 0

**Comment by DumbGameMaker** [comment]
> in utils/bootstrap.sh, it tries to download `https://mirror.rackspace.com/archlinux/iso/2021.10.01/archlinux-bootstrap-2021.12.01-x86_64.tar.gz`, which doesn't exist. I'll change it to `https://mirror.rackspace.com/archlinux/iso/2021.12.01/archlinux-bootstrap-2021.12.01-x86_64.tar.gz` (which does exist), and submit a pr

seems like this was correct, to an extent. something must be overwriting this file

**Comment by DumbGameMaker** [comment]
i was able to fix it on my end by manually downloading it, i'm still stumped

**Comment by MilkyDeveloper** [comment]
Yeah, that's what I'm thinking too. Was just wondering: do you have a permanent link for an archlinux bootstrap file? I'll change the code to include it.

**Comment by DumbGameMaker** [comment]
> Yeah, that's what I'm thinking too. Was just wondering: do you have a permanent link for an archlinux bootstrap file? I'll change the code to include it.

pretty sure it's exactly the same as normal, but with 12 instead of 10

**Comment by MilkyDeveloper** [comment]
The latest version scrapes the rackspace page to get the latest Arch Bootstrap `tar` file, so this has been fixed.
