### ISSUE TITLE
Error when installing to internal storage

### ISSUE THREAD

**Issue by supergamer9787** [cb-linux/breath#64]
There is an error when trying to install to internal storage it says

FATAL: do_vbutil_kernel: Error reading config file.

Please help

**Comment by supergamer9787** [comment]
Ok so i installed curl it appears that error went away but not it errors saying

/dev/fd/63: line 1: 404:: command not found 

Im using debian with xfce if that helps

**Comment by MilkyDeveloper** [comment]
Are you running this on a Linux PC? I’ve never seen file descriptor errors occur. I think your setup might be broken.

**Comment by supergamer9787** [comment]
Thanks for the reply im running it on the breath linux usb and running your install script to my internal storage and it writes to storage for a bit then when its done writing it shows that error and exits

**Comment by MilkyDeveloper** [comment]
Are you sure you put the correct block device (`install-to-internal-storage [BLOCK DEVICE HERE]`)? Post the output of `lsblk`

**Comment by supergamer9787** [comment]
![20220216_220705](https://user-images.githubusercontent.com/99846089/154397209-7881b5e4-3ea5-43e1-8fe6-70bfbf42aaf9.jpg)

**Comment by MilkyDeveloper** [comment]
That's expected. You should try rebooting and running the command: `install-to-internal-storage /dev/mmcblk0`

**Comment by supergamer9787** [comment]
![20220216_222100](https://user-images.githubusercontent.com/99846089/154398594-ba7ee1d9-5bf3-419f-9a27-bd1ac4ab8e4e.jpg)

**Comment by MilkyDeveloper** [comment]
All this time it wasn't your fault. Thanks for helping me debug this! I fixed it in the latest commit. Just run:
```
sudo wget https://raw.githubusercontent.com/cb-linux/breath/main/bin/install-to-internal-storage -O /usr/local/bin/install-to-internal-storage
```
and then

```
sudo chmod +x /usr/local/bin/install-to-internal-storage
```

**Comment by supergamer9787** [comment]
It works now thank you very much and i wish you the best of luck with future development of this project and hope you get help as what you made is amasing and gave new life for my chromebook!

**Comment by ph1-xyz** [comment]
It seems I had a similar issue with _/dev/fd/63_ while installing Ubuntu on an Acer Chromebook Spin 514

the _install-to-internal-storage_ restituted a warning:

`dev/fd/63: line 1: echo: write error: No space left on device`

**Comment by ph1-xyz** [comment]
No luck :-/

![IMG_20220222_141153](https://user-images.githubusercontent.com/6156113/155139216-0ee06443-2efb-44f4-96e2-79afe3b5ac73.jpg)

**Comment by MilkyDeveloper** [comment]
Well - maybe your storage is full, as the error suggests.

**Comment by ph1-xyz** [comment]
> Well - maybe your storage is full, as the error suggests.

Sorry, surely PEBCAK.

Is there a chat where to ask for advices?
