### ISSUE TITLE
Ubuntu 20.04 repositories do not contain 'firmware-sof-signed' nor 'firmware-sof'

### ISSUE THREAD

**Issue by aghebert** [cb-linux/breath#65]
This prevents the `sof-setup-audio` script from finishing since it can't find and install it.

I managed to get around this issue by manually installing it from here: [https://launchpad.net/ubuntu/jammy/+package/firmware-sof-signed](https://launchpad.net/ubuntu/jammy/+package/firmware-sof-signed)

Then I just commented out this piece of the script;
```bash
sudo apt install -y firmware-sof-signed || sudo apt-get -o Dpkg::Options::="--force-overwrite" install firmware-sof-signed
```
The script completed after that.

**Comment by MilkyDeveloper** [comment]
Ubuntu 20.04 repos are to old to contain `sof` firmware, which is why I set the default version to 21.04. I can implement this feature, but I don't think anyone is affected by using Ubuntu 21.04 instead of Ubuntu 20.04. This could create a mini dependency hell.
