### ISSUE TITLE
Bricked my USB :-(

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#70]
After the previous attempt (where the 4GB USB wasn't large enough and the process abended) I went to a 32GB USB and made a second attempt.  For whatever reason, this process went way, way slower than the previous one -- or, at least it appeared to me that way.  I left it running for several hours to let it continue.

When I came back, I found it was hung at the point where I left it.  So, I killed the process.  I rebooted my system and after restarting, inserted the 32GB USB.  It couldn't be read by the OS -- it had two partitions on it -- a ChromeOS kernel and an Ubuntu.

But, I went ahead and tried the process again.  This time it reach the point where I entered the USB path again and then it failed saying the USB already had two partitions and it couldn't change them, so reboot and try again. :-(

I tried to use sfdisk --delete to wipe it.  It took a while then finally came back but the USB was still not useable

I then tried GPARTED to wipe it and create a new partition.  It was hung creating the partition. :-(

Not sure what to try next.  Not sure if it is worth another attempt down this path.  I only have so many USB drives...

**Comment by MilkyDeveloper** [comment]
Not sure what to say... I haven't had any other users reporting this with their USBs. You want the USB to be USB 3.0 or 3.1 optimally. Make sure your USB Card Reader/port is adequate too. Either way, this program uses `parted` for partitioning USBs, so its nothing I can really _fix_ for this issue. What's your USB model/name? If you remember what did it hang on?

**Comment by RodBarnes** [comment]
It is a 3.1 USB device. It has worked faithfully and I've used it for a while without issue.

The place that the script hung was in the middle of unpacking things. I was going very, very slowly. It took over six hours to go from 5% to just 15%. I can't say whether it was progressively getting slower or just going slowly; I got tired of sitting around and watching it.

As noted previously, this last attempt was made after booting a fresh image of Ubuntu 21.10. I wanted to avoid the issue I ran into in the first run where the script complained of "files already being in /mnt". So I just chose to start from a clean image. But, by then, the USB was hosed and it didn't like it at all.

I've tried everything I can think of to review the USB -- gparted, sfdisk, dd, and I'm out of ideas. Even took it to my Windows system and tried there but it pukes there, too.

In all the years I've been using USBs -- and that is a lot of USBs over a lot of years -- I've never had one get bricked, despite having read about this happening to others.

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
Try formatting it with Rufus on Windows. Also, just as a reminder, please don't assume that I am liable for any damages caused - you can see the code of the script itself in `utils/partition.sh`.

**Comment by RodBarnes** [comment]
Lol. Not assuming you're libel for anything. Nobody forced me to do this. Just really disappointed and now wary. I'll look at the script. I'll then decide whether to proceed.

Should this take a really long time and be slow? I'm running this on a small system so I'm not expecting it to be lightening. But six hours for a few percent of progress? Would you expect this to take al an entire day?

--
Rod Barnes

-------- Original Message --------

**Comment by MilkyDeveloper** [comment]
Lots of people are dissapointed with ChromeOS and its flexibility. Unfortunately, many people take that out on open source maintainers. I believe they deserve that dissapointentment. But Google should 100% take responsibility for running a UEFI bootloader with all drivers working, not OSS maintainers.

My builds, an others on similar threads, have some pretty short build times. Mine gets completed on a laptop i5 (8300H) in 3 hours. What are your specs?

**Comment by RodBarnes** [comment]
That's informative, thanks. This is a NUC with a Celeron J3455. Checking the benchmarks your 8300H comes out at 7542 vs 2224 for mine.

That's about what I'd expect and I wasn't expecting it to be done quickly. If yours takes about 3hrs then mine should take at least 2-3 times that.

So, maybe I'll give it another try when I have a more powerful Linux system available. All my other systems are designated for other purposes at the moment.

Got any tips on how to revive a USB? This is really weird. It isn't like the systems see the drive and then say, "Sorry, can't read that" or something. Any attempt to access it causes the system to freeze because it doesn't know what to make of it. When I then remove it, the system goes back to normal. Really strange...

--
Rod Barnes

-------- Original Message --------

**Comment by MilkyDeveloper** [comment]
I'm not sure how to revive the USB, I'm not great at kernel hardware support. I mainly focus on the "software" part of this project rather than the drivers, which I work with the ChromeOS kernel to supply. This is a very rare situation - your Celeron must have completely ceased to write storage when it hanged. Your USB must already have tons of writes. Consider it like flashing an ISO 5 times. A word of advice - when a situation like this happens and it hangs, I'd take the USB itself out. I can assure you its not a virus. A Celeron definetely won't work well for this project; the amount of time taken for lower CPUs is logarithmically lower rather than linearly. I would at least use an old, laptop i3.

**Comment by RodBarnes** [comment]
Actually, this USB is nearly new. It's the one I purchased most recently. :-)

But, in any case, I'll set this aside. I hope this project is successful for you.

--
Rod Barnes

-------- Original Message --------

**Comment by RodBarnes** [comment]
Just another suggestion (I'm giving this another try): It would be helpful if the script output the commands it was running or some text indicating where in the process it as in the script. The displayed output appears to all come from the executed commands.

For example, in partition.sh when it executes

> # Add a root partition
>
> sudo parted -s -a optimal $USB unit mib mkpart Root 65 100%

It could output a line "Adding root partition..." or something similar. I just think it would be helpful in troubleshooting and determining whether the process has hung, died, etc.

Right now, my script is sitting at

> Writing storage, may take more than 5 minutes.
> Although it seems slow, consider this process like flashing an ISO to a USB Drive.
> Below is an innacurate indicator of mB left to write. It may decrease hundreds of megabytes in seconds.
>
> 22256+0 records in
> 22256+0 records out
> 11395072 bytes (11 MB, 11 MiB) copied, 151.145 s, 75.4 kB/s
> mke2fs 1.46.3 (27-Jul-2021)
> Creating filesystem with 3899392 4k blocks and 976752 inodes
> Filesystem UUID: 2aca9e1d-6280-4c76-ae1f-d25a46a41b3e
> Superblock backups stored on blocks:
> 32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208
>
> Allocating group tables: done
> Writing inode tables: done
> Creating journal (16384 blocks): doneWriting superblocks and filesystem accounting information:

And has been sitting there for over an hour. Without being very familiar with the commands being executed, I don't know in what part of the script it is sitting.

This time, I'm using a new 16GB USB drive so maybe it is taking a while due to the size it has to partition?

--
Rod Barnes

------- Original Message -------

**Comment by RodBarnes** [comment]
Oh, and I should tell you this is being done on a different, more power system. :-)

--
Rod Barnes

------- Original Message -------

**Comment by RodBarnes** [comment]
Hmmm.... Based upon searching for "Writing superblocks and filesystem accounting information", it appears it is in the following point in the script:

> # Format the root partition as ext4 and mount it to /mnt
> yes | sudo mkfs.ext4 ${USB}2
> syncStorage
> sudo umount $MNT || sudo umount -lf $MNT || true
> sudo rm -rf ${MNT}/*
> sudo mount ${USB}2 $MNT

I would not expect this to take that long? But I'm no expert with mkfs...

--
Rod Barnes

------- Original Message -------

**Comment by RodBarnes** [comment]
After two hours, I finally killed the process. Restarting and then checking the USB it has a 64MB partition and a 14GB partition on it, both showing "Type Unknown". At least this one wasn't bricked.

I really want to try this out on my Chromebook. But I'm not having great success...

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
Seems like this project is pretty problematic on your configuration. Just out of curiosity: Are you running some kind of barebones distro such as Arch, or something mainstream like Ubuntu/Debian? As for the USB: I think you could just format it within your desktop. You probably already have a ton of data on that drive, so that would complete quicker.

**Comment by RodBarnes** [comment]
This system is running Ubuntu 21.10. I purposely but this system to be the same OS/release as the which is being built, trying to eliminate issues.

I can format the USB under Windows or under Ubuntu as a normal drive. But that isn't how it is used by this script, right? It has to be two partitions, a 64MB and the balance as another, right?

I'm thinking about going through this manually step-by-step and see if I can figure out what is happening.

--
Rod Barnes

-------- Original Message --------

**Comment by MilkyDeveloper** [comment]
Just format it as a completely blank, normal drive that you can put files in. No extra partitions needed. The drive will be formatted again by Breath anyways.

**Comment by RodBarnes** [comment]
Already confirmed I could format it; that's how I knew it wasn't bricked. I just want to avoid having it sit for two hours again and get no where.

--
Rod Barnes

-------- Original Message --------

**Comment by MilkyDeveloper** [comment]
I'm clueless over why your setup isn't working. It seems like your system can't write data fast enough - or something similar. Maybe you could try running `mkfs.ext4 /dev/myusbhere; sync`  to isolate if that's the issue?

**Comment by RodBarnes** [comment]
I'm still digging into this...

I wonder about this statement:

> You can replaceubuntuwitharch(you can only usecli) ordebian(all desktops are supported)

Does that mean that all desktops are supported ONLY on debian? I ask because I have been using this command:

> bash setup.sh lxqt ubuntu impish-21.10

Wondering if the combination of arguments I'm using might be a factor.

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
`bash setup.sh lxqt ubuntu impish-21.10` has no problem. I haven't tested `impish-21.10`. Although it probably makes no difference, why not just try running `bash setup.sh lxqt ubuntu`. For the desktop environments, I was trying to imply that you can use Debian or Ubuntu (both with all desktops supported) or Arch (only CLI).

**Comment by RodBarnes** [comment]
Every time I run this, it gets to a different point in the process and then hangs. It isn't just slow, it is sitting there. It is like a timing thing or I don't know...

Seeing how the function 'syncStorage' works, I have been looking at the contents and it is sitting in this while loop waiting for Dirty of /proc/meminfo to go to less than 5000 before continuing.

I see my Dirty value decrease a little, a little more, then go larger, then decrease a little -- repeat, repeat. But still sitting around 935MB or so.

Ideas? Is there something you can think of I could check?

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
Hmmm... looks like that's the culprit. Go in the `utils/functions.sh` file and replace:
```
  sync & {
    # If the unsynced data (in kB) is greater than 50MB, then show the sync progress
    while [[ $(grep -e Dirty: /proc/meminfo | grep --color=never -o '[0-9]\+') -gt 5000 ]]; do
      SYNC_MB=$(grep -e Dirty: /proc/meminfo | grep --color=never -o '[0-9]\+' | awk '{$1/=1024;printf "%.2fMB\n",$1}')
      echo -en "\r${SYNC_MB}"
      sleep 1
    done
  }
```
with
```
sync
```

**Comment by RodBarnes** [comment]
I've been reading through the docs again and wondering if I've misunderstood what I will end up with. Here's my understanding:

- Breath replaces the ChromeOS (when installed to internal storage)
- The Breath kernel provides (or can provide with some tweaking) all the same device support that ChromeOS provided.
- The end result is a customized kernel, the selected distro, and the selected desktop environment. So, in effect, Linux on a Chromebook.
- That Linux distro will be able to be used like a distro on any other hardware; e.g., receiving updates, the same commands, etc.

Is this a correct understanding? Just wanted to confirm that what I think I'm getting for all this effort is what I will really end up with. :-)

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
1. Yes, that's correct.
2. Mostly. It uses the same ChromeOS kernel but Google doesn't make their patches available, so sometimes you need some modification. I have never had to do this, though.
3. Yes.
4. Pretty much. Running Linux on a USB is a bit slow, but that applies for all systems. It would be a lot of work to publish an OTA  automatic kernel update system, and I don't have the servers, so to update the kernel (which you don't _need_ to do if it's stable) you just run `updatekernel_on_emmc` or something like that.

**Comment by RodBarnes** [comment]
I very much appreciate your willingness to help me figure out what is happening here.

Yesterday, I made another attempt on a completely different system -- one of my more powerful systems became available:

- AMD Ryzen 7 3700X ([comparison to Core i5)](https://www.cpubenchmark.net/compare/AMD-Ryzen-7-3700X-vs-Intel-i5-12400/3485vs4677)
- All SSD drives
- My internet connection for all systems is 100 Mbps fiber

I tried my previous command "bash setup.sh lxqt ubuntu impish-21.10". I started it at about 3pm and checked on it through the day. I noted when it began the unpacking stage and monitored more closely. But after seven hours, it had reached only 11% of the total unpacking and was just crawling.

Given what you described on your i5 that seemed excessive to me. But maybe the estimate you gave of 3 hours was only doing the "cli ubuntu"? Maybe it is the selection of lxqt or impish that is dragging things down?

So, I decided to start again: I reverted the system back to before the first test and began a new test of just "bash setup.sh cli ubuntu" to see what comes of it. I'll let this one run to completion and will let you know the results.

Again, I really do appreciate your remaining engaged on this. I recognize you could easily ignore my situation as a one-off.

--
Rod Barnes

------- Original Message -------

**Comment by MilkyDeveloper** [comment]
Alright, thanks :D
Theoretically, the script should run faster, as it has on my user’s devices, but I understand  that everyone’s situation is different. I think your CLI install will work well, since installing a desktop on the Chromebook itself is faster. I’m doing a major refactor which will make it support generating an ISO which you can then flash using a tried and tested tool such as Etcher or Rufus.

**Comment by RodBarnes** [comment]
After many attempts, I was successful (FINALLY!) completing the process and creating a USB that would boot in my Chromebook.  On this system (see previous comments), it took 35 minutes to complete.  (Note that this was using 'bash setup.sh cli ubuntu impish-21.10' because attempts to use the default ubuntu failed; it was giving errors about being unable to reach some of the sources.)

I'm now trying to do the recommended audio check (but sound-test or mpg123 aren't installed) and so trying to get WiFi connected (but iw is not installed).  Any suggested directions on these next steps would be appreciated.  Meanwhile, searching the internet...

**Comment by RodBarnes** [comment]
This may be a step outside of your project but I'm getting this message when I attempt to run 'speaker-test' to test the audio.  It appears that the Breath image doesn't include alsa.

[Error: Cannot access file /usr/share/alsa/alsa.conf](https://i.postimg.cc/KjwvFKgS/20220304-173803.jpg)

**Comment by MilkyDeveloper** [comment]
`nmtui` is used to connect to WiFi. Ubuntu uses NetworkManager by default. Moving binaries might work, but most of the time these are not static and you'll need to run `ld` or something similar. The error that you have is kind of weird, I've never encountered it. Maybe running `apt update; apt install alsa-*` would work?

**Comment by MilkyDeveloper** [comment]
Also, this morning, I introduced a feature that allows building to an ISO. Just append `FEATURES=ISO` and it should tell you where the ISO was built. This is wayyy faster and you can use tools like Etcher to flash it.

**Comment by RodBarnes** [comment]
I tried the ISO option this morning -- definitely much, much faster!  However, it got to near the end -- after I entered the passwords -- and for the last 20+ packages, it reported "No space left on device".

I see that /mnt is on "loop9" and I have no idea what the "loop" devices are -- see below:
`rod@BRAWN:~/Source/breath$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0     4K  1 loop /snap/bare/5
loop1         7:1    0  61.8M  1 loop /snap/core20/1169
loop2         7:2    0 242.3M  1 loop /snap/gnome-3-38-2004/76
loop3         7:3    0  65.2M  1 loop /snap/gtk-common-themes/1519
loop4         7:4    0  54.2M  1 loop /snap/snap-store/557
loop5         7:5    0 110.8M  1 loop /snap/core/12725
loop6         7:6    0 248.8M  1 loop /snap/gnome-3-38-2004/99
loop7         7:7    0  61.9M  1 loop /snap/core20/1361
loop8         7:8    0  54.2M  1 loop /snap/snap-store/558
loop9         7:9    0     6G  0 loop 
├─loop9p1   259:5    0    64M  0 part 
└─loop9p2   259:6    0   5.9G  0 part /mnt
sda           8:0    0 465.8G  0 disk 
├─sda1        8:1    0   128M  0 part 
└─sda2        8:2    0 465.6G  0 part 
sdb           8:16   0 465.8G  0 disk 
├─sdb1        8:17   0    16M  0 part 
└─sdb2        8:18   0 465.7G  0 part 
sdc           8:32   0 465.8G  0 disk 
├─sdc1        8:33   0    16M  0 part 
└─sdc2        8:34   0 465.7G  0 part 
sdd           8:48   0 465.8G  0 disk 
├─sdd1        8:49   0   128M  0 part 
└─sdd2        8:50   0 465.6G  0 part 
sde           8:64   0 232.9G  0 disk 
├─sde1        8:65   0   512M  0 part 
└─sde2        8:66   0 232.4G  0 part /
sr0          11:0    1  1024M  0 rom  
nvme0n1     259:0    0 931.5G  0 disk 
├─nvme0n1p1 259:1    0   100M  0 part /boot/efi
├─nvme0n1p2 259:2    0    16M  0 part 
├─nvme0n1p3 259:3    0 930.9G  0 part 
└─nvme0n1p4 259:4    0   509M  0 part `

**Comment by MilkyDeveloper** [comment]
Oops, I forgot about Ubuntu installs (which take more space). Try updating the git repo and run the command again, it *should* be fixed.

**Comment by RodBarnes** [comment]
Yes, this build seemed to work.  I found one other small thing but since you've closed this issue and the problem has morphed from the original issue, I'll put it in a new issue.
