### ISSUE TITLE
unable to setup audio (acer Chromebook 311 cb311-9h) (bobba)

### ISSUE THREAD

**Issue by br4zyy** [cb-linux/breath#71]
when I run sof-setup-audio,  it's unable to locate package firmware-sof-signed
![16459908607424641484948000255193](https://user-images.githubusercontent.com/99900883/155897199-9b31d198-2a11-463d-974a-f1bfadd8b859.jpg)

**Comment by MilkyDeveloper** [comment]
Try running: `sudo apt update`

**Comment by br4zyy** [comment]
it says all packages are up to date
![16460152832611665024364004179298](https://user-images.githubusercontent.com/99900883/155914148-79fadfb9-8b4a-49a6-83a7-6b5a6c97124c.jpg)

**Comment by l0k3n** [comment]
add non-free to you sources.list and it will install
