### ISSUE TITLE
Lenovo C340-15 broken audio

### ISSUE THREAD

**Issue by daffy1234** [cb-linux/breath#73]
None of the audio scripts work to set up the audio when using ubuntu.

Laptop: Lenovo C340-15
Model as seen on dev screen: PANTHEON C2B-A8L-J5K-26G-F7Z-Y2A-T96

**Comment by daffy1234** [comment]
Oops, didn't see you wanted output from some commands.

[Here's the `lsmod` output](https://github.com/cb-linux/breath/files/8158641/lsmod.output.txt)
[And here's from `find /usr/share/alsa`](https://github.com/cb-linux/breath/files/8158642/alsa.output.txt)

**Comment by daffy1234** [comment]
I've since tried running all three setup-audio commands from the docs on fresh installs, both after installing to internal storage and before. Anything else I can try? Any logs that would be helpful?

**Comment by MilkyDeveloper** [comment]
What about the output of `sudo alsa-info`? When it asks to upload a link, say "yes". If it doesn't upload a link, tell me the output of the file in `/tmp` it generates.

**Comment by daffy1234** [comment]
Got a few different logs for you. If you need anything else lemme know.

Ubuntu installed to internal storage, booted to internal storage, xubuntu-desktop installed, no audio setups were done:
[pre-sof-audio-setup-alsa-info.txt](https://github.com/cb-linux/breath/files/8236909/pre-sof-audio-setup-alsa-info.txt)

Same as above, but immediately after a `sof-audio-setup` and reboot:
[post-sof-audio-setup-alsa-info.txt](https://github.com/cb-linux/breath/files/8236910/post-sof-audio-setup-alsa-info.txt)

Chromeos installed to internal storage, booted to ubuntu usb, `audio-setup` ran:
[audio-setup-preinstall-alsa-info.txt](https://github.com/cb-linux/breath/files/8236912/audio-setup-preinstall-alsa-info.txt)

Same as above, but after installing to internal storage and a reboot to internal storage:
[audio-setup-postinstall-alsa-info.txt](https://github.com/cb-linux/breath/files/8236915/audio-setup-postinstall-alsa-info.txt)

**Comment by MilkyDeveloper** [comment]
Looks like this is a NAMI based device. Merging issue into #35

**Comment by MilkyDeveloper** [comment]
This issue has been fixed. Check out the audio section of the docs for info on `NAMI` devices.
