### ISSUE TITLE
Add Support for Samsung Chromebook 3

### ISSUE THREAD

**Issue by Parindraa** [cb-linux/breath#74]
It has a

- Intel Celeron N3060
- Intel HD Graphics 500
- 4 Gb ram

**Comment by MilkyDeveloper** [comment]
Have you tried testing it first? If it doesn’t show any errors or you can’t describe any, the issue will be closed.

**Comment by Parindraa** [comment]
> Have you tried testing it first? If it doesn’t show any errors or you can’t describe any, the issue will be closed.



> Have you tried testing it first? If it doesn’t show any errors or you can’t describe any, the issue will be closed.

I  tried testing it but it doesn't boot up

**Comment by MilkyDeveloper** [comment]
I’ve had people posting that their Samsung Chromebook 3 (Bluebird) works. Maybe it’s an error on your side? Try refollowing the updated steps.
