### ISSUE TITLE
Unable to adjust volume

### ISSUE THREAD

**Issue by wronglebowsk** [cb-linux/breath#76]
Hello, after successfully getting booted via USB everything seems to work great. Using sof-setup-audio and rebooting I do have sound now. However it seems to be stuck at max volume. I'm using Ubuntu 21.10 Impish. Nowhere in the system settings or in the quick settings in the top right seems to acknowledge it even has an audio device it's aware of. I am running on an Octopus device.

**Comment by MilkyDeveloper** [comment]
Yeah, this is an issue i've been aware about. You can use the `Master` volume setting in `alsamixer` to change the volume. I'm still currently figuring this out because this project is incompatible with PulseAudio.
