### ISSUE TITLE
Audio failure?

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#78]
I booted from the image (burned from the ISO), and attempted `speaker-test`.  It failed (output below).  Any recommendations?  Searching I do find other articles about the "cannot find card '0'" error so I'll research.

rod@ubuntu:~$ speaker-test

speaker-test 1.2.4

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
Playback open error: -2,No such file or directory

**Comment by MilkyDeveloper** [comment]
Did you run the audio commands mentioned in the docs?

**Comment by RodBarnes** [comment]
Yes. I ran 'sof-setup-audio' as this is an Acer CB515-1HT. Wasn't sure if I should yet try the 'SOUNDCARD=rtk sof-setup-audio'.

BTW: The hardware list on the breath wiki lists this device under 'reef'. Not sure where that name comes from but from a Google perspective, this is a 'sand' device but I don't even see that name listed. Not sure if this matters.

--
Rod Barnes

-------- Original Message --------

**Comment by MilkyDeveloper** [comment]
Sand is derived from reef. Reef audio is being tracked at #6, currently in at a standstill with it.
