### ISSUE TITLE
Webcam not working

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#80]
The webcam on my Acer CB515-1HT (ApolloLake) is not working.  When I open Cheese, the "camera on" LED lights but the image in the app is dark -- no video image.  For reference, in my testing of multiple Linux distros via LEGACY_BOOT, the webcam worked in every test without issue.  So, no idea why it wouldn't be working here.

**Comment by MilkyDeveloper** [comment]
The lights are probably something with i2c or some other communication through a standard seperate from the camera.

What's the output of `ls -ltrh /dev/video*`, `lsusb`, and `lspci`?

**Comment by RodBarnes** [comment]
Output is [here](https://termbin.com/9vmg).

**Comment by MilkyDeveloper** [comment]
Looks like this has a Chicony Webcam:
```
Chicony Electronics Co., Ltd HD WebCam
```
Thanks for letting me know! This should be a simple fix and I'll put it in the next kernel I build.

**Comment by RodBarnes** [comment]
Just checking:  In the prior comment you indicated this would be in v3.  I think that is the "Spring Release"?  If so, the webcam is still not working.  Not nagging, just checking. :-)

**Comment by MilkyDeveloper** [comment]
I think this is already compiled this. Does `sudo modprobe uvcvideo` work? I recently set this module to autoload on boot.

**Comment by RodBarnes** [comment]
An option is for me to go back to LEGACY_BOOT and boot into an Ubuntu image.  I know the webcam was working there so if there's something I could test, check, whatever there, I'm willing to go through the switch around.

**Comment by RodBarnes** [comment]
I'm closing this.  I found a simple test on [](https://www.onlinemictest.com/webcam-test/) and the camera worked.  So, seems something about Cheese...
