### ISSUE TITLE
Software updater fails

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#81]
Running Ubuntu (21.10): Anyone else experiencing failures running "Software Updater" or "Software & Updates"?  In both instances, they error and bring up the "submit report" dialog.

@MilkyDeveloper -- I tested this on a pure image of breath Ubuntu (no modifications) just to ensure that the other things we're currently investigating aren't a factor.  I submitted the reports but I captured the contents of both error reports and saved them as images (since it isn't possible to copy from them -- which seems stupid).  I also have the output of `dmesg`.  If you want any of this, let me know.

**Comment by wronglebowsk** [comment]
I've seen this as well. There seems to be some limitations even after installing to internal storage. 

I'm not sure if it's related but I also see failures trying to update the linux-firmware package. 

`trying to overwrite '/lib/firmware/intel/sof/sof-apl.ri', which is also in package firmware-sof-signed 1.7-1`

I assume this is due to the audio setup scripts. Perhaps we can have an "audio rollback" so this can be updated?

**Comment by RodBarnes** [comment]
I don't think it's related to audio setup. I ran a test with a pure Ubuntu 21.10 -- no modifications, no audio setup, nothing; just booted from the USB -- and it happens there

--
Rod Barnes

-------- Original Message --------

**Comment by wronglebowsk** [comment]
Seems like the "crashes" are stored in /var/crash. I've attached mine. It's titled 

`update-manager crashed with dbus.exceptions.DBusException in call_blocking(): org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute pr
ogram org.debian.apt: Permission denied`

For funsies I called it from the terminal with sudo but it still crashed.
[_usr_bin_update-manager.1000.txt](https://github.com/cb-linux/breath/files/8228528/_usr_bin_update-manager.1000.txt)

**Comment by RodBarnes** [comment]
I'm digging into this and will attempt to identify the cause.

**Comment by MilkyDeveloper** [comment]
Must have something to do with this being a minimal server image. I'll append this line to the postinstall script, so hopefully users won't encounter this in the future.

**Comment by RodBarnes** [comment]
UPDATE: I only needed to run `sudo apt-get install --reinstall dbus` and it fixed the problem.

**Comment by MilkyDeveloper** [comment]
Fixed in https://github.com/cb-linux/breath/commit/e26b1cb3dba3a9889cfcb1a400ea98e4dfe06b86
