### ISSUE TITLE
Arch: Add wireless_tools

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#82]
I was trying the Arch image.  I tried to setup the wifi but the wireless_tools aren't there; e.g., iwconfig, iwlist, etc.  I can't get these via `pacman` because, of course, I'm not connected and have no ability to connect network to my Chromebook -- Catch 22.

**Comment by MilkyDeveloper** [comment]
I think `nmcli` and `nmtui` are installed by default - I'll add to the docs about this.
