### ISSUE TITLE
Audio not working on Acer Spin 11

### ISSUE THREAD

**Issue by mrhappyma** [cb-linux/breath#83]
Hello!

Audio isn't working for my device. I keep getting this when running the commands:
```console
E: Unable to locate package firmware-sof-signed
```

Device is an Acer Chromebook Spin 11 (R751T / CP511), board name *"electro"*.

**Comment by mrhappyma** [comment]
Any estimate for when you'll have audio working?

**Comment by MilkyDeveloper** [comment]
It should already be working on Ubuntu. Follow the docs for audio.

**Comment by mrhappyma** [comment]
lol, looks like you just recently addd that.
i built the installer *before* that was added, any way to download the script? (there probably definitely is i just don't know how)

**Comment by mrhappyma** [comment]
nvm figured it out

**Comment by mrhappyma** [comment]
the files does exist... but this happens

![https://spongebob.is-from.space/r/nicememe.cymjufOIz2wKoaCdXSb.png](https://spongebob.is-from.space/r/nicememe.cymjufOIz2wKoaCdXSb.png)

**Comment by MilkyDeveloper** [comment]
Run `sudo apt install dos2unix`, `sudo dos2unix $(which apl-sof-setup-audio)`

**Comment by MilkyDeveloper** [comment]
This is a `reef` device, and all of these devices are tested to work. See #6 for more details.

**Comment by mrhappyma** [comment]
Hi, sorry for being quite late but still errors
```console
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gzip is already the newest version (1.10-4).
cgpt is already the newest version (0~R99-14469.B-1).
vboot-kernel-utils is already the newest version (0~R99-14469.B-1).
The following packages were automatically installed and are no longer required:
  hyphen-en-us javascript-common libpulsedsp libreoffice-help-common
  libreoffice-help-en-us libspeexdsp1 mythes-en-us node-normalize.css
  pulseaudio-utils
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package firmware-sof-signed
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package firmware-sof-signed
```

@MilkyDeveloper

**Comment by MilkyDeveloper** [comment]
@mrhappyma What distro are you on? Try Ubuntu.

**Comment by mrhappyma** [comment]
Thanks for the quick reply @MilkyDeveloper, I am on Debian.

Is there any way to try troubleshooting on Debian? Building the usb took several hours (using pop os on a usb on a 9 year old mac).

**Comment by mrhappyma** [comment]
Update:
As happened before, after the first restart after the audio script failing it now hangs on a blank screen with a white dash in the corner flashing when booting. I am re-building the USB with Ubuntu.
