### ISSUE TITLE
Audio on Asus Chromebook Flip C302

### ISSUE THREAD

**Issue by GlaZedBelmont** [cb-linux/breath#86]
lsmod output
`Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                122880  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
tun                    40960  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   20480  0
ah6                    16384  0
ip6t_REJECT            16384  2
ip6t_ipv6header        16384  0
vhost_vsock            20480  5
vhost                  36864  1 vhost_vsock
vmw_vsock_virtio_transport_common    24576  1 vhost_vsock
vsock                  36864  7 vmw_vsock_virtio_transport_common,vhost_vsock
8021q                  28672  0
veth                   20480  0
ccm                    20480  6
rfcomm                 45056  2
cmac                   16384  2
xt_cgroup              16384  2
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 20480  6 algif_hash,algif_skcipher
ipt_MASQUERADE         16384  1
uinput                 20480  0
btusb                  45056  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             458752  32 btrtl,btintel,btbcm,btusb,rfcomm
ecdh_generic           24576  1 bluetooth
uvcvideo               98304  0
videobuf2_vmalloc      16384  1 uvcvideo
videobuf2_memops       16384  1 videobuf2_vmalloc
videobuf2_v4l2         24576  1 uvcvideo
videobuf2_common       40960  2 videobuf2_v4l2,uvcvideo
iio_trig_hrtimer       16384  3
industrialio_sw_trigger    16384  1 iio_trig_hrtimer
industrialio_configfs    16384  2 industrialio_sw_trigger
snd_skl_nau88l25_max98357a    24576  4
snd_soc_hdac_hdmi      32768  1 snd_skl_nau88l25_max98357a
snd_soc_dmic           16384  1
snd_soc_skl_ssp_clk    16384  0
snd_soc_skl            77824  3 snd_soc_skl_ssp_clk
snd_soc_skl_ipc        49152  1 snd_soc_skl
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_sst_dsp        20480  1 snd_soc_skl_ipc
snd_soc_acpi_intel_match    28672  1 snd_soc_skl
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_soc_skl
snd_hda_ext_core       16384  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_intel_nhlt         16384  1 snd_soc_skl
snd_hda_core           61440  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
snd_soc_nau8825        45056  2 snd_skl_nau88l25_max98357a
acpi_als               16384  2
snd_soc_max98357a      16384  1
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                  102400  24
iio_trig_sysfs         16384  0
cros_ec_sensors        16384  2
cros_ec_sensors_core    16384  1 cros_ec_sensors
industrialio_triggered_buffer    16384  2 acpi_als,cros_ec_sensors_core
kfifo_buf              16384  2 industrialio_triggered_buffer,cros_ec_sensors_core
industrialio           57344  11 industrialio_triggered_buffer,iio_trig_hrtimer,cros_ec_sensors,acpi_als,kfifo_buf,iio_trig_sysfs,cros_ec_sensors_core
cros_ec_sensorhub      20480  1 cros_ec_sensors_core
iwlmvm                438272  0
iwl7000_mac80211      720896  1 iwlmvm
lzo_rle                16384  4
lzo_compress           16384  1 lzo_rle
zram                   20480  1
iwlwifi               368640  1 iwlmvm
cfg80211              573440  3 iwl7000_mac80211,iwlmvm,iwlwifi
joydev                 24576  0`

find /usr/share/alsa output:
`/usr/share/alsa
/usr/share/alsa/init
/usr/share/alsa/init/default
/usr/share/alsa/init/00main
/usr/share/alsa/init/help
/usr/share/alsa/init/hda
/usr/share/alsa/init/ca0106
/usr/share/alsa/init/test
/usr/share/alsa/init/info
/usr/share/alsa/speaker-test
/usr/share/alsa/speaker-test/sample_map.csv
/usr/share/alsa/ucm
/usr/share/alsa/ucm/Plantronics DA70
/usr/share/alsa/ucm/Plantronics DA70/Plantronics DA70.conf
/usr/share/alsa/ucm/Plantronics DA70/HiFi.conf
/usr/share/alsa/ucm/WD19 Dock
/usr/share/alsa/ucm/Logitech BRIO
/usr/share/alsa/ucm/Logitech BRIO/HiFi.conf
/usr/share/alsa/ucm/Logitech BRIO/Logitech BRIO.conf
/usr/share/alsa/ucm/Sennheiser USB headset
/usr/share/alsa/ucm/Sennheiser USB headset/Sennheiser USB headset.conf
/usr/share/alsa/ucm/Sennheiser USB headset/HiFi.conf
/usr/share/alsa/ucm/Logitech Webcam C930e
/usr/share/alsa/ucm/Logitech Webcam C930e/Logitech Webcam C930e.conf
/usr/share/alsa/ucm/Logitech Webcam C930e/HiFi.conf
/usr/share/alsa/ucm/Plantronics EncorePro 525 USB
/usr/share/alsa/ucm/Plantronics EncorePro 525 USB/Plantronics EncorePro 525 USB.conf
/usr/share/alsa/ucm/Plantronics EncorePro 525 USB/HiFi.conf
/usr/share/alsa/ucm/Scarlett 2i4 USB
/usr/share/alsa/ucm/Scarlett 2i4 USB/Scarlett 2i4 USB.conf
/usr/share/alsa/ucm/Scarlett 2i4 USB/HiFi.conf
/usr/share/alsa/ucm/Mi Dual Driver Earphones Type-C
/usr/share/alsa/ucm/Mi Dual Driver Earphones Type-C/Mi Dual Driver Earphones Type-C.conf
/usr/share/alsa/ucm/Mi Dual Driver Earphones Type-C/HiFi.conf
/usr/share/alsa/ucm/PCP-USB
/usr/share/alsa/ucm/PCP-USB/HiFi.conf
/usr/share/alsa/ucm/PCP-USB/PCP-USB.conf
/usr/share/alsa/ucm/WD15 Dock
/usr/share/alsa/ucm/Poly Blackwire 8225 Series
/usr/share/alsa/ucm/Poly Blackwire 8225 Series/HiFi.conf
/usr/share/alsa/ucm/Poly Blackwire 8225 Series/Poly Blackwire 8225 Series.conf
/usr/share/alsa/ucm/.keep_media-sound_alsa-utils-0.9
/usr/share/alsa/ucm/Chat 150 C
/usr/share/alsa/ucm/Chat 150 C/Chat 150 C.conf
/usr/share/alsa/ucm/Chat 150 C/HiFi.conf
/usr/share/alsa/ucm/Loopback
/usr/share/alsa/ucm/Loopback/HiFi.conf
/usr/share/alsa/ucm/Loopback/Loopback.conf
/usr/share/alsa/ucm/Dell AC511 USB SoundBar
/usr/share/alsa/ucm/Dell AC511 USB SoundBar/HiFi.conf
/usr/share/alsa/ucm/Dell AC511 USB SoundBar/Dell AC511 USB SoundBar.conf
/usr/share/alsa/ucm/ICUSBAUDIO7D
/usr/share/alsa/ucm/ICUSBAUDIO7D/HiFi.conf
/usr/share/alsa/ucm/ICUSBAUDIO7D/ICUSBAUDIO7D.conf
/usr/share/alsa/ucm/Hangouts Meet speakermic
/usr/share/alsa/ucm/Hangouts Meet speakermic/HiFi.conf
/usr/share/alsa/ucm/Hangouts Meet speakermic/Hangouts Meet speakermic.conf
/usr/share/alsa/ucm/Sennheiser SC 660 ANC USB
/usr/share/alsa/ucm/Sennheiser SC 660 ANC USB/HiFi.conf
/usr/share/alsa/ucm/Sennheiser SC 660 ANC USB/Sennheiser SC 660 ANC USB.conf
/usr/share/alsa/ucm/Dell-WD15-Dock
/usr/share/alsa/ucm/Dell-WD15-Dock/Dell-WD15-Dock.conf
/usr/share/alsa/ucm/Dell-WD15-Dock/HiFi.conf
/usr/share/alsa/ucm/Scarlett Solo USB
/usr/share/alsa/ucm/Scarlett Solo USB/Scarlett Solo USB.conf
/usr/share/alsa/ucm/Scarlett Solo USB/HiFi.conf
/usr/share/alsa/ucm/Pixel USB-C earbuds
/usr/share/alsa/ucm/Pixel USB-C earbuds/Pixel USB-C earbuds.conf
/usr/share/alsa/ucm/Pixel USB-C earbuds/HiFi.conf
/usr/share/alsa/ucm/Jabra SPEAK 810
/usr/share/alsa/ucm/Jabra SPEAK 810/Jabra SPEAK 810.conf
/usr/share/alsa/ucm/Jabra SPEAK 810/HiFi.conf
/usr/share/alsa/ucm/DELL PROFESSIONAL SOUND BAR AE5
/usr/share/alsa/ucm/DELL PROFESSIONAL SOUND BAR AE5/DELL PROFESSIONAL SOUND BAR AE5.conf
/usr/share/alsa/ucm/DELL PROFESSIONAL SOUND BAR AE5/HiFi.conf
/usr/share/alsa/ucm/USB 2.0 Camera
/usr/share/alsa/ucm/USB 2.0 Camera/HiFi.conf
/usr/share/alsa/ucm/USB 2.0 Camera/USB 2.0 Camera
/usr/share/alsa/ucm/HUAWEI USB-C HEADSET
/usr/share/alsa/ucm/HUAWEI USB-C HEADSET/HiFi.conf
/usr/share/alsa/ucm/HUAWEI USB-C HEADSET/HUAWEI USB-C HEADSET.conf
/usr/share/alsa/ucm/C505 HD Webcam
/usr/share/alsa/ucm/C505 HD Webcam/HiFi.conf
/usr/share/alsa/ucm/C505 HD Webcam/C505 HD Webcam.conf
/usr/share/alsa/ucm/sof-hda-dsp
/usr/share/alsa/ucm/sof-hda-dsp/sof-hda-dsp.conf
/usr/share/alsa/ucm/sof-hda-dsp/HiFi.conf
/usr/share/alsa/ucm/sklnau8825max
/usr/share/alsa/ucm/sklnau8825max/sklnau8825max.conf
/usr/share/alsa/ucm/sklnau8825max/HiFi.conf
/usr/share/alsa/ucm/Scarlett 2i2 USB
/usr/share/alsa/ucm/Scarlett 2i2 USB/Scarlett 2i2 USB.conf
/usr/share/alsa/ucm/Scarlett 2i2 USB/HiFi.conf
/usr/share/alsa/cards
/usr/share/alsa/cards/ENS1371.conf
/usr/share/alsa/cards/FM801.conf
/usr/share/alsa/cards/CMI8738-MC8.conf
/usr/share/alsa/cards/CMI8338.conf
/usr/share/alsa/cards/CMI8738-MC6.conf
/usr/share/alsa/cards/ATIIXP.conf
/usr/share/alsa/cards/GUS.conf
/usr/share/alsa/cards/vc4-hdmi.conf
/usr/share/alsa/cards/VIA686A.conf
/usr/share/alsa/cards/Echo_Echo3G.conf
/usr/share/alsa/cards/USB-Audio.conf
/usr/share/alsa/cards/VIA8233.conf
/usr/share/alsa/cards/EMU10K1.conf
/usr/share/alsa/cards/CMI8788.conf
/usr/share/alsa/cards/AU8820.conf
/usr/share/alsa/cards/PMacToonie.conf
/usr/share/alsa/cards/Audigy.conf
/usr/share/alsa/cards/VIA8233A.conf
/usr/share/alsa/cards/RME9652.conf
/usr/share/alsa/cards/SB-XFi.conf
/usr/share/alsa/cards/ENS1370.conf
/usr/share/alsa/cards/AACI.conf
/usr/share/alsa/cards/Maestro3.conf
/usr/share/alsa/cards/ICE1724.conf
/usr/share/alsa/cards/CS46xx.conf
/usr/share/alsa/cards/PMac.conf
/usr/share/alsa/cards/PC-Speaker.conf
/usr/share/alsa/cards/NFORCE.conf
/usr/share/alsa/cards/Audigy2.conf
/usr/share/alsa/cards/ICH-MODEM.conf
/usr/share/alsa/cards/ES1968.conf
/usr/share/alsa/cards/VXPocket440.conf
/usr/share/alsa/cards/ICE1712.conf
/usr/share/alsa/cards/EMU10K1X.conf
/usr/share/alsa/cards/RME9636.conf
/usr/share/alsa/cards/HdmiLpeAudio.conf
/usr/share/alsa/cards/VIA8237.conf
/usr/share/alsa/cards/SI7018.conf
/usr/share/alsa/cards/aliases.conf
/usr/share/alsa/cards/VX222.conf
/usr/share/alsa/cards/AU8810.conf
/usr/share/alsa/cards/CMI8338-SWIEC.conf
/usr/share/alsa/cards/PS3.conf
/usr/share/alsa/cards/AU8830.conf
/usr/share/alsa/cards/Loopback.conf
/usr/share/alsa/cards/Aureon71.conf
/usr/share/alsa/cards/VXPocket.conf
/usr/share/alsa/cards/FireWave.conf
/usr/share/alsa/cards/ATIIXP-SPDMA.conf
/usr/share/alsa/cards/CA0106.conf
/usr/share/alsa/cards/Aureon51.conf
/usr/share/alsa/cards/HDA-Intel.conf
/usr/share/alsa/cards/ICH4.conf
/usr/share/alsa/cards/pistachio-card.conf
/usr/share/alsa/cards/FWSpeakers.conf
/usr/share/alsa/cards/ICH.conf
/usr/share/alsa/cards/YMF744.conf
/usr/share/alsa/cards/ATIIXP-MODEM.conf
/usr/share/alsa/cards/TRID4DWAVENX.conf
/usr/share/alsa/alsa.conf
/usr/share/alsa/pcm
/usr/share/alsa/pcm/surround40.conf
/usr/share/alsa/pcm/modem.conf
/usr/share/alsa/pcm/iec958.conf
/usr/share/alsa/pcm/surround50.conf
/usr/share/alsa/pcm/surround51.conf
/usr/share/alsa/pcm/surround21.conf
/usr/share/alsa/pcm/default.conf
/usr/share/alsa/pcm/dsnoop.conf
/usr/share/alsa/pcm/surround71.conf
/usr/share/alsa/pcm/front.conf
/usr/share/alsa/pcm/dmix.conf
/usr/share/alsa/pcm/dpl.conf
/usr/share/alsa/pcm/rear.conf
/usr/share/alsa/pcm/side.conf
/usr/share/alsa/pcm/surround41.conf
/usr/share/alsa/pcm/center_lfe.conf
/usr/share/alsa/pcm/hdmi.conf`

**Comment by GlaZedBelmont** [comment]
god it didn't paste the newlines, I'm so sorry

**Comment by MilkyDeveloper** [comment]
This is an SKL chromebook, merging into #16
