### ISSUE TITLE
Audio issues on Bluebird(octopus)

### ISSUE THREAD

**Issue by DumbGameMaker** [cb-linux/breath#89]
I have a samsung chromebook 4 (bluebird, octopus). Audio works fine, but I can't for the life of me get the headphone jack working. It is unmuted in AlsaMixer but no audio.
using Ubuntu 21.04.

**Comment by MilkyDeveloper** [comment]
Currently, headphone jacks are not working at all due to kernel issues. There's nothing I can do at the moment to fix this.
