### ISSUE TITLE
ASUS Chromebook C523 only built in speakers work after executing apl-sof-setup-audio

### ISSUE THREAD

**Issue by andrzej-onja** [cb-linux/breath#92]
created an iso 
`FEATURES=ISO bash setup.sh gnome ubuntu impish-21.10`

booted up and run:
`apl-sof-setup-audio`

rebooted and speakers work but very loud, jack not working, usb audio not working 

I also have MrChromebox firmware installed with just ubuntu 21.04 (from https://www.linuxium.com.au/isos [Apollo](https://www.google.com/url?q=https%3A%2F%2Furl.linuxium.com.au%2Flatest-apollo-ubuntu-21_04_iso&sa=D&sntz=1&usg=AFQjCNG1CEU4i8m0k7MVPbchhpW0ih6ahA) (-i ubuntu-21.04-desktop-amd64.iso --apollo)) and audio is woring over USB including mic (no internal audio). This is still abetter option as I can have control over volume and recording working...

Nice work anyway, let me know if you want me to run something 

BABYTIGER C6C-A3G-B4Q-63-A2L

﻿```
 lsmod
Module                  Size  Used by
snd_soc_max98357a      16384  1
snd_hda_intel          49152  0
snd_soc_skl           143360  0
snd_soc_sst_ipc        16384  1 snd_soc_skl
snd_soc_sst_dsp        36864  1 snd_soc_skl
snd_sof_pci_intel_apl    16384  0
snd_sof_intel_hda_common    86016  1 snd_sof_pci_intel_apl
snd_sof_intel_hda      16384  1 snd_sof_intel_hda_common
snd_sof_pci            20480  2 snd_sof_intel_hda_common,snd_sof_pci_intel_apl
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_soc_hdac_hda       20480  2 snd_sof_intel_hda_common,snd_soc_skl
snd_soc_acpi_intel_match    57344  3 snd_sof_intel_hda_common,snd_soc_skl,snd_sof_pci_intel_apl
snd_sof               126976  2 snd_sof_pci,snd_sof_intel_hda_common
snd_soc_acpi           16384  3 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_soc_skl
snd_intel_dspcfg       24576  3 snd_hda_intel,snd_sof_intel_hda_common,snd_soc_skl
ledtrig_audio          16384  1 snd_sof
snd_usb_audio         294912  0
snd_usbmidi_lib        36864  1 snd_usb_audio
snd_seq_midi           16384  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_seq                81920  2 snd_seq_midi,snd_seq_midi_event
snd_rawmidi            36864  2 snd_seq_midi,snd_usbmidi_lib
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_soc_dmic           16384  1
snd_hda_codec_hdmi     65536  1
snd_soc_sst_bxt_da7219_max98357a    28672  0
snd_soc_intel_hda_dsp_common    16384  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_hdac_hdmi      32768  1 snd_soc_sst_bxt_da7219_max98357a
snd_hda_ext_core       32768  5 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_da7219         77824  2 snd_soc_sst_bxt_da7219_max98357a
snd_hda_codec         163840  4 snd_hda_codec_hdmi,snd_hda_intel,snd_soc_intel_hda_dsp_common,snd_soc_hdac_hda
snd_hwdep              16384  2 snd_usb_audio,snd_hda_codec
snd_hda_core          106496  10 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_intel_hda_dsp_common,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
dm_multipath           32768  0
crc32c_intel           24576  0
btusb                  53248  0
btrtl                  24576  1 btusb
btbcm                  20480  1 btusb
btintel                45056  1 btusb
bluetooth             630784  25 btrtl,btintel,btbcm,btusb
joydev                 24576  0
ecdh_generic           16384  2 bluetooth
ecc                    36864  1 ecdh_generic
acpi_als               16384  1
industrialio_triggered_buffer    16384  1 acpi_als
kfifo_buf              16384  1 industrialio_triggered_buffer
industrialio           86016  3 industrialio_triggered_buffer,acpi_als,kfifo_buf
vfat                   20480  0
fat                    86016  1 vfat
nls_cp437              20480  0
nls_iso8859_1          16384  0
uvcvideo              126976  0
videobuf2_vmalloc      16384  1 uvcvideo
iwlmvm                401408  0
iwlwifi               376832  1 iwlmvm
fuse                  143360  3
junak@ubuntu:~$ find /user/share/alsa
find: ‘/user/share/alsa’: No such file or directory
junak@ubuntu:~$ find /usr/share/alsa
/usr/share/alsa
/usr/share/alsa/speaker-test
/usr/share/alsa/speaker-test/sample_map.csv
/usr/share/alsa/ucm2
/usr/share/alsa/ucm2/README.md
/usr/share/alsa/ucm2/codecs
/usr/share/alsa/ucm2/codecs/rt5651
/usr/share/alsa/ucm2/codecs/rt5651/IN2-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5651/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5651/HeadPhones-swapped.conf
/usr/share/alsa/ucm2/codecs/rt5651/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN2-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/DigitalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN3-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN12-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt715
/usr/share/alsa/ucm2/codecs/rt715/init.conf
/usr/share/alsa/ucm2/codecs/rt5682
/usr/share/alsa/ucm2/codecs/rt5682/init.conf
/usr/share/alsa/ucm2/codecs/wcd934x
/usr/share/alsa/ucm2/codecs/wcd934x/HeadphoneEnableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/SpeakerDisableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/SpeakerEnableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/HeadphoneDisableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/HeadphoneMicDisableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/DefaultDisableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/HeadphoneMicEnableSeq.conf
/usr/share/alsa/ucm2/codecs/wcd934x/DefaultEnableSeq.conf
/usr/share/alsa/ucm2/codecs/cx2072x
/usr/share/alsa/ucm2/codecs/cx2072x/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/cx2072x/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/cx2072x/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/cx2072x/InternalMic.conf
/usr/share/alsa/ucm2/codecs/cx2072x/Speaker.conf
/usr/share/alsa/ucm2/codecs/cx2072x/DisableSeq.conf
/usr/share/alsa/ucm2/codecs/hda
/usr/share/alsa/ucm2/codecs/hda/hdmi.conf
/usr/share/alsa/ucm2/codecs/rt711
/usr/share/alsa/ucm2/codecs/rt711/init.conf
/usr/share/alsa/ucm2/codecs/rt700
/usr/share/alsa/ucm2/codecs/rt700/init.conf
/usr/share/alsa/ucm2/codecs/max98090
/usr/share/alsa/ucm2/codecs/max98090/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/max98090/Headphones.conf
/usr/share/alsa/ucm2/codecs/max98090/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/max98090/InternalMic.conf
/usr/share/alsa/ucm2/codecs/max98090/Speaker.conf
/usr/share/alsa/ucm2/codecs/wsa881x
/usr/share/alsa/ucm2/codecs/wsa881x/SpeakerDisableSeq.conf
/usr/share/alsa/ucm2/codecs/wsa881x/SpeakerEnableSeq.conf
/usr/share/alsa/ucm2/codecs/wsa881x/DefaultEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645
/usr/share/alsa/ucm2/codecs/rt5645/HeadphonesEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/HSMicEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/SpeakerEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/DigitalMicDisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/HSMicDisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/DigitalMicEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/AnalogMic.conf
/usr/share/alsa/ucm2/codecs/rt5645/DisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5672
/usr/share/alsa/ucm2/codecs/rt5672/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5672/DMIC2.conf
/usr/share/alsa/ucm2/codecs/rt5672/DMIC1.conf
/usr/share/alsa/ucm2/codecs/rt5672/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5672/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5672/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5672/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5640
/usr/share/alsa/ucm2/codecs/rt5640/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5640/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5640/IN3-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5640/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5640/DigitalMics.conf
/usr/share/alsa/ucm2/codecs/rt5640/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5640/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5640/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/es8316
/usr/share/alsa/ucm2/codecs/es8316/IN2-InternalMic.conf
/usr/share/alsa/ucm2/codecs/es8316/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/es8316/IN1-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/es8316/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/es8316/Speaker.conf
/usr/share/alsa/ucm2/codecs/es8316/IN2-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/es8316/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/es8316/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/nau8824
/usr/share/alsa/ucm2/codecs/nau8824/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/nau8824/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/nau8824/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/nau8824/InternalMic.conf
/usr/share/alsa/ucm2/codecs/nau8824/Speaker.conf
/usr/share/alsa/ucm2/codecs/nau8824/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt711-sdca
/usr/share/alsa/ucm2/codecs/rt711-sdca/init.conf
/usr/share/alsa/ucm2/codecs/rt715-sdca
/usr/share/alsa/ucm2/codecs/rt715-sdca/init.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672
/usr/share/alsa/ucm2/cht-bsw-rt5672/cht-bsw-rt5672.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/HiFi.conf
/usr/share/alsa/ucm2/sof-soundwire
/usr/share/alsa/ucm2/sof-soundwire/rt1316-1.conf
/usr/share/alsa/ucm2/sof-soundwire/rt715.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1316-2.conf
/usr/share/alsa/ucm2/sof-soundwire/rt711-sdca.conf
/usr/share/alsa/ucm2/sof-soundwire/sof-soundwire.conf
/usr/share/alsa/ucm2/sof-soundwire/rt715-sdca.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1308-2.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1308-1.conf
/usr/share/alsa/ucm2/sof-soundwire/rt5682.conf
/usr/share/alsa/ucm2/sof-soundwire/rt711.conf
/usr/share/alsa/ucm2/sof-soundwire/rt700.conf
/usr/share/alsa/ucm2/sof-soundwire/HiFi.conf
/usr/share/alsa/ucm2/sof-soundwire/Hdmi.conf
/usr/share/alsa/ucm2/bytcr-rt5651
/usr/share/alsa/ucm2/bytcr-rt5651/bytcr-rt5651.conf
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi-LongName.conf
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi.conf
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi-Components.conf
/usr/share/alsa/ucm2/bytcr-rt5640
/usr/share/alsa/ucm2/bytcr-rt5640/bytcr-rt5640.conf
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi-LongName.conf
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi.conf
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi-Components.conf
/usr/share/alsa/ucm2/SOF
/usr/share/alsa/ucm2/SOF/SOF.conf
/usr/share/alsa/ucm2/SOF/HiFi.conf
/usr/share/alsa/ucm2/chtmax98090
/usr/share/alsa/ucm2/chtmax98090/chtmax98090.conf
/usr/share/alsa/ucm2/chtmax98090/HiFi.conf
/usr/share/alsa/ucm2/bytcht-es8316
/usr/share/alsa/ucm2/bytcht-es8316/HiFi-LongName.conf
/usr/share/alsa/ucm2/bytcht-es8316/bytcht-es8316.conf
/usr/share/alsa/ucm2/bytcht-es8316/HiFi.conf
/usr/share/alsa/ucm2/bytcht-es8316/HiFi-Components.conf
/usr/share/alsa/ucm2/Qualcomm
/usr/share/alsa/ucm2/Qualcomm/apq8096
/usr/share/alsa/ucm2/Qualcomm/apq8096/HDMI.conf
/usr/share/alsa/ucm2/Qualcomm/apq8096/apq8096.conf
/usr/share/alsa/ucm2/Qualcomm/apq8096/HiFi.conf
/usr/share/alsa/ucm2/Qualcomm/sdm845
/usr/share/alsa/ucm2/Qualcomm/sdm845/HDMI.conf
/usr/share/alsa/ucm2/Qualcomm/sdm845/sdm845.conf
/usr/share/alsa/ucm2/Qualcomm/sdm845/HiFi.conf
/usr/share/alsa/ucm2/Qualcomm/apq8016-sbc
/usr/share/alsa/ucm2/Qualcomm/apq8016-sbc/HDMI.conf
/usr/share/alsa/ucm2/Qualcomm/apq8016-sbc/apq8016-sbc.conf
/usr/share/alsa/ucm2/Qualcomm/apq8016-sbc/HiFi.conf
/usr/share/alsa/ucm2/chtnau8824
/usr/share/alsa/ucm2/chtnau8824/chtnau8824.conf
/usr/share/alsa/ucm2/chtnau8824/HiFi.conf
/usr/share/alsa/ucm2/module
/usr/share/alsa/ucm2/module/snd_soc_rk3399_gru_sound.conf
/usr/share/alsa/ucm2/module/snd_soc_omap_abe_twl6040.conf
/usr/share/alsa/ucm2/module/snd_acp3x_rn.conf
/usr/share/alsa/ucm2/module/lib
/usr/share/alsa/ucm2/module/lib/linked.conf
/usr/share/alsa/ucm2/module/snd_soc_apq8096.conf
/usr/share/alsa/ucm2/module/snd_soc_sdm845.conf
/usr/share/alsa/ucm2/module/snd_soc_apq8016_sbc.conf
/usr/share/alsa/ucm2/module/snd_soc_rockchip_max98090.conf
/usr/share/alsa/ucm2/module/snd_soc_snow.conf
/usr/share/alsa/ucm2/module/snd_soc_tegra_max98090.conf
/usr/share/alsa/ucm2/module/snd_soc_tegra_alc5632.conf
/usr/share/alsa/ucm2/chtrt5650
/usr/share/alsa/ucm2/chtrt5650/chtrt5650.conf
/usr/share/alsa/ucm2/chtrt5650/HiFi.conf
/usr/share/alsa/ucm2/Rockchip
/usr/share/alsa/ucm2/Rockchip/rk3399-gru-sound
/usr/share/alsa/ucm2/Rockchip/rk3399-gru-sound/rk3399-gru-sound.conf
/usr/share/alsa/ucm2/Rockchip/rk3399-gru-sound/HiFi.conf
/usr/share/alsa/ucm2/Rockchip/max98090
/usr/share/alsa/ucm2/Rockchip/max98090/max98090.conf
/usr/share/alsa/ucm2/Rockchip/max98090/HiFi.conf
/usr/share/alsa/ucm2/ucm.conf
/usr/share/alsa/ucm2/OMAP
/usr/share/alsa/ucm2/OMAP/abe-twl6040
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/FMAnalog.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/Voice.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/VoiceCall.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/SDP4430.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/HiFiLP.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/Record.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/SDP4430/HiFi.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/FMAnalog.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/Voice.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/VoiceCall.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/HiFiLP.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/Record.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/HiFi.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/Pandaboard/Pandaboard.conf
/usr/share/alsa/ucm2/OMAP/abe-twl6040/abe-twl6040.conf
/usr/share/alsa/ucm2/Samsung
/usr/share/alsa/ucm2/Samsung/snow
/usr/share/alsa/ucm2/Samsung/snow/snow.conf
/usr/share/alsa/ucm2/Samsung/snow/HiFi.conf
/usr/share/alsa/ucm2/chtrt5645
/usr/share/alsa/ucm2/chtrt5645/chtrt5645.conf
/usr/share/alsa/ucm2/chtrt5645/HiFi.conf
/usr/share/alsa/ucm2/HDA-Intel
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-DualCodecs.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-dual.conf
/usr/share/alsa/ucm2/HDA-Intel/init.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-analog.conf
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-Lenovo-DualCodecs.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi.conf
/usr/share/alsa/ucm2/HDA-Intel/Hdmi.conf
/usr/share/alsa/ucm2/HDA-Intel/HDA-Intel.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-acp.conf
/usr/share/alsa/ucm2/HDA-Intel/HDA-Capture-value.conf
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-Gigabyte-ALC1220DualCodecs.conf
/usr/share/alsa/ucm2/sof-hda-dsp
/usr/share/alsa/ucm2/sof-hda-dsp/sof-hda-dsp.conf
/usr/share/alsa/ucm2/sof-hda-dsp/HiFi.conf
/usr/share/alsa/ucm2/sof-hda-dsp/Hdmi.conf
/usr/share/alsa/ucm2/hda-dsp
/usr/share/alsa/ucm2/hda-dsp/Hdmi1.conf
/usr/share/alsa/ucm2/hda-dsp/hda-dsp.conf
/usr/share/alsa/ucm2/hda-dsp/HiFi.conf
/usr/share/alsa/ucm2/hda-dsp/Hdmi2.conf
/usr/share/alsa/ucm2/broxton-rt298
/usr/share/alsa/ucm2/broxton-rt298/broxton-rt298.conf
/usr/share/alsa/ucm2/broxton-rt298/HiFi.conf
/usr/share/alsa/ucm2/broxton-rt298/Hdmi.conf
/usr/share/alsa/ucm2/Tegra
/usr/share/alsa/ucm2/Tegra/max98090
/usr/share/alsa/ucm2/Tegra/max98090/max98090.conf
/usr/share/alsa/ucm2/Tegra/max98090/HiFi.conf
/usr/share/alsa/ucm2/Tegra/alc5632
/usr/share/alsa/ucm2/Tegra/alc5632/alc5632.conf
/usr/share/alsa/ucm2/Tegra/alc5632/Record.conf
/usr/share/alsa/ucm2/Tegra/alc5632/HiFi.conf
/usr/share/alsa/ucm2/bdw-rt5677
/usr/share/alsa/ucm2/bdw-rt5677/bdw-rt5677.conf
/usr/share/alsa/ucm2/bdw-rt5677/HiFi.conf
/usr/share/alsa/ucm2/skylake-rt286
/usr/share/alsa/ucm2/skylake-rt286/Hdmi1.conf
/usr/share/alsa/ucm2/skylake-rt286/skylake-rt286.conf
/usr/share/alsa/ucm2/skylake-rt286/HiFi.conf
/usr/share/alsa/ucm2/skylake-rt286/Hdmi2.conf
/usr/share/alsa/ucm2/USB-Audio
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main.conf
/usr/share/alsa/ucm2/USB-Audio/Realtek-ALC1220-VB-Desktop.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-Desktop-Rear-Line.conf
/usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-Desktop-Rear.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-Desktop-Front-Speaker.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-Desktop-Front.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-Desktop-Front-Headset.conf
/usr/share/alsa/ucm2/USB-Audio/Realtek-ALC1220-VB-Desktop-HiFi.conf
/usr/share/alsa/ucm2/kblrt5660
/usr/share/alsa/ucm2/kblrt5660/kblrt5660.conf
/usr/share/alsa/ucm2/kblrt5660/Hdmi1.conf
/usr/share/alsa/ucm2/kblrt5660/HiFi.conf
/usr/share/alsa/ucm2/kblrt5660/Hdmi2.conf
/usr/share/alsa/ucm2/broadwell-rt286
/usr/share/alsa/ucm2/broadwell-rt286/broadwell-rt286.conf
/usr/share/alsa/ucm2/broadwell-rt286/HiFi.conf
/usr/share/alsa/ucm2/bytcht-cx2072x
/usr/share/alsa/ucm2/bytcht-cx2072x/bytcht-cx2072x.conf
/usr/share/alsa/ucm2/bytcht-cx2072x/HiFi.conf
/usr/share/alsa/ucm2/platforms
/usr/share/alsa/ucm2/platforms/bytcr
/usr/share/alsa/ucm2/platforms/bytcr/PlatformEnableSeq.conf
/usr/share/alsa/ucm2/platforms/bytcr/PlatformDisableSeq.conf
/usr/share/alsa/ucm
/usr/share/alsa/ucm/README.md
/usr/share/alsa/init
/usr/share/alsa/init/help
/usr/share/alsa/init/00main
/usr/share/alsa/init/default
/usr/share/alsa/init/hda
/usr/share/alsa/init/info
/usr/share/alsa/init/test
/usr/share/alsa/init/ens1371
/usr/share/alsa/init/ca0106
/usr/share/alsa/alsa.conf
/usr/share/alsa/cards
/usr/share/alsa/cards/ATIIXP-SPDMA.conf
/usr/share/alsa/cards/ENS1371.conf
/usr/share/alsa/cards/AU8820.conf
/usr/share/alsa/cards/NFORCE.conf
/usr/share/alsa/cards/AU8810.conf
/usr/share/alsa/cards/EMU10K1.conf
/usr/share/alsa/cards/PS3.conf
/usr/share/alsa/cards/VXPocket.conf
/usr/share/alsa/cards/CS46xx.conf
/usr/share/alsa/cards/ES1968.conf
/usr/share/alsa/cards/CA0106.conf
/usr/share/alsa/cards/pistachio-card.conf
/usr/share/alsa/cards/TRID4DWAVENX.conf
/usr/share/alsa/cards/ATIIXP-MODEM.conf
/usr/share/alsa/cards/VXPocket440.conf
/usr/share/alsa/cards/CMI8788.conf
/usr/share/alsa/cards/ICH4.conf
/usr/share/alsa/cards/USB-Audio.conf
/usr/share/alsa/cards/YMF744.conf
/usr/share/alsa/cards/FWSpeakers.conf
/usr/share/alsa/cards/VIA8233A.conf
/usr/share/alsa/cards/CMI8738-MC6.conf
/usr/share/alsa/cards/PMacToonie.conf
/usr/share/alsa/cards/GUS.conf
/usr/share/alsa/cards/CMI8338.conf
/usr/share/alsa/cards/ICH-MODEM.conf
/usr/share/alsa/cards/aliases.conf
/usr/share/alsa/cards/Audigy.conf
/usr/share/alsa/cards/Aureon71.conf
/usr/share/alsa/cards/CMI8338-SWIEC.conf
/usr/share/alsa/cards/vc4-hdmi.conf
/usr/share/alsa/cards/VIA8237.conf
/usr/share/alsa/cards/VX222.conf
/usr/share/alsa/cards/FireWave.conf
/usr/share/alsa/cards/AACI.conf
/usr/share/alsa/cards/FM801.conf
/usr/share/alsa/cards/SB-XFi.conf
/usr/share/alsa/cards/ICE1712.conf
/usr/share/alsa/cards/PMac.conf
/usr/share/alsa/cards/Loopback.conf
/usr/share/alsa/cards/SI7018.conf
/usr/share/alsa/cards/ATIIXP.conf
/usr/share/alsa/cards/VIA8233.conf
/usr/share/alsa/cards/ICE1724.conf
/usr/share/alsa/cards/PC-Speaker.conf
/usr/share/alsa/cards/HdmiLpeAudio.conf
/usr/share/alsa/cards/Maestro3.conf
/usr/share/alsa/cards/Audigy2.conf
/usr/share/alsa/cards/ENS1370.conf
/usr/share/alsa/cards/RME9636.conf
/usr/share/alsa/cards/VIA686A.conf
/usr/share/alsa/cards/ICH.conf
/usr/share/alsa/cards/Echo_Echo3G.conf
/usr/share/alsa/cards/HDA-Intel.conf
/usr/share/alsa/cards/CMI8738-MC8.conf
/usr/share/alsa/cards/RME9652.conf
/usr/share/alsa/cards/AU8830.conf
/usr/share/alsa/cards/EMU10K1X.conf
/usr/share/alsa/cards/Aureon51.conf
/usr/share/alsa/topology
/usr/share/alsa/topology/broadwell
/usr/share/alsa/topology/broadwell/broadwell.conf
/usr/share/alsa/topology/sklrt286
/usr/share/alsa/topology/sklrt286/skl_i2s.conf
/usr/share/alsa/topology/hda-dsp
/usr/share/alsa/topology/hda-dsp/skl_hda_dsp_generic-tplg.conf
/usr/share/alsa/topology/bxtrt298
/usr/share/alsa/topology/bxtrt298/bxt_i2s.conf
/usr/share/alsa/pcm
/usr/share/alsa/pcm/rear.conf
/usr/share/alsa/pcm/surround21.conf
/usr/share/alsa/pcm/surround40.conf
/usr/share/alsa/pcm/center_lfe.conf
/usr/share/alsa/pcm/iec958.conf
/usr/share/alsa/pcm/hdmi.conf
/usr/share/alsa/pcm/surround51.conf
/usr/share/alsa/pcm/front.conf
/usr/share/alsa/pcm/dpl.conf
/usr/share/alsa/pcm/surround71.conf
/usr/share/alsa/pcm/side.conf
/usr/share/alsa/pcm/modem.conf
/usr/share/alsa/pcm/surround41.conf
/usr/share/alsa/pcm/default.conf
/usr/share/alsa/pcm/surround50.conf
/usr/share/alsa/pcm/dmix.conf
/usr/share/alsa/pcm/dsnoop.conf
/usr/share/alsa/utils.sh
/usr/share/alsa/alsa.conf.d
/usr/share/alsa/alsa.conf.d/10-samplerate.conf
/usr/share/alsa/alsa.conf.d/50-jack.conf
/usr/share/alsa/alsa.conf.d/50-pulseaudio.conf
/usr/share/alsa/alsa.conf.d/98-usb-stream.conf
/usr/share/alsa/alsa.conf.d/50-arcam-av-ctl.conf
/usr/share/alsa/alsa.conf.d/50-oss.conf
/usr/share/alsa/alsa.conf.d/10-speexrate.conf
/usr/share/alsa/alsa.conf.d/60-vdownmix.conf
/usr/share/alsa/alsa.conf.d/60-upmix.conf

```

**Comment by MilkyDeveloper** [comment]
Yes, it's a limitation over the kernel. You can control the volume using the `Master` option in `alsamixer`

**Comment by andrzej-onja** [comment]
Thanks, how about usb and jack audio is there any way to make it work ?

**Comment by MilkyDeveloper** [comment]
Nope, not at the moment.
