### ISSUE TITLE
Need help building kernel modules

### ISSUE THREAD

**Issue by karsacui** [cb-linux/breath#98]
I was trying to install wireguard and virtualbox. Both of them require to build custom kernel modules. To build kmods, kernel headers are required. As far as I am concerned, there're no kernel headers on this edited linux distro, nor can the headers be installed from apt-get.

**Comment by aghebert** [comment]
I have this problem too.

**Comment by hede5562** [comment]
correct. Currently the headers are not copied to the usb-media or image. 
If you build your own kernel (there's some how-to here) you can add the needed step to install also header files. `make headers_install INSTALL_HDR_PATH=[DIRECTORY]` and then copying all those files to the destination system should do the trick. 
Maybe in the future someone will also add those functionality to the scripts which create the kernel.

**Comment by MilkyDeveloper** [comment]
This should be trivial to add - I'll do it soon.

**Comment by runcros** [comment]
Soon the integration of UEFI in Breath will generate the headers you are looking for, so I am closing this issue which will have its solution very soon.
